In [1]:
#importing libraries
import pandas as pd
import numpy as np

In [2]:
# Load CSV files into DataFrames for each region
db_buses_goa=pd.read_csv("df_goa.csv")
df_buses_rajasthan=pd.read_csv("df_rajasthan.csv")
df_buses_telangana=pd.read_csv("df_telangana.csv")
df_buses_kerala=pd.read_csv("df_kerala.csv")
df_buses_AS=pd.read_csv("df_AS.csv")
df_buses_bengal=pd.read_csv("df_bengal.csv")
df_buses_andhra=pd.read_csv("df_andhra.csv")
df_buses_up=pd.read_csv("df_up.csv")
df_buses_wb=pd.read_csv("df_wb.csv")
df_buses_himachal=pd.read_csv("df_himachal.csv")

**Data cleaning**

**goa**

In [3]:
db_buses_goa

,Bus_name,Bus_type,Start_time,End_time,Total_duration,Price,Seats_Available,Ratings,Route_link,Route_name,State
0,Atmaram Gobus,VE A/C Sleeper (2+1),21:00:00,07:30:00,04:30:00,1450,6,4.7,https://www.redbus.in/bus-tickets/pune-to-goa,Pune to Goa,Goa
1,Atmaram Gobus,VE A/C Sleeper (2+1),22:30:00,08:45:00,07:15:00,1499,3,4.6,https://www.redbus.in/bus-tickets/pune-to-goa,Pune to Goa,Goa
2,IntrCity SmartBus,Bharat Benz A/C Seater /Sleeper (2+1),21:15:00,08:05:00,05:20:00,1419,19,4.5,https://www.redbus.in/bus-tickets/pune-to-goa,Pune to Goa,Goa
3,Ashray Amrutyog,A/C Sleeper (2+1),22:05:00,09:30:00,07:35:00,1599,17,4.4,https://www.redbus.in/bus-tickets/pune-to-goa,Pune to Goa,Goa
4,Kadamba Transport Corporation Limited (KTCL) -...,Non AC Seater 2+2,18:00:00,08:00:00,02:00:00,600,26,4.0,https://www.redbus.in/bus-tickets/goa-to-pune,Goa to Pune,Goa
...,...,...,...,...,...,...,...,...,...,...,...
123,UNIQUE TOURS AND TRAVELS,A/C Seater Push Back (2+1),08:30:00,20:00:00,04:30:00,400,17,3.2,https://www.redbus.in/bus-tickets/calangute-go...,Calangute (goa) to Goa,Goa
124,Kadamba Transport Corporation Limited (KTCL) -...,A/C Seater (2+3),12:30:00,13:25:00,01:55:00,200,47,3.6,https://www.redbus.in/bus-tickets/mopa-airport...,Mopa Airport to Panaji,Goa
125,Kadamba Transport Corporation Limited (KTCL) -...,Non AC Seater 2+2,16:00:00,18:15:00,10:15:00,140,25,3.6,https://www.redbus.in/bus-tickets/belagavi-to-...,Belagavi to Saquelim,Goa
126,Kadamba Transport Corporation Limited (KTCL) -...,AC Seater (2+2),10:00:00,10:31:00,20:31:00,100,41,3.6,https://www.redbus.in/bus-tickets/calangute-go...,Calangute (goa) to Panaji,Goa
127,Kadamba Transport Corporation Limited (KTCL) -...,AC Seater (2+2),15:30:00,16:01:00,07:31:00,100,41,3.6,https://www.redbus.in/bus-tickets/calangute-go...,Calangute (goa) to Panaji,Goa

In [217]:
# Clean the 'Start_time' column by removing extra spaces
df_buses_AS['Start_time'] = df_buses_AS['Start_time'].str.strip()

# Check if the cleaning helped
print(df_buses_AS['Start_time'].head())

0    21:15:00
1    23:00:00
2    21:15:00
3    19:15:00
4    19:30:00
Name: Start_time, dtype: object

In [218]:
db_buses_goa['Start_time'].unique()

<DatetimeArray>
['1900-01-01 21:00:00', '1900-01-01 22:30:00', '1900-01-01 21:15:00',
 '1900-01-01 22:05:00', '1900-01-01 18:00:00', '1900-01-01 21:32:00',
 '1900-01-01 20:30:00', '1900-01-01 18:30:00', '1900-01-01 16:30:00',
 '1900-01-01 20:00:00', '1900-01-01 19:35:00', '1900-01-01 16:46:00',
 '1900-01-01 17:15:00', '1900-01-01 20:50:00', '1900-01-01 19:40:00',
 '1900-01-01 19:30:00', '1900-01-01 16:00:00', '1900-01-01 04:00:00',
 '1900-01-01 06:30:00', '1900-01-01 07:00:00', '1900-01-01 10:35:00',
 '1900-01-01 19:45:00', '1900-01-01 21:20:00', '1900-01-01 17:00:00',
 '1900-01-01 17:01:00', '1900-01-01 08:30:00', '1900-01-01 10:20:00',
 '1900-01-01 10:30:00', '1900-01-01 12:30:00', '1900-01-01 23:15:00',
 '1900-01-01 00:00:00', '1900-01-01 18:45:00', '1900-01-01 19:00:00',
 '1900-01-01 16:40:00', '1900-01-01 18:10:00', '1900-01-01 15:40:00',
 '1900-01-01 10:00:00', '1900-01-01 15:30:00', '1900-01-01 21:45:00',
 '1900-01-01 23:59:00', '1900-01-01 06:00:00', '1900-01-01 11:45:00',
 '1900-01-01 07:30:00', '1900-01-01 13:45:00', '1900-01-01 08:00:00',
 '1900-01-01 10:15:00', '1900-01-01 11:30:00', '1900-01-01 12:00:00',
 '1900-01-01 23:00:00', '1900-01-01 23:45:00', '1900-01-01 10:31:00',
 '1900-01-01 16:01:00', '1900-01-01 05:15:00', '1900-01-01 15:00:00',
 '1900-01-01 08:15:00', '1900-01-01 14:30:00', '1900-01-01 20:19:00',
 '1900-01-01 17:30:00', '1900-01-01 09:25:00', '1900-01-01 13:30:00',
 '1900-01-01 15:55:00', '1900-01-01 19:15:00']
Length: 62, dtype: datetime64[ns]

In [51]:
import pandas as pd

# Function to convert 'hh h mm m' format to 'hh:mm:ss' format
def convert_to_hms(duration):
    try:
        hours = 0
        minutes = 0
        seconds = 0
        
        # Check for hours and minutes in the string, extract the numeric values
        if 'h' in duration:
            hours = int(duration.split('h')[0].strip())  # Extract hours
        if 'm' in duration:
            minutes = int(duration.split('m')[0].split()[-1].strip())  # Extract minutes
        
        # Format to hh:mm:ss
        time_str = f'{hours:02}:{minutes:02}:{seconds:02}'
        return time_str
    except Exception as e:
        return "Invalid Format"

# Apply the function to the 'Total_duration' column in-place
db_buses_goa['Total_duration'] = db_buses_goa['Total_duration'].apply(convert_to_hms)

# Display the updated DataFrame to confirm the changes
print(db_buses_goa[['Total_duration']])

    Total_duration
0         00:00:00
1         00:00:00
2         00:00:00
3         00:00:00
4         00:00:00
..             ...
123       00:00:00
124       00:00:00
125       00:00:00
126       00:00:00
127       00:00:00

[128 rows x 1 columns]

In [52]:
db_buses_goa["Price"]=db_buses_goa["Price"].astype(str)

In [53]:
#convert prices to numeric
db_buses_goa["Price"]=db_buses_goa["Price"].str.replace("INR","")
db_buses_goa["Price"]=db_buses_goa["Price"].astype(float)
db_buses_goa["Price"].fillna(0)

0      1450.0
1      1499.0
2      1419.0
3      1599.0
4       600.0
        ...
123     400.0
124     200.0
125     140.0
126     100.0
127     100.0
Name: Price, Length: 128, dtype: float64

In [54]:
# Convert price column to numeric, setting errors='coerce' to replace invalid values with NaN
db_buses_goa['Price'] = pd.to_numeric(db_buses_goa['Price'], errors='coerce')

# Replace NaN (missing values) in the price column with a default value or None (for NULL in MySQL)
db_buses_goa['Price'] = db_buses_goa['Price'].fillna(0)  # Replace NaN with 0, or use None for NULL

In [55]:
db_buses_goa['Price'].unique()

array([ 1450.,  1499.,  1419.,  1599.,   600.,  1099.,   900.,  1119.,
        2193.,  1782.,  1945.,  1400.,  1722.,  1200.,  1000.,  1188.,
         170.,  7200.,  1799.,  1496.,  1899.,  2699.,  2799.,  2370.,
         800.,   999.,   879.,   809.,   950.,  1100.,   650.,   449.,
         350.,   450.,   499.,   850.,  1850.,   700.,   735.,   949.,
        1550.,  1044.,   899.,   978.,   200.,   675.,  3000.,  1139.,
         140.,   150.,   490.,   505.,   699.,   400.,  1699.,  2080.,
        1600.,   550.,   990.,  1399., 11000.,   100.])

In [56]:
# Print rows where 'Price' is NaN
print(db_buses_goa[db_buses_goa['Price'].isnull()])

# Drop rows with NaN in 'Price'
db_buses_goa.dropna(subset=['Price'], inplace=True)

Empty DataFrame
Columns: [Bus_name, Bus_type, Start_time, End_time, Total_duration, Price, Seats_Available, Ratings, Route_link, Route_name, State]
Index: []

In [57]:
import numpy as np
import re

# Function to clean the Ratings column
def clean_rating(value):
    # If the value is one of the invalid ones, return NaN
    if str(value).lower() in ['nan', 'new', ' ', 'none']:
        return np.nan
    # Attempt to extract a numeric value from the string
    match = re.match(r'(\d+\.\d+)', str(value))
    if match:
        return float(match.group(1))
    # If no match is found, return NaN
    return np.nan

# Clean the Ratings column
db_buses_goa['Ratings'] = db_buses_goa['Ratings'].apply(clean_rating)

# Show the cleaned data
print(db_buses_goa[['Ratings']].head())

   Ratings
0      4.7
1      4.6
2      4.5
3      4.4
4      4.0

In [58]:
db_buses_goa['Ratings'].unique()

array([4.7, 4.6, 4.5, 4.4, 4. , 4.8, 4.1, 3.8, 3.2, 3.4, 4.3, 3.6, 3. ,
       3.3, 3.5, 2.8, 2.7, 1.9, 3.9, 3.7, 2.1, 4.2, 2.9, 2.6, 5. , 3.1,
       1.7, 4.9, 2.3, 1.6])

In [59]:
db_buses_goa['Seats_Available'].unique()

array([ 6,  3, 19, 17, 26,  2, 11, 22, 16, 18, 15, 21, 25, 27,  4,  8,  1,
       13,  5, 20, 29, 30, 23, 32, 34, 28, 12, 24, 41, 42, 36, 46, 47, 45,
       48, 33, 31, 38])

In [60]:
# Fill any missing values (NaN) in the 'Seats_Available' column with the string "not available"
db_buses_goa['Seats_Available']=db_buses_goa['Seats_Available'].fillna("not available")

In [62]:
db_buses_goa['Seats_Available'].unique()

array([ 6,  3, 19, 17, 26,  2, 11, 22, 16, 18, 15, 21, 25, 27,  4,  8,  1,
       13,  5, 20, 29, 30, 23, 32, 34, 28, 12, 24, 41, 42, 36, 46, 47, 45,
       48, 33, 31, 38])

In [4]:
missing_values =db_buses_goa.isnull().sum()
print("Missing values per column:\n", missing_values)

Missing values per column:
 Bus_name           0
Bus_type           0
Start_time         0
End_time           0
Total_duration     0
Price              0
Seats_Available    0
Ratings            0
Route_link         0
Route_name         0
State              0
dtype: int64

In [64]:
# Remove rows with missing values in any column
db_buses_goa = db_buses_goa.dropna()

In [65]:
print("Data after removing rows with missing values:\n", db_buses_goa)

Data after removing rows with missing values:
                                               Bus_name  \
0                                        Atmaram Gobus
1                                        Atmaram Gobus
2                                    IntrCity SmartBus
3                                      Ashray Amrutyog
4    Kadamba Transport Corporation Limited (KTCL) -...
..                                                 ...
123                           UNIQUE TOURS AND TRAVELS
124  Kadamba Transport Corporation Limited (KTCL) -...
125  Kadamba Transport Corporation Limited (KTCL) -...
126  Kadamba Transport Corporation Limited (KTCL) -...
127  Kadamba Transport Corporation Limited (KTCL) -...

                                  Bus_type Start_time  End_time  \
0                     VE A/C Sleeper (2+1)   21:00:00  07:30:00
1                     VE A/C Sleeper (2+1)   22:30:00  08:45:00
2    Bharat Benz A/C Seater /Sleeper (2+1)   21:15:00  08:05:00
3                        A/C Sleeper (2+1)   22:05:00  09:30:00
4                        Non AC Seater 2+2   18:00:00  08:00:00
..                                     ...        ...       ...
123             A/C Seater Push Back (2+1)   08:30:00  20:00:00
124                       A/C Seater (2+3)   12:30:00  13:25:00
125                      Non AC Seater 2+2   16:00:00  18:15:00
126                        AC Seater (2+2)   10:00:00  10:31:00
127                        AC Seater (2+2)   15:30:00  16:01:00

    Total_duration   Price  Seats_Available  Ratings  \
0         00:00:00  1450.0                6      4.7
1         00:00:00  1499.0                3      4.6
2         00:00:00  1419.0               19      4.5
3         00:00:00  1599.0               17      4.4
4         00:00:00   600.0               26      4.0
..             ...     ...              ...      ...
123       00:00:00   400.0               17      3.2
124       00:00:00   200.0               47      3.6
125       00:00:00   140.0               25      3.6
126       00:00:00   100.0               41      3.6
127       00:00:00   100.0               41      3.6

                                            Route_link  \
0        https://www.redbus.in/bus-tickets/pune-to-goa
1        https://www.redbus.in/bus-tickets/pune-to-goa
2        https://www.redbus.in/bus-tickets/pune-to-goa
3        https://www.redbus.in/bus-tickets/pune-to-goa
4        https://www.redbus.in/bus-tickets/goa-to-pune
..                                                 ...
123  https://www.redbus.in/bus-tickets/calangute-go...
124  https://www.redbus.in/bus-tickets/mopa-airport...
125  https://www.redbus.in/bus-tickets/belagavi-to-...
126  https://www.redbus.in/bus-tickets/calangute-go...
127  https://www.redbus.in/bus-tickets/calangute-go...

                    Route_name State
0                  Pune to Goa   Goa
1                  Pune to Goa   Goa
2                  Pune to Goa   Goa
3                  Pune to Goa   Goa
4                  Goa to Pune   Goa
..                         ...   ...
123     Calangute (goa) to Goa   Goa
124     Mopa Airport to Panaji   Goa
125       Belagavi to Saquelim   Goa
126  Calangute (goa) to Panaji   Goa
127  Calangute (goa) to Panaji   Goa

[128 rows x 11 columns]

In [3]:
db_buses_goa.to_csv('db_cleaned_goa.csv', index=False)

In [4]:
path=r"C:\Users\kella\OneDrive\Desktop\guvi\redbus project\df_goa.csv"
db_buses_goa.to_csv(path,index=False)

In [4]:
db_buses_goa

,Bus_name,Bus_type,Start_time,End_time,Total_duration,Price,Seats_Available,Ratings,Route_link,Route_name,State
0,Atmaram Gobus,VE A/C Sleeper (2+1),21:00:00,07:30:00,04:30:00,1450,6,4.7,https://www.redbus.in/bus-tickets/pune-to-goa,Pune to Goa,Goa
1,Atmaram Gobus,VE A/C Sleeper (2+1),22:30:00,08:45:00,07:15:00,1499,3,4.6,https://www.redbus.in/bus-tickets/pune-to-goa,Pune to Goa,Goa
2,IntrCity SmartBus,Bharat Benz A/C Seater /Sleeper (2+1),21:15:00,08:05:00,05:20:00,1419,19,4.5,https://www.redbus.in/bus-tickets/pune-to-goa,Pune to Goa,Goa
3,Ashray Amrutyog,A/C Sleeper (2+1),22:05:00,09:30:00,07:35:00,1599,17,4.4,https://www.redbus.in/bus-tickets/pune-to-goa,Pune to Goa,Goa
4,Kadamba Transport Corporation Limited (KTCL) -...,Non AC Seater 2+2,18:00:00,08:00:00,02:00:00,600,26,4.0,https://www.redbus.in/bus-tickets/goa-to-pune,Goa to Pune,Goa
...,...,...,...,...,...,...,...,...,...,...,...
123,UNIQUE TOURS AND TRAVELS,A/C Seater Push Back (2+1),08:30:00,20:00:00,04:30:00,400,17,3.2,https://www.redbus.in/bus-tickets/calangute-go...,Calangute (goa) to Goa,Goa
124,Kadamba Transport Corporation Limited (KTCL) -...,A/C Seater (2+3),12:30:00,13:25:00,01:55:00,200,47,3.6,https://www.redbus.in/bus-tickets/mopa-airport...,Mopa Airport to Panaji,Goa
125,Kadamba Transport Corporation Limited (KTCL) -...,Non AC Seater 2+2,16:00:00,18:15:00,10:15:00,140,25,3.6,https://www.redbus.in/bus-tickets/belagavi-to-...,Belagavi to Saquelim,Goa
126,Kadamba Transport Corporation Limited (KTCL) -...,AC Seater (2+2),10:00:00,10:31:00,20:31:00,100,41,3.6,https://www.redbus.in/bus-tickets/calangute-go...,Calangute (goa) to Panaji,Goa
127,Kadamba Transport Corporation Limited (KTCL) -...,AC Seater (2+2),15:30:00,16:01:00,07:31:00,100,41,3.6,https://www.redbus.in/bus-tickets/calangute-go...,Calangute (goa) to Panaji,Goa

**RAJASTHAN**

In [8]:
df_buses_rajasthan

,Bus_name,Bus_type,Start_time,End_time,Total_duration,Price,Seats_Available,Ratings,Route_link,Route_name,State
0,M R Travels,A/C Seater / Sleeper (2+1),15:55:00,20:00:00,04:05:00,550.0,10,3.8,https://www.redbus.in/bus-tickets/jodhpur-to-a...,Jodhpur to Ajmer,Rajasthan
1,Jain travels regd,NON AC Seater/ Sleeper (2+1),17:00:00,22:55:00,05:55:00,330.0,38,4.1,https://www.redbus.in/bus-tickets/jodhpur-to-a...,Jodhpur to Ajmer,Rajasthan
2,Jakhar Travels,NON A/C Seater/ Sleeper (2+1),18:00:00,23:15:00,05:15:00,450.0,29,3.9,https://www.redbus.in/bus-tickets/jodhpur-to-a...,Jodhpur to Ajmer,Rajasthan
3,V k jain travels,A/C Seater / Sleeper (2+1),18:15:00,23:20:00,05:05:00,500.0,38,3.0,https://www.redbus.in/bus-tickets/jodhpur-to-a...,Jodhpur to Ajmer,Rajasthan
4,M R Travels,NON A/C Seater/ Sleeper (2+1),18:30:00,23:40:00,05:10:00,495.0,30,3.8,https://www.redbus.in/bus-tickets/jodhpur-to-a...,Jodhpur to Ajmer,Rajasthan
...,...,...,...,...,...,...,...,...,...,...,...
69,M R Travels,Volvo Multi-Axle I-Shift B11R Semi Sleeper (2+2),17:40:00,21:00:00,03:20:00,612.0,0,4.6,https://www.redbus.in/bus-tickets/pali-to-udaipur,Pali (Rajasthan) to Udaipur,Rajasthan
70,Shree Devnarayan Travels,Bharat Benz A/C Seater (2+1),18:10:00,21:40:00,03:30:00,550.0,0,3.0,https://www.redbus.in/bus-tickets/pali-to-udaipur,Pali (Rajasthan) to Udaipur,Rajasthan
71,Lake City Travels,AC Sleeper (2+1),22:15:00,07:05:00,08:50:00,489.0,0,4.7,https://www.redbus.in/bus-tickets/udaipur-to-j...,Udaipur to Jaipur (Rajasthan),Rajasthan
72,Raj travels,A/C Sleeper (2+1),22:00:00,06:30:00,08:30:00,639.0,0,4.8,https://www.redbus.in/bus-tickets/udaipur-to-j...,Udaipur to Jaipur (Rajasthan),Rajasthan
73,METRO RAJLAXMI TRAVELS,A/C Sleeper (2+1),22:02:00,06:42:00,08:40:00,500.0,0,4.1,https://www.redbus.in/bus-tickets/udaipur-to-j...,Udaipur to Jaipur (Rajasthan),Rajasthan

In [82]:

# Check for missing values again
missing_values = df_buses_rajasthan.isnull().sum()
print("Missing values per column after cleaning:\n", missing_values)

Missing values per column after cleaning:
 Bus_name           0
Bus_type           0
Start_time         0
End_time           0
Total_duration     0
Price              0
Seats_Available    0
Ratings            0
Route_link         0
Route_name         0
State              0
dtype: int64

In [83]:
df_buses_rajasthan['Total_duration'].unique()

array(['04:05:00', '05:55:00', '05:15:00', '05:05:00', '05:10:00',
       '03:25:00', '03:30:00', '02:39:00', '04:30:00', '04:45:00',
       '07:00:00', '07:20:00', '02:55:00', '03:00:00', '03:27:00',
       '02:40:00', '08:45:00', '06:45:00', '09:00:00', '04:40:00',
       '06:01:00', '05:20:00', '06:09:00', '07:41:00', '07:25:00',
       '02:00:00', '03:50:00', '03:29:00', '03:20:00', '03:15:00',
       '04:20:00', '04:00:00', '03:35:00', '05:12:00', '04:50:00',
       '05:45:00', '05:30:00', '08:30:00', '06:30:00', '04:34:00',
       '05:40:00', '02:20:00', '04:15:00', '06:15:00', '08:50:00',
       '08:40:00'], dtype=object)

In [84]:
df_buses_rajasthan['Start_time'].unique()

array(['15:55:00', '17:00:00', '18:00:00', '18:15:00', '18:30:00',
       '17:20:00', '19:30:00', '21:20:00', '21:45:00', '17:10:00',
       '22:30:00', '23:00:00', '22:15:00', '18:45:00', '20:04:00',
       '20:40:00', '21:15:00', '23:45:00', '19:00:00', '23:59:00',
       '16:00:00', '20:30:00', '21:25:00', '23:44:00', '21:30:00',
       '21:00:00', '17:30:00', '19:10:00', '19:01:00', '19:20:00',
       '16:15:00', '17:55:00', '22:00:00', '16:20:00', '16:30:00',
       '17:40:00', '18:10:00', '22:02:00'], dtype=object)

In [85]:
print(df_buses_rajasthan["Price"].dtype)

int64

In [86]:
df_buses_rajasthan["Price"] = df_buses_rajasthan["Price"].astype(str)

In [87]:
#convert prices to numeric
df_buses_rajasthan["Price"]=df_buses_rajasthan["Price"].str.replace("INR","")
df_buses_rajasthan["Price"]=df_buses_rajasthan["Price"].astype(float)
df_buses_rajasthan["Price"].fillna(0)

0     550.0
1     330.0
2     450.0
3     500.0
4     495.0
      ...
69    612.0
70    550.0
71    489.0
72    639.0
73    500.0
Name: Price, Length: 74, dtype: float64

In [88]:
df_buses_rajasthan['Price'].unique()

array([ 550.,  330.,  450.,  500.,  495.,  300.,  350.,  485.,  510.,
        600.,  270.,  315.,  400.,  349.,  308.,  333.,  280.,  299.,
        397.,  499.,  446.,  619.,  523.,  408.,  459., 1099.,  206.,
        549.,  739.,  990.,  289.,  720.,  700.,  267.,  571.,  612.,
        489.,  639.])

In [89]:
df_buses_rajasthan['Ratings'].unique()

array([3.8, 4.1, 3.9, 3. , 4. , 3.4, 4.6, 4.5, 4.4, 4.3, 4.7, 3.5, 3.6,
       4.2, 2.2, 2.7, 3.7, 3.3, 4.9, 1.7, 3.1, 4.8])

In [90]:
df_buses_rajasthan['Seats_Available'].unique()

array([10, 38, 29, 30, 25, 33,  8, 34, 40, 28, 31, 16, 52, 41,  3, 27, 26,
       44, 11, 48, 23,  7,  5, 21, 13, 42, 36,  0])

In [47]:
df_buses_rajasthan['Seats_Available'].unique()

array([], dtype=int64)

In [93]:
df_buses_rajasthan['State'].unique()

array(['Rajasthan'], dtype=object)

In [9]:
missing_values =df_buses_rajasthan.isnull().sum()
print("Missing values per column:\n", missing_values)

Missing values per column:
 Bus_name           0
Bus_type           0
Start_time         0
End_time           0
Total_duration     0
Price              0
Seats_Available    0
Ratings            0
Route_link         0
Route_name         0
State              0
dtype: int64

In [94]:
# Remove rows with missing values in any column
df_buses_rajasthan = df_buses_rajasthan.dropna()

In [4]:
df_buses_rajasthan.to_csv('df_cleaned_rajasthan.csv', index=False)

In [6]:
df_buses_rajasthan

,Bus_name,Bus_type,Start_time,End_time,Total_duration,Price,Seats_Available,Ratings,Route_link,Route_name,State
0,M R Travels,A/C Seater / Sleeper (2+1),15:55:00,20:00:00,04:05:00,550.0,10,3.8,https://www.redbus.in/bus-tickets/jodhpur-to-a...,Jodhpur to Ajmer,Rajasthan
1,Jain travels regd,NON AC Seater/ Sleeper (2+1),17:00:00,22:55:00,05:55:00,330.0,38,4.1,https://www.redbus.in/bus-tickets/jodhpur-to-a...,Jodhpur to Ajmer,Rajasthan
2,Jakhar Travels,NON A/C Seater/ Sleeper (2+1),18:00:00,23:15:00,05:15:00,450.0,29,3.9,https://www.redbus.in/bus-tickets/jodhpur-to-a...,Jodhpur to Ajmer,Rajasthan
3,V k jain travels,A/C Seater / Sleeper (2+1),18:15:00,23:20:00,05:05:00,500.0,38,3.0,https://www.redbus.in/bus-tickets/jodhpur-to-a...,Jodhpur to Ajmer,Rajasthan
4,M R Travels,NON A/C Seater/ Sleeper (2+1),18:30:00,23:40:00,05:10:00,495.0,30,3.8,https://www.redbus.in/bus-tickets/jodhpur-to-a...,Jodhpur to Ajmer,Rajasthan
...,...,...,...,...,...,...,...,...,...,...,...
69,M R Travels,Volvo Multi-Axle I-Shift B11R Semi Sleeper (2+2),17:40:00,21:00:00,03:20:00,612.0,0,4.6,https://www.redbus.in/bus-tickets/pali-to-udaipur,Pali (Rajasthan) to Udaipur,Rajasthan
70,Shree Devnarayan Travels,Bharat Benz A/C Seater (2+1),18:10:00,21:40:00,03:30:00,550.0,0,3.0,https://www.redbus.in/bus-tickets/pali-to-udaipur,Pali (Rajasthan) to Udaipur,Rajasthan
71,Lake City Travels,AC Sleeper (2+1),22:15:00,07:05:00,08:50:00,489.0,0,4.7,https://www.redbus.in/bus-tickets/udaipur-to-j...,Udaipur to Jaipur (Rajasthan),Rajasthan
72,Raj travels,A/C Sleeper (2+1),22:00:00,06:30:00,08:30:00,639.0,0,4.8,https://www.redbus.in/bus-tickets/udaipur-to-j...,Udaipur to Jaipur (Rajasthan),Rajasthan
73,METRO RAJLAXMI TRAVELS,A/C Sleeper (2+1),22:02:00,06:42:00,08:40:00,500.0,0,4.1,https://www.redbus.in/bus-tickets/udaipur-to-j...,Udaipur to Jaipur (Rajasthan),Rajasthan

**TELANGANA**

In [12]:
df_buses_telangana

,Bus_name,Bus_type,Start_time,End_time,Total_duration,Price,Seats_Available,Ratings,Route_link,Route_name,State
0,Bharathi Tours & Travels,A/C Sleeper (2+1),00:50:00,05:30:00,04:40:00,590,1,4.5,https://www.redbus.in/bus-tickets/khammam-to-h...,Khammam to Hyderabad,Telangana
1,Sri Rama Travels,A/C Seater / Sleeper (2+1),01:30:00,06:45:00,05:15:00,777,2,4.1,https://www.redbus.in/bus-tickets/khammam-to-h...,Khammam to Hyderabad,Telangana
2,BSR Tours And Travels,NON A/C Seater (2+2),23:40:00,06:00:00,06:20:00,610,19,4.5,https://www.redbus.in/bus-tickets/khammam-to-h...,Khammam to Hyderabad,Telangana
3,FRESHBUS,Electric A/C Seater (2+2),05:50:00,12:25:00,06:35:00,550,20,4.7,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Telangana
4,FRESHBUS,Electric A/C Seater (2+2),10:25:00,17:55:00,07:30:00,349,28,4.7,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Telangana
...,...,...,...,...,...,...,...,...,...,...,...
78,Morning Star Travels,Scania AC Multi Axle Sleeper (2+1),03:40:00,09:45:00,06:05:00,500,23,2.7,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Godavarikhani,Telangana
79,Morning Star Travels,Scania AC Multi Axle Sleeper (2+1),17:00:00,21:55:00,04:55:00,1990,19,2.7,https://www.redbus.in/bus-tickets/peddapalli-t...,Peddapalli (Telangana) to Hyderabad,Telangana
80,NueGo,Electric A/C Seater (2+2),05:00:00,10:30:00,05:30:00,332,7,4.8,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Kodad,Telangana
81,NueGo,Electric A/C Seater (2+2),09:30:00,15:05:00,05:35:00,408,22,3.9,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Kodad,Telangana
82,NueGo,Electric A/C Seater/Sleeper (2+1),10:30:00,15:55:00,05:25:00,332,17,3.7,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Kodad,Telangana

In [109]:
# Clean the 'Start_time' column by removing extra spaces
df_buses_telangana['Start_time'] = df_buses_telangana['Start_time'].str.strip()

# Check if the cleaning helped
print(df_buses_telangana['Start_time'].head())

0    00:50:00
1    01:30:00
2    23:40:00
3    05:50:00
4    10:25:00
Name: Start_time, dtype: object

In [110]:
# Clean the 'End_time' column by removing extra spaces
df_buses_telangana['End_time'] = df_buses_telangana['End_time'].str.strip()

# Check if the cleaning helped
print(df_buses_telangana['End_time'].head())

0    05:30:00
1    06:45:00
2    06:00:00
3    12:25:00
4    17:55:00
Name: End_time, dtype: object

In [111]:
df_buses_telangana

,Bus_name,Bus_type,Start_time,End_time,Total_duration,Price,Seats_Available,Ratings,Route_link,Route_name,State
0,Bharathi Tours & Travels,A/C Sleeper (2+1),00:50:00,05:30:00,04:40:00,590,1,4.5,https://www.redbus.in/bus-tickets/khammam-to-h...,Khammam to Hyderabad,Telangana
1,Sri Rama Travels,A/C Seater / Sleeper (2+1),01:30:00,06:45:00,05:15:00,777,2,4.1,https://www.redbus.in/bus-tickets/khammam-to-h...,Khammam to Hyderabad,Telangana
2,BSR Tours And Travels,NON A/C Seater (2+2),23:40:00,06:00:00,06:20:00,610,19,4.5,https://www.redbus.in/bus-tickets/khammam-to-h...,Khammam to Hyderabad,Telangana
3,FRESHBUS,Electric A/C Seater (2+2),05:50:00,12:25:00,06:35:00,550,20,4.7,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Telangana
4,FRESHBUS,Electric A/C Seater (2+2),10:25:00,17:55:00,07:30:00,349,28,4.7,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Telangana
...,...,...,...,...,...,...,...,...,...,...,...
79,Morning Star Travels,Scania AC Multi Axle Sleeper (2+1),03:40:00,09:45:00,06:05:00,500,23,2.7,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Godavarikhani,Telangana
80,Morning Star Travels,Scania AC Multi Axle Sleeper (2+1),17:00:00,21:55:00,04:55:00,1990,19,2.7,https://www.redbus.in/bus-tickets/peddapalli-t...,Peddapalli (Telangana) to Hyderabad,Telangana
81,NueGo,Electric A/C Seater (2+2),05:00:00,10:30:00,05:30:00,332,7,4.8,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Kodad,Telangana
82,NueGo,Electric A/C Seater (2+2),09:30:00,15:05:00,05:35:00,408,22,3.9,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Kodad,Telangana
83,NueGo,Electric A/C Seater/Sleeper (2+1),10:30:00,15:55:00,05:25:00,332,17,3.7,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Kodad,Telangana

In [112]:
df_buses_telangana['Total_duration'].unique()

array(['04:40:00', '05:15:00', '06:20:00', '06:35:00', '07:30:00',
       '06:00:00', '07:25:00', '04:00:00', '06:45:00', '07:00:00',
       '07:55:00', '03:25:00', '03:15:00', '03:50:00', '06:30:00',
       '05:45:00', '04:30:00', '04:15:00', '04:50:00', '07:45:00',
       '05:25:00', '03:30:00', '08:30:00', '08:35:00', '06:05:00',
       '06:29:00', '06:25:00', '04:20:00', '07:12:00', '08:00:00',
       '07:40:00', '05:05:00', '03:00:00', '03:35:00', '03:10:00',
       '07:15:00', '05:10:00', '03:45:00', '09:50:00', '11:20:00',
       '11:00:00', '09:00:00', '03:20:00', '03:55:00', '04:55:00',
       '05:30:00', '05:35:00'], dtype=object)

In [113]:
df_buses_telangana['Price'].unique()

array([ 590,  777,  610,  550,  349,  670,  555,  800,    0,  524,  442,
       1129, 2000, 3000,  450,  500,  629, 1080,  780, 1036,  799,  900,
       1200, 1289, 1409,  989,  700, 1990,  711,  749,  738,  600,  810,
        750,  400, 2100,  392,  464,  689,  580,  891, 1624,  499,  699,
        789, 1479,  893,  809, 1090,  660,  751,  332,  408])

In [63]:
# Print rows where 'Price' is NaN
print(df_buses_telangana[df_buses_telangana['Price'].isnull()])

# Drop rows with NaN in 'Price'
df_buses_telangana.dropna(subset=['Price'], inplace=True)

Empty DataFrame
Columns: [Bus_name, Bus_type, Start_time, End_time, Total_duration, Price, Seats_Available, Ratings, Route_link, Route_name]
Index: []

In [114]:
df_buses_telangana['Ratings'].unique()

array([4.5, 4.1, 4.7, 3. , 3.9, 3.8, nan, 3.7, 4.2, 2.7, 1.8, 1. , 4. ,
       3.2, 4.6, 1.2, 2.4, 1.6, 2.9, 4.3, 4.4, 3.4, 3.1, 3.3, 2.5, 2.8,
       4.9, 2.6, 3.6, 4.8])

In [115]:
df_buses_telangana['Seats_Available'].unique()

array([ 1,  2, 19, 20, 28, 38, 30, 36, 29,  0,  8, 23, 14, 18,  6, 12, 42,
       35,  5, 13,  7, 22, 21, 25,  3, 26, 33, 11, 16, 31, 24, 27, 17, 41,
       15, 32, 45])

In [69]:
df_buses_telangana['Seats_Available'].unique()

array([ 1,  2, 19, 20, 28, 38, 30, 36, 29,  0,  8, 23, 14, 18,  6, 12, 42,
       35,  5, 13,  7, 22, 21, 25,  3, 26, 33, 11, 16, 31, 24, 27, 17, 41,
       15, 32, 45])

In [13]:
missing_values =df_buses_telangana.isnull().sum()
print("Missing values per column:\n", missing_values)

Missing values per column:
 Bus_name           0
Bus_type           0
Start_time         0
End_time           0
Total_duration     0
Price              0
Seats_Available    0
Ratings            0
Route_link         0
Route_name         0
State              0
dtype: int64

In [117]:
df_buses_telangana=df_buses_telangana.dropna()

In [118]:
missing_values =df_buses_telangana.isnull().sum()
print("Missing values per column:\n", missing_values)

Missing values per column:
 Bus_name           0
Bus_type           0
Start_time         0
End_time           0
Total_duration     0
Price              0
Seats_Available    0
Ratings            0
Route_link         0
Route_name         0
State              0
dtype: int64

In [5]:
df_buses_telangana.to_csv('df_cleaned_telangana.csv', index=False)

In [8]:
df_buses_telangana

,Bus_name,Bus_type,Start_time,End_time,Total_duration,Price,Seats_Available,Ratings,Route_link,Route_name,State
0,Bharathi Tours & Travels,A/C Sleeper (2+1),00:50:00,05:30:00,04:40:00,590,1,4.5,https://www.redbus.in/bus-tickets/khammam-to-h...,Khammam to Hyderabad,Telangana
1,Sri Rama Travels,A/C Seater / Sleeper (2+1),01:30:00,06:45:00,05:15:00,777,2,4.1,https://www.redbus.in/bus-tickets/khammam-to-h...,Khammam to Hyderabad,Telangana
2,BSR Tours And Travels,NON A/C Seater (2+2),23:40:00,06:00:00,06:20:00,610,19,4.5,https://www.redbus.in/bus-tickets/khammam-to-h...,Khammam to Hyderabad,Telangana
3,FRESHBUS,Electric A/C Seater (2+2),05:50:00,12:25:00,06:35:00,550,20,4.7,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Telangana
4,FRESHBUS,Electric A/C Seater (2+2),10:25:00,17:55:00,07:30:00,349,28,4.7,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Telangana
...,...,...,...,...,...,...,...,...,...,...,...
78,Morning Star Travels,Scania AC Multi Axle Sleeper (2+1),03:40:00,09:45:00,06:05:00,500,23,2.7,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Godavarikhani,Telangana
79,Morning Star Travels,Scania AC Multi Axle Sleeper (2+1),17:00:00,21:55:00,04:55:00,1990,19,2.7,https://www.redbus.in/bus-tickets/peddapalli-t...,Peddapalli (Telangana) to Hyderabad,Telangana
80,NueGo,Electric A/C Seater (2+2),05:00:00,10:30:00,05:30:00,332,7,4.8,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Kodad,Telangana
81,NueGo,Electric A/C Seater (2+2),09:30:00,15:05:00,05:35:00,408,22,3.9,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Kodad,Telangana
82,NueGo,Electric A/C Seater/Sleeper (2+1),10:30:00,15:55:00,05:25:00,332,17,3.7,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Kodad,Telangana

**KERALA**

In [16]:
df_buses_kerala

,Bus_name,Bus_type,Start_time,End_time,Total_duration,Price,Seats_Available,Ratings,Route_link,Route_name,State
0,MMK Travels,A/C Seater / Sleeper (2+1),22:30:00,07:30:00,09:00:00,750,16,4.6,https://www.redbus.in/bus-tickets/bangalore-to...,Bangalore to Kozhikode,Kerala
1,DLT BUS,A/C Sleeper (2+1),22:30:00,07:30:00,09:00:00,1099,1,4.2,https://www.redbus.in/bus-tickets/bangalore-to...,Bangalore to Kozhikode,Kerala
2,SAAM BUS,VE A/C Sleeper (2+1),21:45:00,06:45:00,09:00:00,900,10,4.2,https://www.redbus.in/bus-tickets/bangalore-to...,Bangalore to Kozhikode,Kerala
3,AdFAST LINE BUS,A/C Sleeper (2+1),21:15:00,06:15:00,09:00:00,2429,34,4.0,https://www.redbus.in/bus-tickets/bangalore-to...,Bangalore to Kozhikode,Kerala
4,Kyros Connect,Bharat Benz A/C Semi Sleeper (2+2),23:00:00,09:00:00,10:00:00,799,36,4.1,https://www.redbus.in/bus-tickets/bangalore-to...,Bangalore to Kozhikode,Kerala
...,...,...,...,...,...,...,...,...,...,...,...
183,UFO Bus,A/C Sleeper (2+1),23:55:00,04:45:00,04:50:00,990,6,4.1,https://www.redbus.in/bus-tickets/kozhikode-to...,Kozhikode to Aluva,Kerala
184,UFO Bus,A/C Seater Push Back (2+2),00:20:00,04:45:00,04:25:00,699,22,4.1,https://www.redbus.in/bus-tickets/kozhikode-to...,Kozhikode to Aluva,Kerala
185,Blue Bird Travels,A/C Seater Push Back (2+2),01:20:00,06:05:00,04:45:00,549,7,2.3,https://www.redbus.in/bus-tickets/kozhikode-to...,Kozhikode to Aluva,Kerala
186,Blue Bird Travels,A/C Seater Push Back (2+2),21:40:00,01:45:00,04:05:00,799,33,2.3,https://www.redbus.in/bus-tickets/kozhikode-to...,Kozhikode to Aluva,Kerala
187,CGR Tranz,A/C Semi Sleeper (2+2),23:59:00,04:20:00,04:21:00,680,35,0.0,https://www.redbus.in/bus-tickets/kozhikode-to...,Kozhikode to Aluva,Kerala

In [129]:
df_buses_kerala['Bus_name'].unique()

array(['MMK Travels', 'DLT BUS', 'SAAM BUS', 'AdFAST LINE BUS',
       'Kyros Connect', 'NS Transports', 'AdSuraj Holidays',
       'SKS Tours & Travels', 'Madhavi Travels', 'Cochin Bus',
       'A1 Travels', 'Sonia Travels', 'UFO Bus', 'Kalpaka Travels 1',
       'Sona Travels', 'KSRTC (Kerala) - 549', 'P K Travels',
       'BLM Transports', 'Shajees Motors', 'Ubc travels',
       'Holy Maria Travels', 'DA Transports',
       'National travels and logistics', 'Suraj Holidays', 'LIYAS TOURS',
       'Kallada Travels (Suresh Kallada)', 'PSK Travels',
       'Bharathi Travels', 'FAST LINE BUS',
       'CHANCHALAS TOURS AND TRAVELS', 'Blue Bird Travels',
       'Greenline kerala', 'Galaxy Tours', 'EMERALD TRAVELS',
       'Surya Connect', 'Adrin Travels', 'GOLDEN TRAVEL AGENCIES',
       'Ashoka Travel and Logistics', 'Sugama Tourist',
       'SKS Tourist Corporation (REGD)', 'Golden Travels', 'Arya Travels',
       'CGR Tranz'], dtype=object)

In [130]:
df_buses_kerala['Bus_type'].unique()

array(['A/C Seater / Sleeper (2+1)', 'A/C Sleeper (2+1)',
       'VE A/C Sleeper (2+1)', 'Bharat Benz A/C Semi Sleeper (2+2)',
       'Non A/C Seater / Sleeper (2+1)', 'NON AC Seater / Sleeper 2+1',
       'A/C Semi Sleeper (2+2)',
       'Volvo Multi-Axle B9R A/c Semi Sleeper (2+2)',
       'NON A/C Semi Sleeper (2+2)', 'A/C Seater/Sleeper (2+1)',
       'Super Express Non AC Seater Air Bus (2+2)',
       'Volvo Multi-Axle I-Shift B11R Semi Sleeper (2+2)',
       'Bharat Benz A/C Sleeper (2+1)', 'A/C Seater Push Back (2+2)',
       'Bharat Benz A/C Seater /Sleeper (2+1)',
       '2+1 Air Suspension A/C Seater / Sleeper',
       'Volvo A/C Semi Sleeper (2+2)', 'NON A/C Sleeper (2+1)',
       'VE A/C Seater / Sleeper (2+1)', 'NON A/C Seater/ Sleeper (2+1)',
       'NON A/C Semi Sleeper / Sleeper (2+1)',
       'Volvo AC Seater Pushback 2+2'], dtype=object)

In [131]:
df_buses_kerala['Start_time']=df_buses_kerala['Start_time'].str.strip()

print(df_buses_kerala['Start_time'].head())

0    22:30:00
1    22:30:00
2    21:45:00
3    21:15:00
4    23:00:00
Name: Start_time, dtype: object

In [125]:
df_buses_kerala['Start_time']=pd.to_datetime(df_buses_kerala['Start_time'],format='%H:%M',errors='coerce')
df_buses_kerala['Start_time']=df_buses_kerala['Start_time'].dt.strftime('%H:%M:%S')
print(df_buses_kerala[['Start_time']])

    Start_time
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
..         ...
183        NaN
184        NaN
185        NaN
186        NaN
187        NaN

[188 rows x 1 columns]

In [132]:
df_buses_kerala['End_time']=df_buses_kerala['End_time'].str.strip()
print(df_buses_kerala['End_time'].head())

0    07:30:00
1    07:30:00
2    06:45:00
3    06:15:00
4    09:00:00
Name: End_time, dtype: object

In [82]:
df_buses_kerala['End_time']=pd.to_datetime(df_buses_kerala['End_time'], format='%H:%M', errors='coerce')
df_buses_kerala['End_time']=df_buses_kerala['End_time'].dt.strftime('%H:%M:%S')
print(df_buses_kerala['End_time'])

0      07:30:00
1      07:30:00
2      06:45:00
3      06:15:00
4      09:00:00
         ...
183    04:45:00
184    04:45:00
185    06:05:00
186    01:45:00
187    04:20:00
Name: End_time, Length: 188, dtype: object

In [83]:
# Function to convert 'hh h mm m' format to 'hh:mm:ss' format
def convert_to_hms(duration):
    try:
        hours = 0
        minutes = 0
        seconds = 0
        
        # Check for hours and minutes in the string, extract the numeric values
        if 'h' in duration:
            hours = int(duration.split('h')[0].strip())  # Extract hours
            duration = duration.split('h')[1].strip()  # Remove hours part
        
        if 'm' in duration:
            minutes = int(duration.split('m')[0].strip())  # Extract minutes
            duration = duration.split('m')[1].strip()  # Remove minutes part
        
        # If there are remaining characters, assume it's seconds (in case there are seconds)
        if duration:
            seconds = int(duration.strip())  # Remaining part is seconds
        
        # Format to hh:mm:ss
        time_str = f'{hours:02}:{minutes:02}:{seconds:02}'
        return time_str
    except Exception as e:
        return "Invalid Format"

# Apply the conversion function to the 'Total_duration' column in place
df_buses_kerala['Total_duration'] = df_buses_kerala['Total_duration'].apply(convert_to_hms)

# Remove rows with 'Invalid Format' in the 'Total_duration' column without affecting other columns
df_buses_kerala = df_buses_kerala[df_buses_kerala['Total_duration'] != 'Invalid Format']

# Check the DataFrame to ensure it's correct
print(df_buses_kerala)

              Bus_name                            Bus_type Start_time  \
0          MMK Travels          A/C Seater / Sleeper (2+1)   22:30:00
1              DLT BUS                   A/C Sleeper (2+1)   22:30:00
2             SAAM BUS                VE A/C Sleeper (2+1)   21:45:00
3      AdFAST LINE BUS                   A/C Sleeper (2+1)   21:15:00
4        Kyros Connect  Bharat Benz A/C Semi Sleeper (2+2)   23:00:00
..                 ...                                 ...        ...
183            UFO Bus                   A/C Sleeper (2+1)   23:55:00
184            UFO Bus          A/C Seater Push Back (2+2)   00:20:00
185  Blue Bird Travels          A/C Seater Push Back (2+2)   01:20:00
186  Blue Bird Travels          A/C Seater Push Back (2+2)   21:40:00
187          CGR Tranz              A/C Semi Sleeper (2+2)   23:59:00

     End_time Total_duration     Price     Seats_Available   Ratings  \
0    07:30:00       09:00:00   INR 750  16 Seats available  4.6\n550
1    07:30:00       09:00:00  INR 1099    1 Seat available  4.2\n317
2    06:45:00       09:00:00   INR 900  10 Seats available  4.2\n273
3    06:15:00       09:00:00      2429  34 Seats available   4.0\n35
4    09:00:00       10:00:00   INR 799  36 Seats available  4.1\n337
..        ...            ...       ...                 ...       ...
183  04:45:00       04:50:00       990   6 Seats available       4.1
184  04:45:00       04:25:00       699  22 Seats available       4.1
185  06:05:00       04:45:00   INR 549   7 Seats available       2.3
186  01:45:00       04:05:00   INR 799  33 Seats available    2.3\n9
187  04:20:00       04:21:00   INR 680  35 Seats available       New

                                            Route_link              Route_name
0    https://www.redbus.in/bus-tickets/bangalore-to...  Bangalore to Kozhikode
1    https://www.redbus.in/bus-tickets/bangalore-to...  Bangalore to Kozhikode
2    https://www.redbus.in/bus-tickets/bangalore-to...  Bangalore to Kozhikode
3    https://www.redbus.in/bus-tickets/bangalore-to...  Bangalore to Kozhikode
4    https://www.redbus.in/bus-tickets/bangalore-to...  Bangalore to Kozhikode
..                                                 ...                     ...
183  https://www.redbus.in/bus-tickets/kozhikode-to...      Kozhikode to Aluva
184  https://www.redbus.in/bus-tickets/kozhikode-to...      Kozhikode to Aluva
185  https://www.redbus.in/bus-tickets/kozhikode-to...      Kozhikode to Aluva
186  https://www.redbus.in/bus-tickets/kozhikode-to...      Kozhikode to Aluva
187  https://www.redbus.in/bus-tickets/kozhikode-to...      Kozhikode to Aluva

[188 rows x 10 columns]

In [84]:
df_buses_kerala['Total_duration'].unique()

array(['09:00:00', '10:00:00', '08:15:00', '08:45:00', '09:30:00',
       '08:30:00', '08:25:00', '06:00:00', '05:30:00', '03:54:00',
       '04:30:00', '04:59:00', '05:35:00', '06:01:00', '05:31:00',
       '05:10:00', '05:00:00', '07:58:00', '09:45:00', '09:14:00',
       '04:05:00', '03:05:00', '06:15:00', '05:20:00', '05:15:00',
       '04:45:00', '05:45:00', '07:00:00', '06:20:00', '05:40:00',
       '06:05:00', '04:20:00', '05:59:00', '06:45:00', '07:10:00',
       '06:40:00', '03:45:00', '03:00:00', '03:20:00', '02:30:00',
       '03:35:00', '02:00:00', '09:25:00', '08:40:00', '07:30:00',
       '08:20:00', '08:00:00', '06:55:00', '02:45:00', '03:53:00',
       '03:15:00', '23:30:00', '01:55:00', '02:54:00', '02:55:00',
       '06:50:00', '07:15:00', '06:35:00', '07:45:00', '07:25:00',
       '07:50:00', '07:20:00', '07:48:00', '06:31:00', '07:17:00',
       '06:28:00', '07:16:00', '06:24:00', '05:55:00', '06:48:00',
       '04:31:00', '07:19:00', '08:10:00', '07:01:00', '11:10:00',
       '10:59:00', '09:15:00', '11:00:00', '08:55:00', '07:05:00',
       '08:50:00', '04:40:00', '04:35:00', '04:15:00', '04:26:00',
       '04:41:00', '04:25:00', '03:55:00', '04:50:00', '04:21:00'],
      dtype=object)

In [85]:
# Convert 'Price' column to string type before using .str methods
df_buses_kerala["Price"] = df_buses_kerala["Price"].astype(str)

In [86]:
df_buses_kerala["Price"]=df_buses_kerala["Price"].str.replace("INR","")
df_buses_kerala["Price"]=df_buses_kerala["Price"].astype(float)
df_buses_kerala["Price"].fillna(0)

0       750.0
1      1099.0
2       900.0
3      2429.0
4       799.0
        ...
183     990.0
184     699.0
185     549.0
186     799.0
187     680.0
Name: Price, Length: 188, dtype: float64

In [87]:
df_buses_kerala['Price'] = pd.to_numeric(df_buses_kerala['Price'], errors='coerce')
df_buses_kerala['Price'] = df_buses_kerala['Price'].fillna(0)

In [88]:
df_buses_kerala['Price'].unique()

array([ 750., 1099.,  900., 2429.,  799.,  647.,  878.,  730.,  599.,
        667.,  680.,  810.,  850.,  800.,  650.,  832., 1399., 1899.,
       1169., 1300., 1499., 1500., 1149., 1387.,  400.,  600.,  899.,
        700.,  649.,  749.,  549., 1299., 1590., 1999., 1055., 1000.,
        990.,  500., 1494., 1548., 1200., 1400., 1349.,  999., 1100.,
        949.,  880.,  879.,  739., 1270., 1199., 1143., 1350., 1250.,
       1155.,  950., 1202., 1549.,  795.,  699.])

In [89]:
# Print rows where 'Price' is NaN
print(df_buses_kerala[df_buses_kerala['Price'].isnull()])

# Drop rows with NaN in 'Price'
df_buses_kerala.dropna(subset=['Price'], inplace=True)

Empty DataFrame
Columns: [Bus_name, Bus_type, Start_time, End_time, Total_duration, Price, Seats_Available, Ratings, Route_link, Route_name]
Index: []

In [90]:
import numpy as np
import re

# Function to clean the Ratings column
def clean_rating(value):
    # If the value is one of the invalid ones, return NaN
    if str(value).lower() in ['nan', 'new', ' ', 'none']:
        return np.nan
    # Attempt to extract a numeric value from the string
    match = re.match(r'(\d+\.\d+)', str(value))
    if match:
        return float(match.group(1))
    # If no match is found, return NaN
    return np.nan

# Clean the Ratings column
df_buses_kerala['Ratings'] = df_buses_kerala['Ratings'].apply(clean_rating)

# Show the cleaned data
print(df_buses_kerala[['Ratings']].head())

   Ratings
0      4.6
1      4.2
2      4.2
3      4.0
4      4.1

In [133]:
df_buses_kerala['Ratings'].unique()

array([4.6, 4.2, 4. , 4.1, 3.4, 3.9, 0. , 4.9, 4.5, 3.1, 4.8, 4.4, 2.5,
       4.3, 3.8, 3.3, 3.6, 3.7, 3.5, 2.2, 3. , 3.2, 2.4, 2.6, 2.8, 2.9,
       1.6, 2. , 2.7, 2.3])

In [92]:
df_buses_kerala['Ratings'] = df_buses_kerala['Ratings'].fillna(0)  # Replace NaN with 0

In [93]:
df_buses_kerala = df_buses_kerala.dropna(subset=['Ratings'])

In [94]:
df_buses_kerala['Ratings'].unique()

array([4.6, 4.2, 4. , 4.1, 3.4, 3.9, 0. , 4.9, 4.5, 3.1, 4.8, 4.4, 2.5,
       4.3, 3.8, 3.3, 3.6, 3.7, 3.5, 2.2, 3. , 3.2, 2.4, 2.6, 2.8, 2.9,
       1.6, 2. , 2.7, 2.3])

In [134]:
df_buses_kerala['Seats_Available'].unique()

array([16,  1, 10, 34, 36, 25, 15, 19, 17, 24,  4,  6, 13, 14, 12, 37, 26,
        7,  5,  9, 21,  3, 18, 32,  2,  8, 29, 20, 23, 35, 11, 28, 33, 30,
       22, 31])

In [96]:
df_buses_kerala['Seats_Available']=df_buses_kerala['Seats_Available'].fillna("not available")

In [97]:
import re

# Apply a transformation to the 'Seats_Available' column to extract the first numeric value from the string.
# If a numeric value is found, it converts it to an integer. If no numeric value is found, it assigns 0.
df_buses_kerala['Seats_Available'] = df_buses_kerala['Seats_Available'].apply(
    lambda x: int(re.findall(r'\d+', x)[0]) if re.findall(r'\d+', x) else 0
)

# Print the DataFrame to check the updated 'Seats_Available' values
print(df_buses_kerala)

              Bus_name                            Bus_type Start_time  \
0          MMK Travels          A/C Seater / Sleeper (2+1)   22:30:00
1              DLT BUS                   A/C Sleeper (2+1)   22:30:00
2             SAAM BUS                VE A/C Sleeper (2+1)   21:45:00
3      AdFAST LINE BUS                   A/C Sleeper (2+1)   21:15:00
4        Kyros Connect  Bharat Benz A/C Semi Sleeper (2+2)   23:00:00
..                 ...                                 ...        ...
183            UFO Bus                   A/C Sleeper (2+1)   23:55:00
184            UFO Bus          A/C Seater Push Back (2+2)   00:20:00
185  Blue Bird Travels          A/C Seater Push Back (2+2)   01:20:00
186  Blue Bird Travels          A/C Seater Push Back (2+2)   21:40:00
187          CGR Tranz              A/C Semi Sleeper (2+2)   23:59:00

     End_time Total_duration   Price  Seats_Available  Ratings  \
0    07:30:00       09:00:00   750.0               16      4.6
1    07:30:00       09:00:00  1099.0                1      4.2
2    06:45:00       09:00:00   900.0               10      4.2
3    06:15:00       09:00:00  2429.0               34      4.0
4    09:00:00       10:00:00   799.0               36      4.1
..        ...            ...     ...              ...      ...
183  04:45:00       04:50:00   990.0                6      4.1
184  04:45:00       04:25:00   699.0               22      4.1
185  06:05:00       04:45:00   549.0                7      2.3
186  01:45:00       04:05:00   799.0               33      2.3
187  04:20:00       04:21:00   680.0               35      0.0

                                            Route_link              Route_name
0    https://www.redbus.in/bus-tickets/bangalore-to...  Bangalore to Kozhikode
1    https://www.redbus.in/bus-tickets/bangalore-to...  Bangalore to Kozhikode
2    https://www.redbus.in/bus-tickets/bangalore-to...  Bangalore to Kozhikode
3    https://www.redbus.in/bus-tickets/bangalore-to...  Bangalore to Kozhikode
4    https://www.redbus.in/bus-tickets/bangalore-to...  Bangalore to Kozhikode
..                                                 ...                     ...
183  https://www.redbus.in/bus-tickets/kozhikode-to...      Kozhikode to Aluva
184  https://www.redbus.in/bus-tickets/kozhikode-to...      Kozhikode to Aluva
185  https://www.redbus.in/bus-tickets/kozhikode-to...      Kozhikode to Aluva
186  https://www.redbus.in/bus-tickets/kozhikode-to...      Kozhikode to Aluva
187  https://www.redbus.in/bus-tickets/kozhikode-to...      Kozhikode to Aluva

[188 rows x 10 columns]

In [98]:
df_buses_kerala['Seats_Available'].unique()

array([16,  1, 10, 34, 36, 25, 15, 19, 17, 24,  4,  6, 13, 14, 12, 37, 26,
        7,  5,  9, 21,  3, 18, 32,  2,  8, 29, 20, 23, 35, 11, 28, 33, 30,
       22, 31])

In [17]:
missing_values=df_buses_kerala.isnull().sum()
missing_values

Bus_name           0
Bus_type           0
Start_time         0
End_time           0
Total_duration     0
Price              0
Seats_Available    0
Ratings            0
Route_link         0
Route_name         0
State              0
dtype: int64

In [6]:
df_buses_kerala.to_csv('df_cleaned_kerala.csv', index=False)

In [10]:
df_buses_kerala

,Bus_name,Bus_type,Start_time,End_time,Total_duration,Price,Seats_Available,Ratings,Route_link,Route_name,State
0,MMK Travels,A/C Seater / Sleeper (2+1),22:30:00,07:30:00,09:00:00,750,16,4.6,https://www.redbus.in/bus-tickets/bangalore-to...,Bangalore to Kozhikode,Kerala
1,DLT BUS,A/C Sleeper (2+1),22:30:00,07:30:00,09:00:00,1099,1,4.2,https://www.redbus.in/bus-tickets/bangalore-to...,Bangalore to Kozhikode,Kerala
2,SAAM BUS,VE A/C Sleeper (2+1),21:45:00,06:45:00,09:00:00,900,10,4.2,https://www.redbus.in/bus-tickets/bangalore-to...,Bangalore to Kozhikode,Kerala
3,AdFAST LINE BUS,A/C Sleeper (2+1),21:15:00,06:15:00,09:00:00,2429,34,4.0,https://www.redbus.in/bus-tickets/bangalore-to...,Bangalore to Kozhikode,Kerala
4,Kyros Connect,Bharat Benz A/C Semi Sleeper (2+2),23:00:00,09:00:00,10:00:00,799,36,4.1,https://www.redbus.in/bus-tickets/bangalore-to...,Bangalore to Kozhikode,Kerala
...,...,...,...,...,...,...,...,...,...,...,...
183,UFO Bus,A/C Sleeper (2+1),23:55:00,04:45:00,04:50:00,990,6,4.1,https://www.redbus.in/bus-tickets/kozhikode-to...,Kozhikode to Aluva,Kerala
184,UFO Bus,A/C Seater Push Back (2+2),00:20:00,04:45:00,04:25:00,699,22,4.1,https://www.redbus.in/bus-tickets/kozhikode-to...,Kozhikode to Aluva,Kerala
185,Blue Bird Travels,A/C Seater Push Back (2+2),01:20:00,06:05:00,04:45:00,549,7,2.3,https://www.redbus.in/bus-tickets/kozhikode-to...,Kozhikode to Aluva,Kerala
186,Blue Bird Travels,A/C Seater Push Back (2+2),21:40:00,01:45:00,04:05:00,799,33,2.3,https://www.redbus.in/bus-tickets/kozhikode-to...,Kozhikode to Aluva,Kerala
187,CGR Tranz,A/C Semi Sleeper (2+2),23:59:00,04:20:00,04:21:00,680,35,0.0,https://www.redbus.in/bus-tickets/kozhikode-to...,Kozhikode to Aluva,Kerala

**ASSAM**

In [20]:
df_buses_AS

,Bus_name,Bus_type,Start_time,End_time,Total_duration,Price,Seats_Available,Ratings,Route_link,Route_name,State
0,BLUE HILL TRAVELS INDIA LIMITED,NON A/C Seater Semi Sleeper (2+1),21:15:00,03:00:00,05:45:00,500.00,7,3.4,https://www.redbus.in/bus-tickets/tezpur-to-gu...,Tezpur to Guwahati,Assam
1,DESTINY TRAVELS,NON A/C Seater (2+1),23:00:00,04:15:00,05:15:00,488.78,21,2.4,https://www.redbus.in/bus-tickets/tezpur-to-gu...,Tezpur to Guwahati,Assam
2,Shopuris Travels,Non AC Seater (2+1),21:15:00,03:00:00,05:45:00,700.00,6,0.0,https://www.redbus.in/bus-tickets/tezpur-to-gu...,Tezpur to Guwahati,Assam
3,Yatra Travels,NON AC Seater/ Sleeper (2+1),19:15:00,23:00:00,03:45:00,450.00,19,3.2,https://www.redbus.in/bus-tickets/guwahati-to-...,Guwahati to Tezpur,Assam
4,Yatra Travels,NON A/C Seater/ Sleeper (2+1),19:30:00,00:30:00,05:00:00,425.00,25,3.4,https://www.redbus.in/bus-tickets/guwahati-to-...,Guwahati to Tezpur,Assam
...,...,...,...,...,...,...,...,...,...,...,...
61,DESTINY TRAVELS,NON A/C Seater (2+1),23:45:00,04:15:00,04:30:00,451.00,18,1.4,https://www.redbus.in/bus-tickets/tezpur-to-no...,Tezpur to North Lakhimpur,Assam
62,Yatra Travels,A/C Seater / Sleeper (2+1),19:30:00,03:00:00,07:30:00,675.00,17,4.1,https://www.redbus.in/bus-tickets/north-lakhim...,North Lakhimpur to Nagaon (Assam),Assam
63,MAHARATHI TRANSPORT,NON A/C Semi Sleeper (2+1),19:30:00,03:00:00,07:30:00,495.00,10,3.3,https://www.redbus.in/bus-tickets/north-lakhim...,North Lakhimpur to Nagaon (Assam),Assam
64,Yatra Travels,NON AC Seater/ Sleeper (2+1),19:45:00,05:00:00,09:15:00,540.00,11,3.3,https://www.redbus.in/bus-tickets/north-lakhim...,North Lakhimpur to Nagaon (Assam),Assam
65,Maharathi Travels(UNDER ASTC),NON A/C Seater (2+1),20:20:00,03:30:00,07:10:00,475.00,15,3.8,https://www.redbus.in/bus-tickets/north-lakhim...,North Lakhimpur to Nagaon (Assam),Assam

In [139]:
df_buses_AS['Bus_name'].unique()

array(['BLUE HILL TRAVELS INDIA LIMITED', 'DESTINY TRAVELS',
       'Shopuris Travels', 'Yatra Travels',
       'Nishigandha(Divya Tours & Travels)', 'MAA MONOSHA TRAVELS',
       'Yatra', 'Aniruddha Travels', 'SANJEEBANI TRAVELS',
       'Puja Transport', 'J.S. Travels', 'Baikuntha Transport Service',
       'Purple Wings Coaches', 'Trishul Transport Service',
       'Air Bus Travels', 'RAYAN TRAVELS', 'PARIJAT TRAVELS(UNDER ASTC)',
       'Laxmi Travels', 'KIRAN TRAVELS', 'Pranjit Travels (Under ASTC)',
       'BAIKUNTHA TRAVELS (UNDER ASTC)',
       'TRINAYAN TRANSPORT (Under ASTC)', 'MAHARATHI TRANSPORT',
       'Maharathi Travels(UNDER ASTC)'], dtype=object)

In [104]:
df_buses_AS = df_buses_AS.dropna(subset=['Bus_name'])

In [140]:
df_buses_AS['Bus_name'].unique()

array(['BLUE HILL TRAVELS INDIA LIMITED', 'DESTINY TRAVELS',
       'Shopuris Travels', 'Yatra Travels',
       'Nishigandha(Divya Tours & Travels)', 'MAA MONOSHA TRAVELS',
       'Yatra', 'Aniruddha Travels', 'SANJEEBANI TRAVELS',
       'Puja Transport', 'J.S. Travels', 'Baikuntha Transport Service',
       'Purple Wings Coaches', 'Trishul Transport Service',
       'Air Bus Travels', 'RAYAN TRAVELS', 'PARIJAT TRAVELS(UNDER ASTC)',
       'Laxmi Travels', 'KIRAN TRAVELS', 'Pranjit Travels (Under ASTC)',
       'BAIKUNTHA TRAVELS (UNDER ASTC)',
       'TRINAYAN TRANSPORT (Under ASTC)', 'MAHARATHI TRANSPORT',
       'Maharathi Travels(UNDER ASTC)'], dtype=object)

In [106]:
df_buses_AS['Bus_type'].unique()

array(['NON A/C Seater Semi Sleeper (2+1)', 'NON A/C Seater (2+1)',
       'Non AC Seater (2+1)', 'NON AC Seater/ Sleeper (2+1)',
       'NON A/C Seater/ Sleeper (2+1)', 'A/C Seater / Sleeper (2+1)',
       'A/C Seater (2+1)', 'Non AC Seater (2+2)',
       'Non A/C Seater / Sleeper (2+1)', 'NON AC Seater / Sleeper 2+1',
       'Bharat Benz A/C Seater /Sleeper (2+1)', nan,
       'Bharat Benz A/C Seater (2+1)', 'A/C Seater/Sleeper (2+1)',
       'NON A/C Semi Sleeper (2+1)'], dtype=object)

In [107]:
df_buses_AS = df_buses_AS.dropna(subset=['Bus_type'])

In [108]:
df_buses_AS['Bus_type'].unique()

array(['NON A/C Seater Semi Sleeper (2+1)', 'NON A/C Seater (2+1)',
       'Non AC Seater (2+1)', 'NON AC Seater/ Sleeper (2+1)',
       'NON A/C Seater/ Sleeper (2+1)', 'A/C Seater / Sleeper (2+1)',
       'A/C Seater (2+1)', 'Non AC Seater (2+2)',
       'Non A/C Seater / Sleeper (2+1)', 'NON AC Seater / Sleeper 2+1',
       'Bharat Benz A/C Seater /Sleeper (2+1)',
       'Bharat Benz A/C Seater (2+1)', 'A/C Seater/Sleeper (2+1)',
       'NON A/C Semi Sleeper (2+1)'], dtype=object)

In [141]:
# Clean the 'Start_time' column by removing extra spaces
df_buses_AS['Start_time'] = df_buses_AS['Start_time'].str.strip()

# Check if the cleaning helped
print(df_buses_AS['Start_time'].head())

0    21:15:00
1    23:00:00
2    21:15:00
3    19:15:00
4    19:30:00
Name: Start_time, dtype: object

In [110]:
import pandas as pd



# Step 1: Convert Start_time to datetime format (with date included)
df_buses_AS['Start_time'] = pd.to_datetime(df_buses_AS['Start_time'], format='%H:%M', errors='coerce')

# Step 2: Extract only the time and convert to 'HHMMSS' format
df_buses_AS['Start_time'] = df_buses_AS['Start_time'].dt.strftime('%H:%M:%S')

# Display the updated DataFrame with 'Start_time' in 'HHMMSS' format
print(df_buses_AS[['Start_time']])

   Start_time
0    21:15:00
1    23:00:00
2    22:15:00
3    21:15:00
4    19:15:00
..        ...
68   23:45:00
69   19:30:00
70   19:30:00
71   19:45:00
72   20:20:00

[67 rows x 1 columns]

In [142]:
# Clean the 'End_time' column by removing extra spaces
df_buses_AS['End_time'] = df_buses_AS['End_time'].str.strip()

# Check if the cleaning helped
print(df_buses_AS['End_time'].head())

0    03:00:00
1    04:15:00
2    03:00:00
3    23:00:00
4    00:30:00
Name: End_time, dtype: object

In [112]:

df_buses_AS['End_time'] = pd.to_datetime(df_buses_AS['End_time'], format='%H:%M', errors='coerce')
df_buses_AS['End_time'] =df_buses_AS['End_time'].dt.strftime('%H:%M:%S')
print(df_buses_AS[['End_time']])

    End_time
0   03:00:00
1   04:15:00
2   03:45:00
3   03:00:00
4   23:00:00
..       ...
68  04:15:00
69  03:00:00
70  03:00:00
71  05:00:00
72  03:30:00

[67 rows x 1 columns]

In [113]:
# Function to convert 'hh h mm m' format to 'hh:mm:ss' format
def convert_to_hms(duration):
    try:
        hours = 0
        minutes = 0
        seconds = 0
        
        # Check for hours and minutes in the string, extract the numeric values
        if 'h' in duration:
            hours = int(duration.split('h')[0].strip())  # Extract hours
            duration = duration.split('h')[1].strip()  # Remove hours part
        
        if 'm' in duration:
            minutes = int(duration.split('m')[0].strip())  # Extract minutes
            duration = duration.split('m')[1].strip()  # Remove minutes part
        
        # If there are remaining characters, assume it's seconds (in case there are seconds)
        if duration:
            seconds = int(duration.strip())  # Remaining part is seconds
        
        # Format to hh:mm:ss
        time_str = f'{hours:02}:{minutes:02}:{seconds:02}'
        return time_str
    except Exception as e:
        return "Invalid Format"

# Apply the conversion function to the 'Total_duration' column in place
df_buses_AS['Total_duration'] = df_buses_AS['Total_duration'].apply(convert_to_hms)

# Remove rows with 'Invalid Format' in the 'Total_duration' column without affecting other columns
df_buses_AS = df_buses_AS[df_buses_AS['Total_duration'] != 'Invalid Format']

# Check the DataFrame to ensure it's correct
print(df_buses_AS)

                           Bus_name                           Bus_type  \
0   BLUE HILL TRAVELS INDIA LIMITED  NON A/C Seater Semi Sleeper (2+1)
1                   DESTINY TRAVELS               NON A/C Seater (2+1)
3                  Shopuris Travels                Non AC Seater (2+1)
4                     Yatra Travels       NON AC Seater/ Sleeper (2+1)
5                     Yatra Travels      NON A/C Seater/ Sleeper (2+1)
..                              ...                                ...
68                  DESTINY TRAVELS               NON A/C Seater (2+1)
69                    Yatra Travels         A/C Seater / Sleeper (2+1)
70              MAHARATHI TRANSPORT         NON A/C Semi Sleeper (2+1)
71                    Yatra Travels       NON AC Seater/ Sleeper (2+1)
72    Maharathi Travels(UNDER ASTC)               NON A/C Seater (2+1)

   Start_time  End_time Total_duration       Price     Seats_Available  \
0    21:15:00  03:00:00       05:45:00     INR 500   7 Seats available
1    23:00:00  04:15:00       05:15:00  INR 488.78  21 Seats available
3    21:15:00  03:00:00       05:45:00     INR 700   6 Seats available
4    19:15:00  23:00:00       03:45:00         450  19 Seats available
5    19:30:00  00:30:00       05:00:00         425  25 Seats available
..        ...       ...            ...         ...                 ...
68   23:45:00  04:15:00       04:30:00         451  18 Seats available
69   19:30:00  03:00:00       07:30:00         675  17 Seats available
70   19:30:00  03:00:00       07:30:00         495  10 Seats available
71   19:45:00  05:00:00       09:15:00         540  11 Seats available
72   20:20:00  03:30:00       07:10:00         475  15 Seats available

    Ratings                                         Route_link  \
0   3.4\n91  https://www.redbus.in/bus-tickets/tezpur-to-gu...
1       2.4  https://www.redbus.in/bus-tickets/tezpur-to-gu...
3       New  https://www.redbus.in/bus-tickets/tezpur-to-gu...
4   3.2\n46  https://www.redbus.in/bus-tickets/guwahati-to-...
5       3.4  https://www.redbus.in/bus-tickets/guwahati-to-...
..      ...                                                ...
68      1.4  https://www.redbus.in/bus-tickets/tezpur-to-no...
69      4.1  https://www.redbus.in/bus-tickets/north-lakhim...
70      3.3  https://www.redbus.in/bus-tickets/north-lakhim...
71  3.3\n15  https://www.redbus.in/bus-tickets/north-lakhim...
72   3.8\n5  https://www.redbus.in/bus-tickets/north-lakhim...

                           Route_name
0                  Tezpur to Guwahati
1                  Tezpur to Guwahati
3                  Tezpur to Guwahati
4                  Guwahati to Tezpur
5                  Guwahati to Tezpur
..                                ...
68          Tezpur to North Lakhimpur
69  North Lakhimpur to Nagaon (Assam)
70  North Lakhimpur to Nagaon (Assam)
71  North Lakhimpur to Nagaon (Assam)
72  North Lakhimpur to Nagaon (Assam)

[66 rows x 10 columns]

In [143]:
df_buses_AS

,Bus_name,Bus_type,Start_time,End_time,Total_duration,Price,Seats_Available,Ratings,Route_link,Route_name,State
0,BLUE HILL TRAVELS INDIA LIMITED,NON A/C Seater Semi Sleeper (2+1),21:15:00,03:00:00,05:45:00,500.00,7,3.4,https://www.redbus.in/bus-tickets/tezpur-to-gu...,Tezpur to Guwahati,Assam
1,DESTINY TRAVELS,NON A/C Seater (2+1),23:00:00,04:15:00,05:15:00,488.78,21,2.4,https://www.redbus.in/bus-tickets/tezpur-to-gu...,Tezpur to Guwahati,Assam
2,Shopuris Travels,Non AC Seater (2+1),21:15:00,03:00:00,05:45:00,700.00,6,0.0,https://www.redbus.in/bus-tickets/tezpur-to-gu...,Tezpur to Guwahati,Assam
3,Yatra Travels,NON AC Seater/ Sleeper (2+1),19:15:00,23:00:00,03:45:00,450.00,19,3.2,https://www.redbus.in/bus-tickets/guwahati-to-...,Guwahati to Tezpur,Assam
4,Yatra Travels,NON A/C Seater/ Sleeper (2+1),19:30:00,00:30:00,05:00:00,425.00,25,3.4,https://www.redbus.in/bus-tickets/guwahati-to-...,Guwahati to Tezpur,Assam
...,...,...,...,...,...,...,...,...,...,...,...
61,DESTINY TRAVELS,NON A/C Seater (2+1),23:45:00,04:15:00,04:30:00,451.00,18,1.4,https://www.redbus.in/bus-tickets/tezpur-to-no...,Tezpur to North Lakhimpur,Assam
62,Yatra Travels,A/C Seater / Sleeper (2+1),19:30:00,03:00:00,07:30:00,675.00,17,4.1,https://www.redbus.in/bus-tickets/north-lakhim...,North Lakhimpur to Nagaon (Assam),Assam
63,MAHARATHI TRANSPORT,NON A/C Semi Sleeper (2+1),19:30:00,03:00:00,07:30:00,495.00,10,3.3,https://www.redbus.in/bus-tickets/north-lakhim...,North Lakhimpur to Nagaon (Assam),Assam
64,Yatra Travels,NON AC Seater/ Sleeper (2+1),19:45:00,05:00:00,09:15:00,540.00,11,3.3,https://www.redbus.in/bus-tickets/north-lakhim...,North Lakhimpur to Nagaon (Assam),Assam
65,Maharathi Travels(UNDER ASTC),NON A/C Seater (2+1),20:20:00,03:30:00,07:10:00,475.00,15,3.8,https://www.redbus.in/bus-tickets/north-lakhim...,North Lakhimpur to Nagaon (Assam),Assam

In [144]:
df_buses_AS['Total_duration'].unique()

array(['05:45:00', '05:15:00', '03:45:00', '05:00:00', '05:30:00',
       '04:30:00', '02:35:00', '07:30:00', '07:15:00', '08:30:00',
       '09:00:00', '04:20:00', '03:40:00', '06:00:00', '06:45:00',
       '04:45:00', '05:40:00', '06:25:00', '06:40:00', '07:00:00',
       '06:30:00', '08:15:00', '08:45:00', '04:15:00', '07:45:00',
       '05:20:00', '03:55:00', '09:20:00', '07:25:00', '06:55:00',
       '03:15:00', '08:55:00', '09:15:00', '10:45:00', '10:05:00',
       '09:30:00', '10:00:00', '07:10:00'], dtype=object)

In [116]:
# Convert 'Price' column to string type before using .str methods
df_buses_AS["Price"] = df_buses_AS["Price"].astype(str)

In [117]:
#convert prices to numeric
df_buses_AS["Price"]=df_buses_AS["Price"].str.replace("INR","")
df_buses_AS["Price"]=df_buses_AS["Price"].astype(float)
df_buses_AS["Price"].fillna(0)

0     500.00
1     488.78
3     700.00
4     450.00
5     425.00
       ...
68    451.00
69    675.00
70    495.00
71    540.00
72    475.00
Name: Price, Length: 66, dtype: float64

In [118]:
# Convert price column to numeric, setting errors='coerce' to replace invalid values with NaN
df_buses_AS['Price'] = pd.to_numeric(df_buses_AS['Price'], errors='coerce')

# Replace NaN (missing values) in the price column with a default value or None (for NULL in MySQL)
df_buses_AS['Price'] = df_buses_AS['Price'].fillna(0)  # Replace NaN with 0, or use None for NULL

In [145]:
df_buses_AS['Price'].unique()

array([500.  , 488.78, 700.  , 450.  , 425.  , 375.  , 550.  , 350.  ,
       570.  , 600.  , 585.  , 540.  , 400.  , 495.  , 630.  , 510.  ,
       620.  , 535.  , 439.  , 415.  , 595.  , 750.  , 675.  , 465.  ,
       451.  , 475.  ])

In [120]:
# Print rows where 'Price' is NaN
print(df_buses_AS[df_buses_AS['Price'].isnull()])

# Drop rows with NaN in 'Price'
df_buses_AS.dropna(subset=['Price'], inplace=True)

Empty DataFrame
Columns: [Bus_name, Bus_type, Start_time, End_time, Total_duration, Price, Seats_Available, Ratings, Route_link, Route_name]
Index: []

In [121]:
import numpy as np
import re

# Function to clean the Ratings column
def clean_rating(value):
    # If the value is one of the invalid ones, return NaN
    if str(value).lower() in ['nan', 'new', ' ', 'none']:
        return np.nan
    # Attempt to extract a numeric value from the string
    match = re.match(r'(\d+\.\d+)', str(value))
    if match:
        return float(match.group(1))
    # If no match is found, return NaN
    return np.nan

# Clean the Ratings column
df_buses_AS['Ratings'] = df_buses_AS['Ratings'].apply(clean_rating)

# Show the cleaned data
print(df_buses_AS[['Ratings']].head())

   Ratings
0      3.4
1      2.4
3      NaN
4      3.2
5      3.4

In [122]:
df_buses_AS['Ratings'] = df_buses_AS['Ratings'].fillna(0)

In [123]:
df_buses_AS = df_buses_AS.dropna(subset=['Ratings'])

In [146]:
df_buses_AS['Ratings'].unique()

array([3.4, 2.4, 0. , 3.2, 4.6, 3.3, 2.3, 3.6, 4.2, 2.9, 2.5, 3.1, 3.9,
       2.6, 3.7, 4.8, 3.8, 4.3, 1.9, 2.2, 4.4, 4.5, 4.1, 3.5, 2.7, 1.4])

In [147]:
df_buses_AS['Seats_Available'].unique()

array([ 7, 21,  6, 19, 25, 29, 23, 11, 34, 40,  9,  5, 14, 13,  4, 36, 20,
       10,  2, 32, 31, 16, 17, 35, 37,  8, 18, 15])

In [126]:
df_buses_AS['Seats_Available']=df_buses_AS['Seats_Available'].fillna("not available")

In [127]:
import re

# Apply a transformation to the 'Seats_Available' column to extract the first numeric value from the string.
# If a numeric value is found, it converts it to an integer. If no numeric value is found, it assigns 0.
df_buses_AS['Seats_Available'] = df_buses_AS['Seats_Available'].apply(
    lambda x: int(re.findall(r'\d+', x)[0]) if re.findall(r'\d+', x) else 0
)

# Print the DataFrame to check the updated 'Seats_Available' values
print(df_buses_AS)

                           Bus_name                           Bus_type  \
0   BLUE HILL TRAVELS INDIA LIMITED  NON A/C Seater Semi Sleeper (2+1)
1                   DESTINY TRAVELS               NON A/C Seater (2+1)
3                  Shopuris Travels                Non AC Seater (2+1)
4                     Yatra Travels       NON AC Seater/ Sleeper (2+1)
5                     Yatra Travels      NON A/C Seater/ Sleeper (2+1)
..                              ...                                ...
68                  DESTINY TRAVELS               NON A/C Seater (2+1)
69                    Yatra Travels         A/C Seater / Sleeper (2+1)
70              MAHARATHI TRANSPORT         NON A/C Semi Sleeper (2+1)
71                    Yatra Travels       NON AC Seater/ Sleeper (2+1)
72    Maharathi Travels(UNDER ASTC)               NON A/C Seater (2+1)

   Start_time  End_time Total_duration   Price  Seats_Available  Ratings  \
0    21:15:00  03:00:00       05:45:00  500.00                7      3.4
1    23:00:00  04:15:00       05:15:00  488.78               21      2.4
3    21:15:00  03:00:00       05:45:00  700.00                6      0.0
4    19:15:00  23:00:00       03:45:00  450.00               19      3.2
5    19:30:00  00:30:00       05:00:00  425.00               25      3.4
..        ...       ...            ...     ...              ...      ...
68   23:45:00  04:15:00       04:30:00  451.00               18      1.4
69   19:30:00  03:00:00       07:30:00  675.00               17      4.1
70   19:30:00  03:00:00       07:30:00  495.00               10      3.3
71   19:45:00  05:00:00       09:15:00  540.00               11      3.3
72   20:20:00  03:30:00       07:10:00  475.00               15      3.8

                                           Route_link  \
0   https://www.redbus.in/bus-tickets/tezpur-to-gu...
1   https://www.redbus.in/bus-tickets/tezpur-to-gu...
3   https://www.redbus.in/bus-tickets/tezpur-to-gu...
4   https://www.redbus.in/bus-tickets/guwahati-to-...
5   https://www.redbus.in/bus-tickets/guwahati-to-...
..                                                ...
68  https://www.redbus.in/bus-tickets/tezpur-to-no...
69  https://www.redbus.in/bus-tickets/north-lakhim...
70  https://www.redbus.in/bus-tickets/north-lakhim...
71  https://www.redbus.in/bus-tickets/north-lakhim...
72  https://www.redbus.in/bus-tickets/north-lakhim...

                           Route_name
0                  Tezpur to Guwahati
1                  Tezpur to Guwahati
3                  Tezpur to Guwahati
4                  Guwahati to Tezpur
5                  Guwahati to Tezpur
..                                ...
68          Tezpur to North Lakhimpur
69  North Lakhimpur to Nagaon (Assam)
70  North Lakhimpur to Nagaon (Assam)
71  North Lakhimpur to Nagaon (Assam)
72  North Lakhimpur to Nagaon (Assam)

[66 rows x 10 columns]

In [128]:
df_buses_AS['Seats_Available'].unique()

array([ 7, 21,  6, 19, 25, 29, 23, 11, 34, 40,  9,  5, 14, 13,  4, 36, 20,
       10,  2, 32, 31, 16, 17, 35, 37,  8, 18, 15])

In [21]:
missing_values=df_buses_AS.isnull().sum()
missing_values

Bus_name           0
Bus_type           0
Start_time         0
End_time           0
Total_duration     0
Price              0
Seats_Available    0
Ratings            0
Route_link         0
Route_name         0
State              0
dtype: int64

In [7]:
df_buses_AS.to_csv('df_cleaned_AS.csv', index=False)

In [12]:
df_buses_AS

,Bus_name,Bus_type,Start_time,End_time,Total_duration,Price,Seats_Available,Ratings,Route_link,Route_name,State
0,BLUE HILL TRAVELS INDIA LIMITED,NON A/C Seater Semi Sleeper (2+1),21:15:00,03:00:00,05:45:00,500.00,7,3.4,https://www.redbus.in/bus-tickets/tezpur-to-gu...,Tezpur to Guwahati,Assam
1,DESTINY TRAVELS,NON A/C Seater (2+1),23:00:00,04:15:00,05:15:00,488.78,21,2.4,https://www.redbus.in/bus-tickets/tezpur-to-gu...,Tezpur to Guwahati,Assam
2,Shopuris Travels,Non AC Seater (2+1),21:15:00,03:00:00,05:45:00,700.00,6,0.0,https://www.redbus.in/bus-tickets/tezpur-to-gu...,Tezpur to Guwahati,Assam
3,Yatra Travels,NON AC Seater/ Sleeper (2+1),19:15:00,23:00:00,03:45:00,450.00,19,3.2,https://www.redbus.in/bus-tickets/guwahati-to-...,Guwahati to Tezpur,Assam
4,Yatra Travels,NON A/C Seater/ Sleeper (2+1),19:30:00,00:30:00,05:00:00,425.00,25,3.4,https://www.redbus.in/bus-tickets/guwahati-to-...,Guwahati to Tezpur,Assam
...,...,...,...,...,...,...,...,...,...,...,...
61,DESTINY TRAVELS,NON A/C Seater (2+1),23:45:00,04:15:00,04:30:00,451.00,18,1.4,https://www.redbus.in/bus-tickets/tezpur-to-no...,Tezpur to North Lakhimpur,Assam
62,Yatra Travels,A/C Seater / Sleeper (2+1),19:30:00,03:00:00,07:30:00,675.00,17,4.1,https://www.redbus.in/bus-tickets/north-lakhim...,North Lakhimpur to Nagaon (Assam),Assam
63,MAHARATHI TRANSPORT,NON A/C Semi Sleeper (2+1),19:30:00,03:00:00,07:30:00,495.00,10,3.3,https://www.redbus.in/bus-tickets/north-lakhim...,North Lakhimpur to Nagaon (Assam),Assam
64,Yatra Travels,NON AC Seater/ Sleeper (2+1),19:45:00,05:00:00,09:15:00,540.00,11,3.3,https://www.redbus.in/bus-tickets/north-lakhim...,North Lakhimpur to Nagaon (Assam),Assam
65,Maharathi Travels(UNDER ASTC),NON A/C Seater (2+1),20:20:00,03:30:00,07:10:00,475.00,15,3.8,https://www.redbus.in/bus-tickets/north-lakhim...,North Lakhimpur to Nagaon (Assam),Assam

**BENGAL**

In [24]:
df_buses_bengal

,Bus_name,Bus_type,Start_time,End_time,Total_duration,Price,Seats_Available,Ratings,Route_link,Route_name,State
0,WBTC (CTC) Habra - Barasat - Durgapur - Asanso...,Non AC Seater (2+3),14:25:00,17:00:00,02:35:00,135,16,4.4,https://www.redbus.in/bus-tickets/durgapur-to-...,Durgapur (West Bengal) to Kolkata,South bengal
1,Shyamoli Paribahan Pvt Ltd,Volvo A/C Seater (2+2),15:30:00,19:20:00,03:50:00,650,13,4.2,https://www.redbus.in/bus-tickets/durgapur-to-...,Durgapur (West Bengal) to Kolkata,South bengal
2,Greenline,Volvo A/C Seater (2+2),16:00:00,19:50:00,03:50:00,486,1,4.2,https://www.redbus.in/bus-tickets/durgapur-to-...,Durgapur (West Bengal) to Kolkata,South bengal
3,SHYAMOLI Pvt. Ltd.(Karunamoyee),Scania Multi-Axle AC Semi Sleeper (2+2),16:00:00,20:00:00,04:00:00,650,14,4.5,https://www.redbus.in/bus-tickets/durgapur-to-...,Durgapur (West Bengal) to Kolkata,South bengal
4,SHYAMOLI Pvt. Ltd.(Karunamoyee),Scania Multi-Axle AC Semi Sleeper (2+2),16:00:00,20:00:00,04:00:00,650,14,4.0,https://www.redbus.in/bus-tickets/durgapur-to-...,Durgapur (West Bengal) to Kolkata,South bengal
...,...,...,...,...,...,...,...,...,...,...,...
114,Dolphin tours and travels,A/C Seater / Sleeper (2+2),17:45:00,19:00:00,01:15:00,896,18,3.8,https://www.redbus.in/bus-tickets/durgapur-to-...,Durgapur (West Bengal) to Bankura,South bengal
115,Sri Balaji Parivahan,Non AC Seater (2+3),15:45:00,17:30:00,01:45:00,110,10,2.7,https://www.redbus.in/bus-tickets/durgapur-to-...,Durgapur (West Bengal) to Bankura,South bengal
116,SBSTC-SILIGURI - KOLKATA - VOLVO - 19:35 (BEL ...,Volvo AC Seater (2+2),19:35:00,08:35:00,13:00:00,1210,27,3.8,https://www.redbus.in/bus-tickets/siliguri-to-...,Siliguri to Kolkata,South bengal
117,Shyamoli Paribahan Pvt Ltd,Volvo Multi-Axle A/C seater/sleeper (2+1),20:00:00,09:00:00,13:00:00,2530,22,4.2,https://www.redbus.in/bus-tickets/siliguri-to-...,Siliguri to Kolkata,South bengal
118,Lokenath Bus Service,Volvo A/C B11R Multi Axle Semi Sleeper (2+2),21:00:00,09:00:00,12:00:00,2350,25,4.3,https://www.redbus.in/bus-tickets/siliguri-to-...,Siliguri to Kolkata,South bengal

In [133]:
df_buses_bengal =df_buses_bengal.dropna(subset=['Bus_name'])

In [134]:
df_buses_bengal = df_buses_bengal.dropna(subset=['Bus_type'])

In [152]:
# Clean the 'Start_time' column by removing extra spaces
df_buses_bengal['Start_time'] = df_buses_bengal['Start_time'].str.strip()

# Check if the cleaning helped
print(df_buses_bengal['Start_time'].head())

0    14:25:00
1    15:30:00
2    16:00:00
3    16:00:00
4    16:00:00
Name: Start_time, dtype: object

In [136]:

df_buses_bengal['Start_time'] = pd.to_datetime(df_buses_bengal['Start_time'], format='%H:%M', errors='coerce')

# Step 2: Extract only the time and convert to 'HHMMSS' format
df_buses_bengal['Start_time'] =df_buses_bengal['Start_time'].dt.strftime('%H:%M:%S')

# Display the updated DataFrame with 'Start_time' in 'HHMMSS' format
print(df_buses_bengal[['Start_time']])

    Start_time
0     14:25:00
1     15:30:00
2     16:00:00
3     16:00:00
4     16:00:00
..         ...
129   17:45:00
130   15:45:00
131   19:35:00
132   20:00:00
133   21:00:00

[119 rows x 1 columns]

In [153]:
# Clean the 'End_time' column by removing extra spaces
df_buses_bengal['End_time'] = df_buses_bengal['End_time'].str.strip()

# Check if the cleaning helped
print(df_buses_bengal['End_time'].head())

0    17:00:00
1    19:20:00
2    19:50:00
3    20:00:00
4    20:00:00
Name: End_time, dtype: object

In [138]:

df_buses_bengal['End_time'] = pd.to_datetime(df_buses_bengal['End_time'], format='%H:%M', errors='coerce')
df_buses_bengal['End_time'] =df_buses_bengal['End_time'].dt.strftime('%H:%M:%S')
print(df_buses_bengal[['End_time']])

     End_time
0    17:00:00
1    19:20:00
2    19:50:00
3    20:00:00
4    20:00:00
..        ...
129  19:00:00
130  17:30:00
131  08:35:00
132  09:00:00
133  09:00:00

[119 rows x 1 columns]

In [139]:
# Function to convert 'hh h mm m' format to 'hh:mm:ss' format
def convert_to_hms(duration):
    try:
        hours = 0
        minutes = 0
        seconds = 0
        
        # Check for hours and minutes in the string, extract the numeric values
        if 'h' in duration:
            hours = int(duration.split('h')[0].strip())  # Extract hours
            duration = duration.split('h')[1].strip()  # Remove hours part
        
        if 'm' in duration:
            minutes = int(duration.split('m')[0].strip())  # Extract minutes
            duration = duration.split('m')[1].strip()  # Remove minutes part
        
        # If there are remaining characters, assume it's seconds (in case there are seconds)
        if duration:
            seconds = int(duration.strip())  # Remaining part is seconds
        
        # Format to hh:mm:ss
        time_str = f'{hours:02}:{minutes:02}:{seconds:02}'
        return time_str
    except Exception as e:
        return "Invalid Format"

# Apply the conversion function to the 'Total_duration' column in place
df_buses_bengal['Total_duration'] = df_buses_bengal['Total_duration'].apply(convert_to_hms)

# Remove rows with 'Invalid Format' in the 'Total_duration' column without affecting other columns
df_buses_bengal = df_buses_bengal[df_buses_bengal['Total_duration'] != 'Invalid Format']

# Check the DataFrame to ensure it's correct
print(df_buses_bengal)

                                              Bus_name  \
0    WBTC (CTC) Habra - Barasat - Durgapur - Asanso...
1                           Shyamoli Paribahan Pvt Ltd
2                                            Greenline
3                      SHYAMOLI Pvt. Ltd.(Karunamoyee)
4                      SHYAMOLI Pvt. Ltd.(Karunamoyee)
..                                                 ...
129                          Dolphin tours and travels
130                               Sri Balaji Parivahan
131  SBSTC-SILIGURI - KOLKATA - VOLVO - 19:35 (BEL ...
132                         Shyamoli Paribahan Pvt Ltd
133                               Lokenath Bus Service

                                         Bus_type Start_time  End_time  \
0                             Non AC Seater (2+3)   14:25:00  17:00:00
1                          Volvo A/C Seater (2+2)   15:30:00  19:20:00
2                          Volvo A/C Seater (2+2)   16:00:00  19:50:00
3         Scania Multi-Axle AC Semi Sleeper (2+2)   16:00:00  20:00:00
4         Scania Multi-Axle AC Semi Sleeper (2+2)   16:00:00  20:00:00
..                                            ...        ...       ...
129                    A/C Seater / Sleeper (2+2)   17:45:00  19:00:00
130                           Non AC Seater (2+3)   15:45:00  17:30:00
131                         Volvo AC Seater (2+2)   19:35:00  08:35:00
132     Volvo Multi-Axle A/C seater/sleeper (2+1)   20:00:00  09:00:00
133  Volvo A/C B11R Multi Axle Semi Sleeper (2+2)   21:00:00  09:00:00

    Total_duration     Price     Seats_Available   Ratings  \
0         02:35:00   INR 135  16 Seats available   4.4\n17
1         03:50:00   INR 650  13 Seats available  4.2\n215
2         03:50:00   INR 486    1 Seat available  4.2\n163
3         04:00:00   INR 650  14 Seats available    4.5\n5
4         04:00:00   INR 650  14 Seats available  4.0\n374
..             ...       ...                 ...       ...
129       01:15:00   INR 896  18 Seats available       3.8
130       01:45:00   INR 110  10 Seats available       2.7
131       13:00:00  INR 1210  27 Seats available  3.8\n133
132       13:00:00  INR 2530  22 Seats available  4.2\n586
133       12:00:00  INR 2350  25 Seats available  4.3\n312

                                            Route_link  \
0    https://www.redbus.in/bus-tickets/durgapur-to-...
1    https://www.redbus.in/bus-tickets/durgapur-to-...
2    https://www.redbus.in/bus-tickets/durgapur-to-...
3    https://www.redbus.in/bus-tickets/durgapur-to-...
4    https://www.redbus.in/bus-tickets/durgapur-to-...
..                                                 ...
129  https://www.redbus.in/bus-tickets/durgapur-to-...
130  https://www.redbus.in/bus-tickets/durgapur-to-...
131  https://www.redbus.in/bus-tickets/siliguri-to-...
132  https://www.redbus.in/bus-tickets/siliguri-to-...
133  https://www.redbus.in/bus-tickets/siliguri-to-...

                            Route_name
0    Durgapur (West Bengal) to Kolkata
1    Durgapur (West Bengal) to Kolkata
2    Durgapur (West Bengal) to Kolkata
3    Durgapur (West Bengal) to Kolkata
4    Durgapur (West Bengal) to Kolkata
..                                 ...
129  Durgapur (West Bengal) to Bankura
130  Durgapur (West Bengal) to Bankura
131                Siliguri to Kolkata
132                Siliguri to Kolkata
133                Siliguri to Kolkata

[119 rows x 10 columns]

In [140]:
df_buses_bengal['Total_duration'].unique()

array(['02:35:00', '03:50:00', '04:00:00', '03:45:00', '01:15:00',
       '02:30:00', '02:15:00', '03:00:00', '03:20:00', '03:19:00',
       '02:50:00', '04:25:00', '05:00:00', '04:30:00', '04:55:00',
       '05:10:00', '06:00:00', '03:55:00', '03:30:00', '10:25:00',
       '09:50:00', '08:20:00', '03:35:00', '03:40:00', '10:15:00',
       '09:55:00', '07:30:00', '07:15:00', '08:10:00', '08:30:00',
       '02:01:00', '02:25:00', '03:05:00', '01:30:00', '10:00:00',
       '09:45:00', '09:30:00', '08:45:00', '00:15:00', '06:20:00',
       '06:10:00', '05:26:00', '03:01:00', '03:25:00', '02:55:00',
       '02:51:00', '02:38:00', '08:00:00', '04:35:00', '04:06:00',
       '04:13:00', '04:40:00', '05:30:00', '07:10:00', '01:45:00',
       '13:00:00', '12:00:00'], dtype=object)

In [141]:

df_buses_bengal["Price"] = df_buses_bengal["Price"].astype(str)

In [142]:
#convert prices to numeric
df_buses_bengal["Price"]=df_buses_bengal["Price"].str.replace("INR","")
df_buses_bengal["Price"]=df_buses_bengal["Price"].astype(float)
df_buses_bengal["Price"].fillna(0)

0       135.0
1       650.0
2       486.0
3       650.0
4       650.0
        ...
129     896.0
130     110.0
131    1210.0
132    2530.0
133    2350.0
Name: Price, Length: 119, dtype: float64

In [143]:
# Convert price column to numeric, setting errors='coerce' to replace invalid values with NaN
df_buses_bengal['Price'] = pd.to_numeric(df_buses_bengal['Price'], errors='coerce')

# Replace NaN (missing values) in the price column with a default value or None (for NULL in MySQL)
df_buses_bengal['Price'] = df_buses_bengal['Price'].fillna(0)  # Replace NaN with 0, or use None for NULL

In [154]:
df_buses_bengal['Price'].unique()

array([ 135,  650,  486,  700,  750,  429,  350,  110,  167,  185,  170,
        121,   95,  145,  300,  349,  549,  250,  285,  430,  524,  130,
        190,  142,  160,  150,  134,  238,  270,  246,   80,   78,  233,
        319,  288,   65,   64,   68,  155,  147,   96,  108,  163,  520,
        450,  115,  375,  271,  303,  312,   88,  335,  139,   75,  896,
       1210, 2530, 2350])

In [145]:
# Print rows where 'Price' is NaN
print(df_buses_bengal[df_buses_bengal['Price'].isnull()])

# Drop rows with NaN in 'Price'
df_buses_bengal.dropna(subset=['Price'], inplace=True)

Empty DataFrame
Columns: [Bus_name, Bus_type, Start_time, End_time, Total_duration, Price, Seats_Available, Ratings, Route_link, Route_name]
Index: []

In [146]:
import numpy as np
import re

# Function to clean the Ratings column
def clean_rating(value):
    # If the value is one of the invalid ones, return NaN
    if str(value).lower() in ['nan', 'new', ' ', 'none']:
        return np.nan
    # Attempt to extract a numeric value from the string
    match = re.match(r'(\d+\.\d+)', str(value))
    if match:
        return float(match.group(1))
    # If no match is found, return NaN
    return np.nan

# Clean the Ratings column
df_buses_bengal['Ratings'] = df_buses_bengal['Ratings'].apply(clean_rating)

# Show the cleaned data
print(df_buses_bengal[['Ratings']].head())

   Ratings
0      4.4
1      4.2
2      4.2
3      4.5
4      4.0

In [147]:
df_buses_bengal['Ratings'] = df_buses_bengal['Ratings'].fillna(0)

In [148]:
df_buses_bengal = df_buses_bengal.dropna(subset=['Ratings'])

In [155]:
df_buses_bengal['Ratings'].unique()

array([4.4, 4.2, 4.5, 4. , 3.8, 4.3, 4.1, 3.6, 4.8, 4.7, 3.9, 3.7, 2.2,
       3.4, 3.5, 2.3, 2.5, 4.9, 0. , 5. , 2.8, 4.6, 2.4, 2.9, 2. , 3.3,
       2.1, 3.2, 2.7])

In [150]:
df_buses_bengal['Seats_Available'].unique()

array(['16 Seats available', '13 Seats available', '1 Seat available',
       '14 Seats available', '17 Seats available', '11 Seats available',
       '9 Seats available', '10 Seats available', '26 Seats available',
       '22 Seats available', '24 Seats available', '18 Seats available',
       '45 Seats available', '35 Seats available', '23 Seats available',
       '25 Seats available', '32 Seats available', '15 Seats available',
       '42 Seats available', '52 Seats available', '44 Seats available',
       '33 Seats available', '34 Seats available', '38 Seats available',
       '12 Seats available', '20 Seats available', '48 Seats available',
       '39 Seats available', '19 Seats available', '46 Seats available',
       '21 Seats available', '50 Seats available', '41 Seats available',
       '36 Seats available', '7 Seats available', '31 Seats available',
       '66 Seats available', '51 Seats available', '43 Seats available',
       '28 Seats available', '3 Seats available', '49 Seats available',
       '61 Seats available', '30 Seats available', '47 Seats available',
       '40 Seats available', '27 Seats available'], dtype=object)

In [151]:
df_buses_bengal['Seats_Available']=df_buses_bengal['Seats_Available'].fillna("not available")

In [152]:
import re

# Apply a transformation to the 'Seats_Available' column
df_buses_bengal['Seats_Available'] = df_buses_bengal['Seats_Available'].apply(
    lambda x: int(re.findall(r'\d+', str(x))[0]) if re.findall(r'\d+', str(x)) else 0
)

# Print the DataFrame to check the updated 'Seats_Available' values
print(df_buses_bengal[['Seats_Available']])

     Seats_Available
0                 16
1                 13
2                  1
3                 14
4                 14
..               ...
129               18
130               10
131               27
132               22
133               25

[119 rows x 1 columns]

In [156]:
df_buses_bengal['Seats_Available'].unique()

array([16, 13,  1, 14, 17, 11,  9, 10, 26, 22, 24, 18, 45, 35, 23, 25, 32,
       15, 42, 52, 44, 33, 34, 38, 12, 20, 48, 39, 19, 46, 21, 50, 41, 36,
        7, 31, 66, 51, 43, 28,  3, 49, 61, 30, 47, 40, 27])

In [157]:
missing_values=df_buses_bengal.isnull().sum()
missing_values

Bus_name           0
Bus_type           0
Start_time         0
End_time           0
Total_duration     0
Price              0
Seats_Available    0
Ratings            0
Route_link         0
Route_name         0
State              0
dtype: int64

In [8]:
df_buses_bengal.to_csv('df_cleaned_bengal.csv', index=False)

In [14]:
df_buses_bengal

,Bus_name,Bus_type,Start_time,End_time,Total_duration,Price,Seats_Available,Ratings,Route_link,Route_name,State
0,WBTC (CTC) Habra - Barasat - Durgapur - Asanso...,Non AC Seater (2+3),14:25:00,17:00:00,02:35:00,135,16,4.4,https://www.redbus.in/bus-tickets/durgapur-to-...,Durgapur (West Bengal) to Kolkata,South bengal
1,Shyamoli Paribahan Pvt Ltd,Volvo A/C Seater (2+2),15:30:00,19:20:00,03:50:00,650,13,4.2,https://www.redbus.in/bus-tickets/durgapur-to-...,Durgapur (West Bengal) to Kolkata,South bengal
2,Greenline,Volvo A/C Seater (2+2),16:00:00,19:50:00,03:50:00,486,1,4.2,https://www.redbus.in/bus-tickets/durgapur-to-...,Durgapur (West Bengal) to Kolkata,South bengal
3,SHYAMOLI Pvt. Ltd.(Karunamoyee),Scania Multi-Axle AC Semi Sleeper (2+2),16:00:00,20:00:00,04:00:00,650,14,4.5,https://www.redbus.in/bus-tickets/durgapur-to-...,Durgapur (West Bengal) to Kolkata,South bengal
4,SHYAMOLI Pvt. Ltd.(Karunamoyee),Scania Multi-Axle AC Semi Sleeper (2+2),16:00:00,20:00:00,04:00:00,650,14,4.0,https://www.redbus.in/bus-tickets/durgapur-to-...,Durgapur (West Bengal) to Kolkata,South bengal
...,...,...,...,...,...,...,...,...,...,...,...
114,Dolphin tours and travels,A/C Seater / Sleeper (2+2),17:45:00,19:00:00,01:15:00,896,18,3.8,https://www.redbus.in/bus-tickets/durgapur-to-...,Durgapur (West Bengal) to Bankura,South bengal
115,Sri Balaji Parivahan,Non AC Seater (2+3),15:45:00,17:30:00,01:45:00,110,10,2.7,https://www.redbus.in/bus-tickets/durgapur-to-...,Durgapur (West Bengal) to Bankura,South bengal
116,SBSTC-SILIGURI - KOLKATA - VOLVO - 19:35 (BEL ...,Volvo AC Seater (2+2),19:35:00,08:35:00,13:00:00,1210,27,3.8,https://www.redbus.in/bus-tickets/siliguri-to-...,Siliguri to Kolkata,South bengal
117,Shyamoli Paribahan Pvt Ltd,Volvo Multi-Axle A/C seater/sleeper (2+1),20:00:00,09:00:00,13:00:00,2530,22,4.2,https://www.redbus.in/bus-tickets/siliguri-to-...,Siliguri to Kolkata,South bengal
118,Lokenath Bus Service,Volvo A/C B11R Multi Axle Semi Sleeper (2+2),21:00:00,09:00:00,12:00:00,2350,25,4.3,https://www.redbus.in/bus-tickets/siliguri-to-...,Siliguri to Kolkata,South bengal

**ANDHRA**

In [27]:
df_buses_andhra

,Bus_name,Bus_type,Start_time,End_time,Total_duration,Price,Seats_Available,Ratings,Route_link,Route_name,State
0,FRESHBUS,Electric A/C Seater (2+2),05:50:00,12:25:00,06:35:00,349.0,24,4.7,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Andhra
1,FRESHBUS,Electric A/C Seater (2+2),10:25:00,17:55:00,07:30:00,349.0,37,4.7,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Andhra
2,FRESHBUS,Electric A/C Seater (2+2),11:20:00,18:50:00,07:30:00,349.0,39,4.7,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Andhra
3,IntrCity SmartBus,A/C Seater / Sleeper (2+1),23:25:00,06:15:00,06:50:00,929.0,32,4.7,https://www.redbus.in/bus-tickets/vijayawada-t...,Vijayawada to Hyderabad,Andhra
4,IntrCity SmartBus,Bharat Benz A/C Seater /Sleeper (2+1),23:45:00,06:00:00,06:15:00,1069.0,28,4.6,https://www.redbus.in/bus-tickets/vijayawada-t...,Vijayawada to Hyderabad,Andhra
...,...,...,...,...,...,...,...,...,...,...,...
163,Giridhar Tours and Travels,A/C Sleeper (2+1),22:00:00,05:30:00,07:30:00,1099.0,17,4.2,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Markapuram,Andhra
164,Dosti Tours and Travels,A/C Sleeper (2+1),22:00:00,04:55:00,06:55:00,899.0,24,3.5,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Markapuram,Andhra
165,Indu Travels,Non A/C Seater / Sleeper (2+1),22:00:00,04:30:00,06:30:00,500.0,17,4.3,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Nandyal,Andhra
166,Indu Travels,Non A/C Seater / Sleeper (2+1),21:45:00,04:20:00,06:35:00,550.0,30,4.2,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Nandyal,Andhra
167,BRS Travels,A/C Sleeper (2+1),22:15:00,05:30:00,07:15:00,800.0,16,4.1,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Nandyal,Andhra

In [159]:
df_buses_andhra= df_buses_andhra.dropna(subset=['Bus_name'])

In [160]:
df_buses_andhra = df_buses_andhra.dropna(subset=['Bus_type'])

In [161]:
# Clean the 'Start_time' column by removing extra spaces
df_buses_andhra ['Start_time'] = df_buses_andhra ['Start_time'].str.strip()

# Check if the cleaning helped
print(df_buses_andhra ['Start_time'].head())

0    05:50:00
1    10:25:00
2    11:20:00
3    23:25:00
4    23:45:00
Name: Start_time, dtype: object

In [162]:

df_buses_andhra ['Start_time'] = pd.to_datetime(df_buses_andhra ['Start_time'], format='%H:%M', errors='coerce')
df_buses_andhra ['Start_time'] = df_buses_andhra ['Start_time'].dt.strftime('%H:%M:%S')
print(df_buses_andhra [['Start_time']])

    Start_time
0     05:50:00
1     10:25:00
2     11:20:00
5     23:25:00
6     23:45:00
..         ...
232   22:00:00
233   22:00:00
236   22:00:00
237   21:45:00
238   22:15:00

[168 rows x 1 columns]

In [162]:
# Clean the 'End_time' column by removing extra spaces
df_buses_andhra['End_time'] = df_buses_andhra['End_time'].str.strip()

# Check if the cleaning helped
print(df_buses_andhra['End_time'].head())

0    12:25:00
1    17:55:00
2    18:50:00
3    06:15:00
4    06:00:00
Name: End_time, dtype: object

In [164]:

df_buses_andhra['End_time'] = pd.to_datetime(df_buses_andhra['End_time'], format='%H:%M', errors='coerce')
df_buses_andhra['End_time'] =df_buses_andhra['End_time'].dt.strftime('%H:%M:%S')
print(df_buses_andhra[['End_time']])

     End_time
0    12:25:00
1    17:55:00
2    18:50:00
5    06:15:00
6    06:00:00
..        ...
232  05:30:00
233  04:55:00
236  04:30:00
237  04:20:00
238  05:30:00

[168 rows x 1 columns]

In [165]:
# Function to convert 'hh h mm m' format to 'hh:mm:ss' format
def convert_to_hms(duration):
    try:
        hours = 0
        minutes = 0
        seconds = 0
        
        # Check for hours and minutes in the string, extract the numeric values
        if 'h' in duration:
            hours = int(duration.split('h')[0].strip())  # Extract hours
            duration = duration.split('h')[1].strip()  # Remove hours part
        
        if 'm' in duration:
            minutes = int(duration.split('m')[0].strip())  # Extract minutes
            duration = duration.split('m')[1].strip()  # Remove minutes part
        
        # If there are remaining characters, assume it's seconds (in case there are seconds)
        if duration:
            seconds = int(duration.strip())  # Remaining part is seconds
        
        # Format to hh:mm:ss
        time_str = f'{hours:02}:{minutes:02}:{seconds:02}'
        return time_str
    except Exception as e:
        return "Invalid Format"

# Apply the conversion function to the 'Total_duration' column in place
df_buses_andhra['Total_duration'] = df_buses_andhra['Total_duration'].apply(convert_to_hms)

# Remove rows with 'Invalid Format' in the 'Total_duration' column without affecting other columns
df_buses_andhra= df_buses_andhra[df_buses_andhra['Total_duration'] != 'Invalid Format']

# Check the DataFrame to ensure it's correct
print(df_buses_andhra)

                       Bus_name                               Bus_type  \
0                      FRESHBUS              Electric A/C Seater (2+2)
1                      FRESHBUS              Electric A/C Seater (2+2)
2                      FRESHBUS              Electric A/C Seater (2+2)
5             IntrCity SmartBus             A/C Seater / Sleeper (2+1)
6             IntrCity SmartBus  Bharat Benz A/C Seater /Sleeper (2+1)
..                          ...                                    ...
232  Giridhar Tours and Travels                      A/C Sleeper (2+1)
233     Dosti Tours and Travels                      A/C Sleeper (2+1)
236                Indu Travels         Non A/C Seater / Sleeper (2+1)
237                Indu Travels         Non A/C Seater / Sleeper (2+1)
238                 BRS Travels                      A/C Sleeper (2+1)

    Start_time  End_time Total_duration     Price     Seats_Available  \
0     05:50:00  12:25:00       06:35:00       349  24 Seats available
1     10:25:00  17:55:00       07:30:00       349  37 Seats available
2     11:20:00  18:50:00       07:30:00       349  39 Seats available
5     23:25:00  06:15:00       06:50:00   INR 929  32 Seats available
6     23:45:00  06:00:00       06:15:00  INR 1069  28 Seats available
..         ...       ...            ...       ...                 ...
232   22:00:00  05:30:00       07:30:00  INR 1099  17 Seats available
233   22:00:00  04:55:00       06:55:00   INR 899  24 Seats available
236   22:00:00  04:30:00       06:30:00   INR 500  17 Seats available
237   21:45:00  04:20:00       06:35:00   INR 550  30 Seats available
238   22:15:00  05:30:00       07:15:00   INR 800  16 Seats available

       Ratings                                         Route_link  \
0     4.7\n398  https://www.redbus.in/bus-tickets/hyderabad-to...
1     4.7\n355  https://www.redbus.in/bus-tickets/hyderabad-to...
2     4.7\n320  https://www.redbus.in/bus-tickets/hyderabad-to...
5     4.7\n849  https://www.redbus.in/bus-tickets/vijayawada-t...
6    4.6\n1138  https://www.redbus.in/bus-tickets/vijayawada-t...
..         ...                                                ...
232    4.2\n65  https://www.redbus.in/bus-tickets/hyderabad-to...
233    3.5\n95  https://www.redbus.in/bus-tickets/hyderabad-to...
236   4.3\n175  https://www.redbus.in/bus-tickets/hyderabad-to...
237   4.2\n251  https://www.redbus.in/bus-tickets/hyderabad-to...
238   4.1\n359  https://www.redbus.in/bus-tickets/hyderabad-to...

                  Route_name
0    Hyderabad to Vijayawada
1    Hyderabad to Vijayawada
2    Hyderabad to Vijayawada
5    Vijayawada to Hyderabad
6    Vijayawada to Hyderabad
..                       ...
232  Hyderabad to Markapuram
233  Hyderabad to Markapuram
236     Hyderabad to Nandyal
237     Hyderabad to Nandyal
238     Hyderabad to Nandyal

[168 rows x 10 columns]

In [163]:
df_buses_andhra['Total_duration'].unique()

array(['06:35:00', '07:30:00', '06:50:00', '06:15:00', '06:30:00',
       '03:20:00', '03:40:00', '04:40:00', '04:35:00', '03:00:00',
       '03:15:00', '06:25:00', '05:48:00', '05:30:00', '04:10:00',
       '05:51:00', '03:55:00', '07:45:00', '08:30:00', '08:35:00',
       '02:55:00', '03:05:00', '04:00:00', '08:05:00', '07:50:00',
       '07:35:00', '07:03:00', '05:10:00', '04:30:00', '03:30:00',
       '03:45:00', '03:50:00', '05:15:00', '07:10:00', '05:05:00',
       '07:15:00', '06:45:00', '07:55:00', '06:40:00', '06:05:00',
       '05:45:00', '13:50:00', '07:40:00', '04:15:00', '04:20:00',
       '07:39:00', '08:22:00', '08:10:00', '03:35:00', '05:20:00',
       '28:30:00', '07:00:00', '04:50:00', '05:00:00', '04:25:00',
       '08:15:00', '03:14:00', '07:12:00', '08:00:00', '05:01:00',
       '06:16:00', '06:10:00', '06:00:00', '06:56:00', '08:33:00',
       '07:25:00', '07:20:00', '10:00:00', '09:30:00', '04:45:00',
       '04:59:00', '04:51:00', '05:50:00', '06:55:00'], dtype=object)

In [167]:

df_buses_andhra["Price"] = df_buses_andhra["Price"].astype(str)

In [168]:
#convert prices to numeric
df_buses_andhra["Price"]=df_buses_andhra["Price"].str.replace("INR","")
df_buses_andhra["Price"]=df_buses_andhra["Price"].astype(float)
df_buses_andhra["Price"].fillna(0)

0       349.0
1       349.0
2       349.0
5       929.0
6      1069.0
        ...
232    1099.0
233     899.0
236     500.0
237     550.0
238     800.0
Name: Price, Length: 168, dtype: float64

In [169]:
# Convert price column to numeric, setting errors='coerce' to replace invalid values with NaN
df_buses_andhra['Price'] = pd.to_numeric(df_buses_andhra['Price'], errors='coerce')

# Replace NaN (missing values) in the price column with a default value or None (for NULL in MySQL)
df_buses_andhra['Price'] = df_buses_andhra['Price'].fillna(0)  # Replace NaN with 0, or use None for NULL

In [170]:
df_buses_andhra['Price'].unique()

array([ 349.  ,  929.  , 1069.  ,  830.  ,  599.  , 5000.  ,  454.  ,
        399.  ,  394.  ,  549.  ,  570.  ,  700.  ,  585.  ,  370.  ,
        521.  ,  807.  , 1013.  ,  799.  ,  999.  , 1500.  ,  600.  ,
        500.  ,  738.  , 1200.  ,  619.  , 1160.  ,  350.  ,  499.  ,
        900.  , 1050.  ,  824.  , 1450.  ,  431.  ,  332.  , 1149.  ,
       1320.  , 1049.  ,  666.  ,  790.  ,  777.  , 3999.  ,  850.  ,
        560.  ,  780.  ,  555.  ,  333.  ,  699.  ,  464.  ,  750.  ,
        994.  ,  899.  ,  450.  ,  844.  ,  949.  ,  792.  ,  238.  ,
        400.  ,  422.  ,  398.  , 3000.  , 1419.  , 1329.  ,  979.  ,
        980.  , 1401.79,  650.  ,  250.  ,  784.  , 1079.  ,  520.  ,
        392.  ,  478.  ,  709.  ,  749.  ,  408.  ,  690.  , 4000.  ,
        356.25,  989.  ,  802.  ,  569.  ,  620.  , 1919.  , 1000.  ,
       1425.  , 1099.  , 1673.  ,  990.  , 1090.  ,  970.  ,  362.  ,
        506.  , 1220.  , 1299.  , 1139.  ,  373.  ,  930.  , 2099.  ,
        630.  ,  550.  ,  800.  ])

In [171]:

print(df_buses_andhra[df_buses_andhra['Price'].isnull()])
df_buses_andhra.dropna(subset=['Price'], inplace=True)

Empty DataFrame
Columns: [Bus_name, Bus_type, Start_time, End_time, Total_duration, Price, Seats_Available, Ratings, Route_link, Route_name]
Index: []

In [172]:
import numpy as np
import re

# Function to clean the Ratings column
def clean_rating(value):
    # If the value is one of the invalid ones, return NaN
    if str(value).lower() in ['nan', 'new', ' ', 'none']:
        return np.nan
    # Attempt to extract a numeric value from the string
    match = re.match(r'(\d+\.\d+)', str(value))
    if match:
        return float(match.group(1))
    # If no match is found, return NaN
    return np.nan

# Clean the Ratings column
df_buses_andhra['Ratings'] =df_buses_andhra['Ratings'].apply(clean_rating)

# Show the cleaned data
print(df_buses_andhra[['Ratings']].head())

   Ratings
0      4.7
1      4.7
2      4.7
5      4.7
6      4.6

In [173]:
df_buses_andhra['Ratings'] =df_buses_andhra['Ratings'].fillna(0)

In [174]:
df_buses_andhra = df_buses_andhra.dropna(subset=['Ratings'])

In [164]:
df_buses_andhra['Ratings'].unique()

array([4.7, 4.6, 0. , 3.4, 3.6, 3.8, 4.2, 3.7, 5. , 4.4, 3.1, 4.8, 3.3,
       4. , 4.5, 4.3, 4.9, 3. , 3.2, 2.7, 4.1, 3.5, 3.9, 2.5, 2.3, 2.8,
       2.1, 2.6])

In [176]:
df_buses_andhra['Seats_Available'].unique()

array(['24 Seats available', '37 Seats available', '39 Seats available',
       '32 Seats available', '28 Seats available', '23 Seats available',
       '13 Seats available', '1 Seat available', '2 Seats available',
       '27 Seats available', '11 Seats available', '4 Seats available',
       '3 Seats available', '17 Seats available', '31 Seats available',
       '20 Seats available', '34 Seats available', '9 Seats available',
       '14 Seats available', '6 Seats available', '29 Seats available',
       '22 Seats available', '25 Seats available', '33 Seats available',
       '30 Seats available', '18 Seats available', '26 Seats available',
       '42 Seats available', '40 Seats available', '7 Seats available',
       '15 Seats available', '35 Seats available', '12 Seats available',
       '8 Seats available', '19 Seats available', '21 Seats available',
       '16 Seats available', '10 Seats available'], dtype=object)

In [177]:
import re
df_buses_andhra['Seats_Available'] = df_buses_andhra['Seats_Available'].apply(
    lambda x: int(re.findall(r'\d+', x)[0]) if re.findall(r'\d+', x) else 0
)

print(df_buses_andhra)

                       Bus_name                               Bus_type  \
0                      FRESHBUS              Electric A/C Seater (2+2)
1                      FRESHBUS              Electric A/C Seater (2+2)
2                      FRESHBUS              Electric A/C Seater (2+2)
5             IntrCity SmartBus             A/C Seater / Sleeper (2+1)
6             IntrCity SmartBus  Bharat Benz A/C Seater /Sleeper (2+1)
..                          ...                                    ...
232  Giridhar Tours and Travels                      A/C Sleeper (2+1)
233     Dosti Tours and Travels                      A/C Sleeper (2+1)
236                Indu Travels         Non A/C Seater / Sleeper (2+1)
237                Indu Travels         Non A/C Seater / Sleeper (2+1)
238                 BRS Travels                      A/C Sleeper (2+1)

    Start_time  End_time Total_duration   Price  Seats_Available  Ratings  \
0     05:50:00  12:25:00       06:35:00   349.0               24      4.7
1     10:25:00  17:55:00       07:30:00   349.0               37      4.7
2     11:20:00  18:50:00       07:30:00   349.0               39      4.7
5     23:25:00  06:15:00       06:50:00   929.0               32      4.7
6     23:45:00  06:00:00       06:15:00  1069.0               28      4.6
..         ...       ...            ...     ...              ...      ...
232   22:00:00  05:30:00       07:30:00  1099.0               17      4.2
233   22:00:00  04:55:00       06:55:00   899.0               24      3.5
236   22:00:00  04:30:00       06:30:00   500.0               17      4.3
237   21:45:00  04:20:00       06:35:00   550.0               30      4.2
238   22:15:00  05:30:00       07:15:00   800.0               16      4.1

                                            Route_link  \
0    https://www.redbus.in/bus-tickets/hyderabad-to...
1    https://www.redbus.in/bus-tickets/hyderabad-to...
2    https://www.redbus.in/bus-tickets/hyderabad-to...
5    https://www.redbus.in/bus-tickets/vijayawada-t...
6    https://www.redbus.in/bus-tickets/vijayawada-t...
..                                                 ...
232  https://www.redbus.in/bus-tickets/hyderabad-to...
233  https://www.redbus.in/bus-tickets/hyderabad-to...
236  https://www.redbus.in/bus-tickets/hyderabad-to...
237  https://www.redbus.in/bus-tickets/hyderabad-to...
238  https://www.redbus.in/bus-tickets/hyderabad-to...

                  Route_name
0    Hyderabad to Vijayawada
1    Hyderabad to Vijayawada
2    Hyderabad to Vijayawada
5    Vijayawada to Hyderabad
6    Vijayawada to Hyderabad
..                       ...
232  Hyderabad to Markapuram
233  Hyderabad to Markapuram
236     Hyderabad to Nandyal
237     Hyderabad to Nandyal
238     Hyderabad to Nandyal

[168 rows x 10 columns]

In [178]:
df_buses_andhra['Seats_Available'].unique()

array([24, 37, 39, 32, 28, 23, 13,  1,  2, 27, 11,  4,  3, 17, 31, 20, 34,
        9, 14,  6, 29, 22, 25, 33, 30, 18, 26, 42, 40,  7, 15, 35, 12,  8,
       19, 21, 16, 10])

In [179]:
missing_values=df_buses_andhra.isnull().sum()
missing_values

Bus_name           0
Bus_type           0
Start_time         0
End_time           0
Total_duration     0
Price              0
Seats_Available    0
Ratings            0
Route_link         0
Route_name         0
dtype: int64

In [9]:
df_buses_andhra.to_csv('df_cleaned_andhra.csv', index=False)

In [16]:
df_buses_andhra

,Bus_name,Bus_type,Start_time,End_time,Total_duration,Price,Seats_Available,Ratings,Route_link,Route_name,State
0,FRESHBUS,Electric A/C Seater (2+2),05:50:00,12:25:00,06:35:00,349.0,24,4.7,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Andhra
1,FRESHBUS,Electric A/C Seater (2+2),10:25:00,17:55:00,07:30:00,349.0,37,4.7,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Andhra
2,FRESHBUS,Electric A/C Seater (2+2),11:20:00,18:50:00,07:30:00,349.0,39,4.7,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Vijayawada,Andhra
3,IntrCity SmartBus,A/C Seater / Sleeper (2+1),23:25:00,06:15:00,06:50:00,929.0,32,4.7,https://www.redbus.in/bus-tickets/vijayawada-t...,Vijayawada to Hyderabad,Andhra
4,IntrCity SmartBus,Bharat Benz A/C Seater /Sleeper (2+1),23:45:00,06:00:00,06:15:00,1069.0,28,4.6,https://www.redbus.in/bus-tickets/vijayawada-t...,Vijayawada to Hyderabad,Andhra
...,...,...,...,...,...,...,...,...,...,...,...
163,Giridhar Tours and Travels,A/C Sleeper (2+1),22:00:00,05:30:00,07:30:00,1099.0,17,4.2,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Markapuram,Andhra
164,Dosti Tours and Travels,A/C Sleeper (2+1),22:00:00,04:55:00,06:55:00,899.0,24,3.5,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Markapuram,Andhra
165,Indu Travels,Non A/C Seater / Sleeper (2+1),22:00:00,04:30:00,06:30:00,500.0,17,4.3,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Nandyal,Andhra
166,Indu Travels,Non A/C Seater / Sleeper (2+1),21:45:00,04:20:00,06:35:00,550.0,30,4.2,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Nandyal,Andhra
167,BRS Travels,A/C Sleeper (2+1),22:15:00,05:30:00,07:15:00,800.0,16,4.1,https://www.redbus.in/bus-tickets/hyderabad-to...,Hyderabad to Nandyal,Andhra

**UTTAR PRADESH**

In [30]:
df_buses_up

,Bus_name,Bus_type,Start_time,End_time,Total_duration,Price,Seats_Available,Ratings,Route_link,Route_name,State
0,FlixBus,AC Seater (2+2),23:35:00,05:00:00,05:25:00,427.68,9,4.3,https://www.redbus.in/bus-tickets/delhi-to-bar...,Delhi to Bareilly (Uttar Pradesh),Uttar pradesh
1,RS YADAV SMART BUS,Bharat Benz A/C Seater /Sleeper (2+1),21:40:00,04:45:00,07:05:00,799.00,12,3.5,https://www.redbus.in/bus-tickets/delhi-to-bar...,Delhi to Bareilly (Uttar Pradesh),Uttar pradesh
2,New Khaira Transport,A/C Seater / Sleeper (2+2),21:00:00,03:30:00,06:30:00,500.00,9,1.9,https://www.redbus.in/bus-tickets/delhi-to-bar...,Delhi to Bareilly (Uttar Pradesh),Uttar pradesh
3,Gola Bus Service,Bharat Benz A/C Seater /Sleeper (2+1),22:30:00,06:30:00,08:00:00,699.00,37,4.7,https://www.redbus.in/bus-tickets/delhi-to-luc...,Delhi to Lucknow,Uttar pradesh
4,PTC-SKYBUS,VE A/C Seater / Sleeper (2+1),23:50:00,07:30:00,07:40:00,700.00,24,4.7,https://www.redbus.in/bus-tickets/delhi-to-luc...,Delhi to Lucknow,Uttar pradesh
...,...,...,...,...,...,...,...,...,...,...,...
145,RSRTC - 195742,A/C Seater / Sleeper (2+1),23:59:00,06:30:00,06:31:00,664.00,34,1.7,https://www.redbus.in/bus-tickets/delhi-to-hal...,Delhi to Haldwani,Uttar pradesh
146,Laxmi holidays,Bharat Benz A/C Sleeper (2+1),23:00:00,05:00:00,06:00:00,665.00,20,4.6,https://www.redbus.in/bus-tickets/delhi-to-hal...,Delhi to Haldwani,Uttar pradesh
147,India Tours & Travels (GetBookCab),A/C Seater / Sleeper (2+2),23:00:00,03:45:00,04:45:00,391.00,39,4.5,https://www.redbus.in/bus-tickets/delhi-to-hal...,Delhi to Haldwani,Uttar pradesh
148,UPSRTC - BTR0023,Ordinary Non AC Seater 2+3,19:00:00,01:17:00,06:17:00,283.00,52,3.3,https://www.redbus.in/bus-tickets/allahabad-to...,Prayagraj(Uttar Pradesh) to Azamgarh,Uttar pradesh
149,RS YADAV SMART BUS,A/C Seater / Sleeper (2+1),22:45:00,05:55:00,07:10:00,1099.00,10,4.5,https://www.redbus.in/bus-tickets/shahjahanpur...,Shahjahanpur (Uttar Pradesh) to Delhi,Uttar pradesh

In [183]:
df_buses_up = df_buses_up.dropna(subset=['Bus_name'])

In [184]:
df_buses_up = df_buses_up.dropna(subset=['Bus_type'])

In [168]:
# Clean the 'Start_time' column by removing extra spaces
df_buses_up['Start_time'] =df_buses_up['Start_time'].str.strip()

# Check if the cleaning helped
print(df_buses_up['Start_time'].head())

0    23:35:00
1    21:40:00
2    21:00:00
3    22:30:00
4    23:50:00
Name: Start_time, dtype: object

In [186]:

df_buses_up['Start_time'] = pd.to_datetime(df_buses_up['Start_time'], format='%H:%M', errors='coerce')

df_buses_up['Start_time'] = df_buses_up['Start_time'].dt.strftime('%H:%M:%S')

print(df_buses_up[['Start_time']])

    Start_time
0     23:35:00
1     21:40:00
2     21:00:00
5     22:30:00
6     23:50:00
..         ...
177   23:59:00
178   23:00:00
179   23:00:00
182   19:00:00
183   22:45:00

[151 rows x 1 columns]

In [187]:
print(df_buses_up['Start_time'].unique())

['23:35:00' '21:40:00' '21:00:00' '22:30:00' '23:50:00' '23:45:00'
 '16:15:00' '23:59:00' '17:00:00' '23:40:00' '23:46:00' '21:30:00'
 '17:59:00' '18:29:00' '19:35:00' '20:28:00' '16:30:00' '16:31:00'
 '17:15:00' '17:30:00' '22:20:00' '20:40:00' '16:50:00' '17:35:00'
 '18:00:00' '18:30:00' '22:00:00' '23:30:00' '16:00:00' '15:30:00'
 '23:29:00' '18:20:00' '17:20:00' '20:20:00' '20:30:00' '20:00:00'
 '18:45:00' '19:00:00' '22:23:00' '23:49:00' '22:15:00' '20:02:00'
 '21:20:00' '18:15:00' '19:10:00' '20:45:00' '23:20:00' '21:55:00'
 '22:45:00' '00:50:00' '15:40:00' '16:25:00' '17:25:00' '18:25:00'
 '18:01:00' '23:00:00' '19:30:00' '22:50:00' '19:26:00' '19:50:00'
 '20:01:00' '17:10:00' '18:05:00' '19:04:00' '19:05:00' '23:05:00'
 '15:50:00' '19:20:00' '15:55:00' '18:40:00' '19:40:00' '21:01:00'
 '23:55:00' '22:40:00' '22:14:00' '18:03:00' '22:46:00']

In [169]:
# Clean the 'End_time' column by removing extra spaces
df_buses_up['End_time'] = df_buses_up['End_time'].str.strip()

# Check if the cleaning helped
print(df_buses_up['End_time'].head())

0    05:00:00
1    04:45:00
2    03:30:00
3    06:30:00
4    07:30:00
Name: End_time, dtype: object

In [189]:

df_buses_up['End_time'] = pd.to_datetime(df_buses_up['End_time'], format='%H:%M', errors='coerce')
df_buses_up['End_time'] =df_buses_up['End_time'].dt.strftime('%H:%M:%S')
print(df_buses_up[['End_time']])

     End_time
0    05:00:00
1    04:45:00
2    03:30:00
5    06:30:00
6    07:30:00
..        ...
177  06:30:00
178  05:00:00
179  03:45:00
182  01:17:00
183  05:55:00

[151 rows x 1 columns]

In [190]:
# Function to convert 'hh h mm m' format to 'hh:mm:ss' format
def convert_to_hms(duration):
    try:
        hours = 0
        minutes = 0
        seconds = 0
        
        # Check for hours and minutes in the string, extract the numeric values
        if 'h' in duration:
            hours = int(duration.split('h')[0].strip())  # Extract hours
            duration = duration.split('h')[1].strip()  # Remove hours part
        
        if 'm' in duration:
            minutes = int(duration.split('m')[0].strip())  # Extract minutes
            duration = duration.split('m')[1].strip()  # Remove minutes part
        
        # If there are remaining characters, assume it's seconds (in case there are seconds)
        if duration:
            seconds = int(duration.strip())  # Remaining part is seconds
        
        # Format to hh:mm:ss
        time_str = f'{hours:02}:{minutes:02}:{seconds:02}'
        return time_str
    except Exception as e:
        return "Invalid Format"

# Apply the conversion function to the 'Total_duration' column in place
df_buses_up['Total_duration'] = df_buses_up['Total_duration'].apply(convert_to_hms)

# Remove rows with 'Invalid Format' in the 'Total_duration' column without affecting other columns
df_buses_up = df_buses_up[df_buses_up['Total_duration'] != 'Invalid Format']

# Check the DataFrame to ensure it's correct
print(df_buses_up)

                               Bus_name  \
0                               FlixBus
1                    RS YADAV SMART BUS
2                  New Khaira Transport
5                      Gola Bus Service
6                            PTC-SKYBUS
..                                  ...
177                      RSRTC - 195742
178                      Laxmi holidays
179  India Tours & Travels (GetBookCab)
182                    UPSRTC - BTR0023
183                  RS YADAV SMART BUS

                                  Bus_type Start_time  End_time  \
0                          AC Seater (2+2)   23:35:00  05:00:00
1    Bharat Benz A/C Seater /Sleeper (2+1)   21:40:00  04:45:00
2               A/C Seater / Sleeper (2+2)   21:00:00  03:30:00
5    Bharat Benz A/C Seater /Sleeper (2+1)   22:30:00  06:30:00
6            VE A/C Seater / Sleeper (2+1)   23:50:00  07:30:00
..                                     ...        ...       ...
177             A/C Seater / Sleeper (2+1)   23:59:00  06:30:00
178          Bharat Benz A/C Sleeper (2+1)   23:00:00  05:00:00
179             A/C Seater / Sleeper (2+2)   23:00:00  03:45:00
182             Ordinary Non AC Seater 2+3   19:00:00  01:17:00
183             A/C Seater / Sleeper (2+1)   22:45:00  05:55:00

    Total_duration       Price     Seats_Available    Ratings  \
0         05:25:00  INR 427.68   9 Seats available   4.3\n128
1         07:05:00     INR 799  12 Seats available    3.5\n40
2         06:30:00     INR 500   9 Seats available    1.9\n37
5         08:00:00     INR 699  37 Seats available  4.7\n1447
6         07:40:00     INR 700  24 Seats available  4.7\n1424
..             ...         ...                 ...        ...
177       06:31:00     INR 664  34 Seats available    1.7\n11
178       06:00:00         665  20 Seats available   4.6\n333
179       04:45:00         391  39 Seats available   4.5\n447
182       06:17:00     INR 283  52 Seats available        3.3
183       07:10:00    INR 1099  10 Seats available    4.5\n18

                                            Route_link  \
0    https://www.redbus.in/bus-tickets/delhi-to-bar...
1    https://www.redbus.in/bus-tickets/delhi-to-bar...
2    https://www.redbus.in/bus-tickets/delhi-to-bar...
5    https://www.redbus.in/bus-tickets/delhi-to-luc...
6    https://www.redbus.in/bus-tickets/delhi-to-luc...
..                                                 ...
177  https://www.redbus.in/bus-tickets/delhi-to-hal...
178  https://www.redbus.in/bus-tickets/delhi-to-hal...
179  https://www.redbus.in/bus-tickets/delhi-to-hal...
182  https://www.redbus.in/bus-tickets/allahabad-to...
183  https://www.redbus.in/bus-tickets/shahjahanpur...

                                Route_name
0        Delhi to Bareilly (Uttar Pradesh)
1        Delhi to Bareilly (Uttar Pradesh)
2        Delhi to Bareilly (Uttar Pradesh)
5                         Delhi to Lucknow
6                         Delhi to Lucknow
..                                     ...
177                      Delhi to Haldwani
178                      Delhi to Haldwani
179                      Delhi to Haldwani
182   Prayagraj(Uttar Pradesh) to Azamgarh
183  Shahjahanpur (Uttar Pradesh) to Delhi

[150 rows x 10 columns]

In [170]:
df_buses_up['Total_duration'].unique()

array(['05:25:00', '07:05:00', '06:30:00', '08:00:00', '07:40:00',
       '05:00:00', '05:56:00', '05:30:00', '06:20:00', '05:50:00',
       '05:46:00', '05:47:00', '03:02:00', '03:19:00', '03:20:00',
       '02:52:00', '03:21:00', '04:30:00', '08:40:00', '08:15:00',
       '05:40:00', '09:00:00', '09:10:00', '09:20:00', '04:50:00',
       '03:40:00', '13:20:00', '13:30:00', '13:10:00', '13:15:00',
       '10:15:00', '10:00:00', '07:00:00', '07:03:00', '06:31:00',
       '05:05:00', '04:25:00', '04:00:00', '09:30:00', '07:58:00',
       '10:50:00', '02:30:00', '04:10:00', '03:50:00', '08:05:00',
       '07:45:00', '07:50:00', '07:30:00', '06:35:00', '05:15:00',
       '03:53:00', '06:00:00', '07:10:00', '08:30:00', '07:15:00',
       '06:45:00', '08:20:00', '06:15:00', '05:34:00', '05:29:00',
       '04:51:00', '04:49:00', '04:47:00', '05:55:00', '06:49:00',
       '07:55:00', '06:28:00', '07:20:00', '03:45:00', '04:45:00',
       '04:35:00', '15:00:00', '12:50:00', '13:40:00', '08:49:00',
       '03:00:00', '06:05:00', '05:45:00', '07:44:00', '06:46:00',
       '05:35:00', '05:27:00', '05:59:00', '06:17:00'], dtype=object)

In [192]:
df_buses_up["Price"] = df_buses_up["Price"].astype(str)

In [193]:
#convert prices to numeric
df_buses_up["Price"]=df_buses_up["Price"].str.replace("INR","")
df_buses_up["Price"]=df_buses_up["Price"].astype(float)
df_buses_up["Price"].fillna(0)

0       427.68
1       799.00
2       500.00
5       699.00
6       700.00
        ...
177     664.00
178     665.00
179     391.00
182     283.00
183    1099.00
Name: Price, Length: 150, dtype: float64

In [194]:
# Convert price column to numeric, setting errors='coerce' to replace invalid values with NaN
df_buses_up['Price'] = pd.to_numeric(df_buses_up['Price'], errors='coerce')

# Replace NaN (missing values) in the price column with a default value or None (for NULL in MySQL)
df_buses_up['Price'] = df_buses_up['Price'].fillna(0)  # Replace NaN with 0, or use None for NULL

In [171]:
df_buses_up['Price'].unique()

array([ 427.68,  799.  ,  500.  ,  699.  ,  700.  ,  740.  , 1099.  ,
        675.  ,  499.  ,  463.  ,  650.  ,  335.  ,  224.  ,  280.  ,
        708.  ,  435.  ,  503.  ,  550.  , 1039.  , 1109.  ,  959.  ,
        719.  ,  450.  ,  600.  ,  891.  ,  361.  ,  664.  ,  999.  ,
       1199.  ,  549.  ,  649.  ,  705.  ,  998.  ,  359.  ,  599.  ,
        504.  ,  709.  ,  689.  ,  529.  ,  849.  , 1499.  ,  449.  ,
       1399.  ,  924.  ,  284.  ,  409.  ,  452.  ,  555.  ,  439.  ,
        810.  , 1019.  ,  939.  ,  949.  ,  749.  ,  429.  ,  620.  ,
        647.  ,  414.  ,  534.  , 1490.  ,  379.  ,  368.  ,  375.1 ,
        360.  , 1069.  , 1200.  ,  321.  ,  212.5 , 1860.  , 1599.  ,
       1020.  ,  864.  ,  571.  ,  899.  ,  750.  , 1000.  ,  355.  ,
        665.  ,  391.  ,  283.  ])

In [196]:
# Print rows where 'Price' is NaN
print(df_buses_up[df_buses_up['Price'].isnull()])

# Drop rows with NaN in 'Price'
df_buses_up.dropna(subset=['Price'], inplace=True)

Empty DataFrame
Columns: [Bus_name, Bus_type, Start_time, End_time, Total_duration, Price, Seats_Available, Ratings, Route_link, Route_name]
Index: []

In [197]:
import numpy as np
import re

# Function to clean the Ratings column
def clean_rating(value):
    # If the value is one of the invalid ones, return NaN
    if str(value).lower() in ['nan', 'new', ' ', 'none']:
        return np.nan
    # Attempt to extract a numeric value from the string
    match = re.match(r'(\d+\.\d+)', str(value))
    if match:
        return float(match.group(1))
    # If no match is found, return NaN
    return np.nan

# Clean the Ratings column
df_buses_up['Ratings'] = df_buses_up['Ratings'].apply(clean_rating)

# Show the cleaned data
print(df_buses_up[['Ratings']].head())

   Ratings
0      4.3
1      3.5
2      1.9
5      4.7
6      4.7

In [198]:
df_buses_up['Ratings'] = df_buses_up['Ratings'].fillna(0)

In [199]:
df_buses_up = df_buses_up.dropna(subset=['Ratings'])

In [172]:
df_buses_up['Ratings'].unique()

array([4.3, 3.5, 1.9, 4.7, 4.6, 4.1, 4. , 3.3, 3.8, 3.6, 3.7, 3.4, 4.5,
       2.6, 2.1, 4.8, 1.1, 3.9, 1.3, 1.5, 5. , 3.1, 2. , 4.4, 2.5, 4.2,
       2.4, 1.7, 3.2, 2.9, 4.9])

In [201]:
df_buses_up['Seats_Available'].unique()

array(['9 Seats available', '12 Seats available', '37 Seats available',
       '24 Seats available', '30 Seats available', '17 Seats available',
       '10 Seats available', '5 Seats available', '21 Seats available',
       '4 Seats available', '8 Seats available', '34 Seats available',
       '52 Seats available', '39 Seats available', '48 Seats available',
       '36 Seats available', '15 Seats available', '19 Seats available',
       '31 Seats available', '40 Seats available', '44 Seats available',
       '28 Seats available', '6 Seats available', '20 Seats available',
       '2 Seats available', '27 Seats available', '23 Seats available',
       '14 Seats available', '11 Seats available', '26 Seats available',
       '38 Seats available', '51 Seats available', '22 Seats available',
       '13 Seats available', '7 Seats available', '32 Seats available',
       '42 Seats available', '41 Seats available', '18 Seats available',
       '25 Seats available', '35 Seats available', '3 Seats available'],
      dtype=object)

In [202]:
df_buses_up['Seats_Available']=df_buses_up['Seats_Available'].fillna("not available")

In [203]:
import re

# Apply a transformation to the 'Seats_Available' column to extract the first numeric value from the string.
# If a numeric value is found, it converts it to an integer. If no numeric value is found, it assigns 0.
df_buses_up['Seats_Available'] = df_buses_up['Seats_Available'].apply(
    lambda x: int(re.findall(r'\d+', x)[0]) if re.findall(r'\d+', x) else 0
)

# Print the DataFrame to check the updated 'Seats_Available' values
print(df_buses_up)

                               Bus_name  \
0                               FlixBus
1                    RS YADAV SMART BUS
2                  New Khaira Transport
5                      Gola Bus Service
6                            PTC-SKYBUS
..                                  ...
177                      RSRTC - 195742
178                      Laxmi holidays
179  India Tours & Travels (GetBookCab)
182                    UPSRTC - BTR0023
183                  RS YADAV SMART BUS

                                  Bus_type Start_time  End_time  \
0                          AC Seater (2+2)   23:35:00  05:00:00
1    Bharat Benz A/C Seater /Sleeper (2+1)   21:40:00  04:45:00
2               A/C Seater / Sleeper (2+2)   21:00:00  03:30:00
5    Bharat Benz A/C Seater /Sleeper (2+1)   22:30:00  06:30:00
6            VE A/C Seater / Sleeper (2+1)   23:50:00  07:30:00
..                                     ...        ...       ...
177             A/C Seater / Sleeper (2+1)   23:59:00  06:30:00
178          Bharat Benz A/C Sleeper (2+1)   23:00:00  05:00:00
179             A/C Seater / Sleeper (2+2)   23:00:00  03:45:00
182             Ordinary Non AC Seater 2+3   19:00:00  01:17:00
183             A/C Seater / Sleeper (2+1)   22:45:00  05:55:00

    Total_duration    Price  Seats_Available  Ratings  \
0         05:25:00   427.68                9      4.3
1         07:05:00   799.00               12      3.5
2         06:30:00   500.00                9      1.9
5         08:00:00   699.00               37      4.7
6         07:40:00   700.00               24      4.7
..             ...      ...              ...      ...
177       06:31:00   664.00               34      1.7
178       06:00:00   665.00               20      4.6
179       04:45:00   391.00               39      4.5
182       06:17:00   283.00               52      3.3
183       07:10:00  1099.00               10      4.5

                                            Route_link  \
0    https://www.redbus.in/bus-tickets/delhi-to-bar...
1    https://www.redbus.in/bus-tickets/delhi-to-bar...
2    https://www.redbus.in/bus-tickets/delhi-to-bar...
5    https://www.redbus.in/bus-tickets/delhi-to-luc...
6    https://www.redbus.in/bus-tickets/delhi-to-luc...
..                                                 ...
177  https://www.redbus.in/bus-tickets/delhi-to-hal...
178  https://www.redbus.in/bus-tickets/delhi-to-hal...
179  https://www.redbus.in/bus-tickets/delhi-to-hal...
182  https://www.redbus.in/bus-tickets/allahabad-to...
183  https://www.redbus.in/bus-tickets/shahjahanpur...

                                Route_name
0        Delhi to Bareilly (Uttar Pradesh)
1        Delhi to Bareilly (Uttar Pradesh)
2        Delhi to Bareilly (Uttar Pradesh)
5                         Delhi to Lucknow
6                         Delhi to Lucknow
..                                     ...
177                      Delhi to Haldwani
178                      Delhi to Haldwani
179                      Delhi to Haldwani
182   Prayagraj(Uttar Pradesh) to Azamgarh
183  Shahjahanpur (Uttar Pradesh) to Delhi

[150 rows x 10 columns]

In [173]:
df_buses_up['Seats_Available'].unique()

array([ 9, 12, 37, 24, 30, 17, 10,  5, 21,  4,  8, 34, 52, 39, 48, 36, 15,
       19, 31, 40, 44, 28,  6, 20,  2, 27, 23, 14, 11, 26, 38, 51, 22, 13,
        7, 32, 42, 41, 18, 25, 35,  3])

In [174]:
missing_values=df_buses_up.isnull().sum()
missing_values

Bus_name           0
Bus_type           0
Start_time         0
End_time           0
Total_duration     0
Price              0
Seats_Available    0
Ratings            0
Route_link         0
Route_name         0
State              0
dtype: int64

In [10]:
df_buses_up.to_csv('df_cleaned_up.csv', index=False)

In [18]:
df_buses_up

,Bus_name,Bus_type,Start_time,End_time,Total_duration,Price,Seats_Available,Ratings,Route_link,Route_name,State
0,FlixBus,AC Seater (2+2),23:35:00,05:00:00,05:25:00,427.68,9,4.3,https://www.redbus.in/bus-tickets/delhi-to-bar...,Delhi to Bareilly (Uttar Pradesh),Uttar pradesh
1,RS YADAV SMART BUS,Bharat Benz A/C Seater /Sleeper (2+1),21:40:00,04:45:00,07:05:00,799.00,12,3.5,https://www.redbus.in/bus-tickets/delhi-to-bar...,Delhi to Bareilly (Uttar Pradesh),Uttar pradesh
2,New Khaira Transport,A/C Seater / Sleeper (2+2),21:00:00,03:30:00,06:30:00,500.00,9,1.9,https://www.redbus.in/bus-tickets/delhi-to-bar...,Delhi to Bareilly (Uttar Pradesh),Uttar pradesh
3,Gola Bus Service,Bharat Benz A/C Seater /Sleeper (2+1),22:30:00,06:30:00,08:00:00,699.00,37,4.7,https://www.redbus.in/bus-tickets/delhi-to-luc...,Delhi to Lucknow,Uttar pradesh
4,PTC-SKYBUS,VE A/C Seater / Sleeper (2+1),23:50:00,07:30:00,07:40:00,700.00,24,4.7,https://www.redbus.in/bus-tickets/delhi-to-luc...,Delhi to Lucknow,Uttar pradesh
...,...,...,...,...,...,...,...,...,...,...,...
145,RSRTC - 195742,A/C Seater / Sleeper (2+1),23:59:00,06:30:00,06:31:00,664.00,34,1.7,https://www.redbus.in/bus-tickets/delhi-to-hal...,Delhi to Haldwani,Uttar pradesh
146,Laxmi holidays,Bharat Benz A/C Sleeper (2+1),23:00:00,05:00:00,06:00:00,665.00,20,4.6,https://www.redbus.in/bus-tickets/delhi-to-hal...,Delhi to Haldwani,Uttar pradesh
147,India Tours & Travels (GetBookCab),A/C Seater / Sleeper (2+2),23:00:00,03:45:00,04:45:00,391.00,39,4.5,https://www.redbus.in/bus-tickets/delhi-to-hal...,Delhi to Haldwani,Uttar pradesh
148,UPSRTC - BTR0023,Ordinary Non AC Seater 2+3,19:00:00,01:17:00,06:17:00,283.00,52,3.3,https://www.redbus.in/bus-tickets/allahabad-to...,Prayagraj(Uttar Pradesh) to Azamgarh,Uttar pradesh
149,RS YADAV SMART BUS,A/C Seater / Sleeper (2+1),22:45:00,05:55:00,07:10:00,1099.00,10,4.5,https://www.redbus.in/bus-tickets/shahjahanpur...,Shahjahanpur (Uttar Pradesh) to Delhi,Uttar pradesh

**WEST BENGAL**

In [33]:
df_buses_wb

,Bus_name,Bus_type,Start_time,End_time,Total_duration,Price,Seats_Available,Ratings,Route_link,Route_name,State
0,Snemita Paribahan(Shinjini),A/C Seater (2+3),22:45:00,04:10:00,05:25:00,333,10,3.8,https://www.redbus.in/bus-tickets/digha-to-kol...,Digha to Kolkata,West bengal
1,City Express (Shinjini),AC Seater (2+3),22:45:00,04:10:00,05:25:00,333,8,3.3,https://www.redbus.in/bus-tickets/digha-to-kol...,Digha to Kolkata,West bengal
2,Satya Paribahan,A/C Seater (2+3),23:00:00,03:45:00,04:45:00,350,13,3.0,https://www.redbus.in/bus-tickets/digha-to-kol...,Digha to Kolkata,West bengal
3,The Joy Ride,A/C Seater / Sleeper (2+2),21:15:00,02:30:00,05:15:00,520,1,3.9,https://www.redbus.in/bus-tickets/digha-to-kol...,Digha to Kolkata,West bengal
4,Satya Paribahan,A/C Seater (2+3),23:30:00,03:40:00,04:10:00,350,20,1.8,https://www.redbus.in/bus-tickets/digha-to-kol...,Digha to Kolkata,West bengal
5,Snemita Paribahan (Shinjini),AC Seater (2+3),23:35:00,04:15:00,04:40:00,333,20,2.5,https://www.redbus.in/bus-tickets/digha-to-kol...,Digha to Kolkata,West bengal
6,Parameswar Travels,A/C Seater Push Back (2+3),21:00:00,03:00:00,06:00:00,340,13,1.6,https://www.redbus.in/bus-tickets/digha-to-kol...,Digha to Kolkata,West bengal
7,Ankita Paribahan,A/C Seater Push Back (2+3),23:30:00,05:10:00,05:40:00,315,29,3.7,https://www.redbus.in/bus-tickets/digha-to-kol...,Digha to Kolkata,West bengal
8,Snemita Paribahan,A/C Seater (2+3),23:30:00,04:00:00,04:30:00,378,45,2.1,https://www.redbus.in/bus-tickets/digha-to-kol...,Digha to Kolkata,West bengal
9,Arunita Paribahan,A/C Seater (2+3),23:35:00,04:30:00,04:55:00,333,21,1.7,https://www.redbus.in/bus-tickets/digha-to-kol...,Digha to Kolkata,West bengal
10,RAYAN,A/C Seater / Sleeper (2+1),20:00:00,01:20:00,05:20:00,500,41,2.3,https://www.redbus.in/bus-tickets/digha-to-kol...,Digha to Kolkata,West bengal
11,Shyamoli Paribahan Pvt Ltd,VE A/C Seater (2+2),23:30:00,04:30:00,05:00:00,300,29,4.5,https://www.redbus.in/bus-tickets/kolkata-to-d...,Kolkata to Digha,West bengal
12,Express Line,Volvo 9600 A/C Seater (2+2),23:45:00,04:45:00,05:00:00,349,31,4.3,https://www.redbus.in/bus-tickets/kolkata-to-d...,Kolkata to Digha,West bengal
13,Maa Chandi Travels,A/C Seater / Sleeper (2+2),22:00:00,05:30:00,07:30:00,400,40,4.2,https://www.redbus.in/bus-tickets/kolkata-to-d...,Kolkata to Digha,West bengal
14,Satya Paribahan,A/C Seater (2+3),23:40:00,03:45:00,04:05:00,350,14,3.1,https://www.redbus.in/bus-tickets/mandarmani-t...,Mandarmani to Kolkata,West bengal
15,City Express (Shinjini),AC Seater (2+3),23:15:00,04:10:00,04:55:00,333,13,2.9,https://www.redbus.in/bus-tickets/mandarmani-t...,Mandarmani to Kolkata,West bengal
16,Snemita Paribahan(Shinjini),A/C Seater (2+3),23:15:00,04:10:00,04:55:00,333,11,2.5,https://www.redbus.in/bus-tickets/mandarmani-t...,Mandarmani to Kolkata,West bengal
17,Snemita Paribahan (Shinjini),AC Seater (2+3),23:59:00,04:15:00,04:16:00,333,20,2.5,https://www.redbus.in/bus-tickets/mandarmani-t...,Mandarmani to Kolkata,West bengal
18,Shyamoli Paribahan Pvt Ltd,VE A/C Seater (2+2),23:30:00,03:45:00,04:15:00,300,29,4.7,https://www.redbus.in/bus-tickets/kolkata-to-m...,Kolkata to Mandarmani,West bengal
19,Express Line,Volvo 9600 A/C Seater (2+2),23:45:00,04:05:00,04:20:00,349,31,4.4,https://www.redbus.in/bus-tickets/kolkata-to-m...,Kolkata to Mandarmani,West bengal
20,Basu Travels,A/C Seater / Sleeper (2+2),23:59:00,04:00:00,04:01:00,319,30,4.5,https://www.redbus.in/bus-tickets/kolkata-to-m...,Kolkata to Mandarmani,West bengal
21,Maa Chandi Travels,A/C Seater / Sleeper (2+2),22:00:00,05:10:00,07:10:00,400,40,3.7,https://www.redbus.in/bus-tickets/kolkata-to-m...,Kolkata to Mandarmani,West bengal

In [209]:
df_buses_wb = df_buses_wb.dropna(subset=['Bus_name'])

In [210]:
df_buses_wb = df_buses_wb.dropna(subset=['Bus_type'])

In [211]:
# Clean the 'Start_time' column by removing extra spaces
df_buses_wb['Start_time'] = df_buses_wb['Start_time'].str.strip()

# Check if the cleaning helped
print(df_buses_wb['Start_time'].head())

0    22:45
1    22:45
2    23:00
3    21:15
4    23:30
Name: Start_time, dtype: object

In [212]:

df_buses_wb['Start_time'] = pd.to_datetime(df_buses_wb['Start_time'], format='%H:%M', errors='coerce')

df_buses_wb['Start_time'] = df_buses_wb['Start_time'].dt.strftime('%H:%M:%S')

print(df_buses_wb[['Start_time']])

   Start_time
0    22:45:00
1    22:45:00
2    23:00:00
3    21:15:00
4    23:30:00
5    23:35:00
6    21:00:00
7    23:30:00
8    23:30:00
9    23:35:00
10   20:00:00
11   23:30:00
12   23:45:00
13   22:00:00
16   23:40:00
17   23:15:00
18   23:15:00
19   23:59:00
21   23:30:00
22   23:45:00
23   23:59:00
24   22:00:00

In [213]:
# Clean the 'End_time' column by removing extra spaces
df_buses_wb['End_time'] = df_buses_wb['End_time'].str.strip()

# Check if the cleaning helped
print(df_buses_wb['End_time'].head())

0    04:10
1    04:10
2    03:45
3    02:30
4    03:40
Name: End_time, dtype: object

In [214]:
df_buses_wb['End_time'] = pd.to_datetime(df_buses_wb['End_time'], format='%H:%M', errors='coerce')
df_buses_wb['End_time'] =df_buses_wb['End_time'].dt.strftime('%H:%M:%S')
print(df_buses_wb[['End_time']])

    End_time
0   04:10:00
1   04:10:00
2   03:45:00
3   02:30:00
4   03:40:00
5   04:15:00
6   03:00:00
7   05:10:00
8   04:00:00
9   04:30:00
10  01:20:00
11  04:30:00
12  04:45:00
13  05:30:00
16  03:45:00
17  04:10:00
18  04:10:00
19  04:15:00
21  03:45:00
22  04:05:00
23  04:00:00
24  05:10:00

In [215]:
# Function to convert 'hh h mm m' format to 'hh:mm:ss' format
def convert_to_hms(duration):
    try:
        hours = 0
        minutes = 0
        seconds = 0
        
        # Check for hours and minutes in the string, extract the numeric values
        if 'h' in duration:
            hours = int(duration.split('h')[0].strip())  # Extract hours
            duration = duration.split('h')[1].strip()  # Remove hours part
        
        if 'm' in duration:
            minutes = int(duration.split('m')[0].strip())  # Extract minutes
            duration = duration.split('m')[1].strip()  # Remove minutes part
        
        # If there are remaining characters, assume it's seconds (in case there are seconds)
        if duration:
            seconds = int(duration.strip())  # Remaining part is seconds
        
        # Format to hh:mm:ss
        time_str = f'{hours:02}:{minutes:02}:{seconds:02}'
        return time_str
    except Exception as e:
        return "Invalid Format"

# Apply the conversion function to the 'Total_duration' column in place
df_buses_wb['Total_duration'] =df_buses_wb['Total_duration'].apply(convert_to_hms)

# Remove rows with 'Invalid Format' in the 'Total_duration' column without affecting other columns
df_buses_wb = df_buses_wb[df_buses_wb['Total_duration'] != 'Invalid Format']

# Check the DataFrame to ensure it's correct
print(df_buses_wb)

                        Bus_name                     Bus_type Start_time  \
0    Snemita Paribahan(Shinjini)             A/C Seater (2+3)   22:45:00
1        City Express (Shinjini)              AC Seater (2+3)   22:45:00
2                Satya Paribahan             A/C Seater (2+3)   23:00:00
3                   The Joy Ride   A/C Seater / Sleeper (2+2)   21:15:00
4                Satya Paribahan             A/C Seater (2+3)   23:30:00
5   Snemita Paribahan (Shinjini)              AC Seater (2+3)   23:35:00
6             Parameswar Travels   A/C Seater Push Back (2+3)   21:00:00
7               Ankita Paribahan   A/C Seater Push Back (2+3)   23:30:00
8              Snemita Paribahan             A/C Seater (2+3)   23:30:00
9              Arunita Paribahan             A/C Seater (2+3)   23:35:00
10                         RAYAN   A/C Seater / Sleeper (2+1)   20:00:00
11    Shyamoli Paribahan Pvt Ltd          VE A/C Seater (2+2)   23:30:00
12                  Express Line  Volvo 9600 A/C Seater (2+2)   23:45:00
13            Maa Chandi Travels   A/C Seater / Sleeper (2+2)   22:00:00
16               Satya Paribahan             A/C Seater (2+3)   23:40:00
17       City Express (Shinjini)              AC Seater (2+3)   23:15:00
18   Snemita Paribahan(Shinjini)             A/C Seater (2+3)   23:15:00
19  Snemita Paribahan (Shinjini)              AC Seater (2+3)   23:59:00
21    Shyamoli Paribahan Pvt Ltd          VE A/C Seater (2+2)   23:30:00
22                  Express Line  Volvo 9600 A/C Seater (2+2)   23:45:00
23                  Basu Travels   A/C Seater / Sleeper (2+2)   23:59:00
24            Maa Chandi Travels   A/C Seater / Sleeper (2+2)   22:00:00

    End_time Total_duration    Price     Seats_Available   Ratings  \
0   04:10:00       05:25:00      333  10 Seats available   3.8\n29
1   04:10:00       05:25:00      333   8 Seats available   3.3\n32
2   03:45:00       04:45:00  INR 350  13 Seats available   3.0\n31
3   02:30:00       05:15:00      520    1 Seat available    3.9\n5
4   03:40:00       04:10:00  INR 350  20 Seats available   1.8\n23
5   04:15:00       04:40:00      333  20 Seats available   2.5\n13
6   03:00:00       06:00:00      340  13 Seats available   1.6\n10
7   05:10:00       05:40:00      315  29 Seats available    3.7\n7
8   04:00:00       04:30:00      378  45 Seats available   2.1\n10
9   04:30:00       04:55:00      333  21 Seats available    1.7\n9
10  01:20:00       05:20:00  INR 500  41 Seats available       2.3
11  04:30:00       05:00:00  INR 300  29 Seats available  4.5\n340
12  04:45:00       05:00:00  INR 349  31 Seats available  4.3\n331
13  05:30:00       07:30:00  INR 400  40 Seats available  4.2\n237
16  03:45:00       04:05:00  INR 350  14 Seats available       3.1
17  04:10:00       04:55:00      333  13 Seats available       2.9
18  04:10:00       04:55:00      333  11 Seats available       2.5
19  04:15:00       04:16:00      333  20 Seats available       2.5
21  03:45:00       04:15:00  INR 300  29 Seats available   4.7\n66
22  04:05:00       04:20:00  INR 349  31 Seats available   4.4\n49
23  04:00:00       04:01:00      319  30 Seats available   4.5\n10
24  05:10:00       07:10:00  INR 400  40 Seats available   3.7\n22

                                           Route_link             Route_name
0   https://www.redbus.in/bus-tickets/digha-to-kol...       Digha to Kolkata
1   https://www.redbus.in/bus-tickets/digha-to-kol...       Digha to Kolkata
2   https://www.redbus.in/bus-tickets/digha-to-kol...       Digha to Kolkata
3   https://www.redbus.in/bus-tickets/digha-to-kol...       Digha to Kolkata
4   https://www.redbus.in/bus-tickets/digha-to-kol...       Digha to Kolkata
5   https://www.redbus.in/bus-tickets/digha-to-kol...       Digha to Kolkata
6   https://www.redbus.in/bus-tickets/digha-to-kol...       Digha to Kolkata
7   https://www.redbus.in/bus-tickets/digha-to-kol...       Digha to Kolkata
8   https://www.redbus.in/bus-tickets/digha-to-kol...       Digha to Kolkata
9   https://www.redbus.in/bus-tickets/digha-to-kol...       Digha to Kolkata
10  https://www.redbus.in/bus-tickets/digha-to-kol...       Digha to Kolkata
11  https://www.redbus.in/bus-tickets/kolkata-to-d...       Kolkata to Digha
12  https://www.redbus.in/bus-tickets/kolkata-to-d...       Kolkata to Digha
13  https://www.redbus.in/bus-tickets/kolkata-to-d...       Kolkata to Digha
16  https://www.redbus.in/bus-tickets/mandarmani-t...  Mandarmani to Kolkata
17  https://www.redbus.in/bus-tickets/mandarmani-t...  Mandarmani to Kolkata
18  https://www.redbus.in/bus-tickets/mandarmani-t...  Mandarmani to Kolkata
19  https://www.redbus.in/bus-tickets/mandarmani-t...  Mandarmani to Kolkata
21  https://www.redbus.in/bus-tickets/kolkata-to-m...  Kolkata to Mandarmani
22  https://www.redbus.in/bus-tickets/kolkata-to-m...  Kolkata to Mandarmani
23  https://www.redbus.in/bus-tickets/kolkata-to-m...  Kolkata to Mandarmani
24  https://www.redbus.in/bus-tickets/kolkata-to-m...  Kolkata to Mandarmani

In [216]:
df_buses_wb['Total_duration'].unique()

array(['05:25:00', '04:45:00', '05:15:00', '04:10:00', '04:40:00',
       '06:00:00', '05:40:00', '04:30:00', '04:55:00', '05:20:00',
       '05:00:00', '07:30:00', '04:05:00', '04:16:00', '04:15:00',
       '04:20:00', '04:01:00', '07:10:00'], dtype=object)

In [217]:
# Convert 'Price' column to string type before using .str methods
df_buses_wb["Price"] = df_buses_wb["Price"].astype(str)

In [218]:
#convert prices to numeric
df_buses_wb["Price"]=df_buses_wb["Price"].str.replace("INR","")
df_buses_wb["Price"]=df_buses_wb["Price"].astype(float)
df_buses_wb["Price"].fillna(0)

0     333.0
1     333.0
2     350.0
3     520.0
4     350.0
5     333.0
6     340.0
7     315.0
8     378.0
9     333.0
10    500.0
11    300.0
12    349.0
13    400.0
16    350.0
17    333.0
18    333.0
19    333.0
21    300.0
22    349.0
23    319.0
24    400.0
Name: Price, dtype: float64

In [219]:
# Convert price column to numeric, setting errors='coerce' to replace invalid values with NaN
df_buses_wb['Price'] = pd.to_numeric(df_buses_wb['Price'], errors='coerce')

# Replace NaN (missing values) in the price column with a default value or None (for NULL in MySQL)
df_buses_wb['Price'] = df_buses_wb['Price'].fillna(0)  # Replace NaN with 0, or use None for NULL

In [220]:
df_buses_wb['Price'].unique()

array([333., 350., 520., 340., 315., 378., 500., 300., 349., 400., 319.])

In [221]:
# Print rows where 'Price' is NaN
print(df_buses_wb[df_buses_wb['Price'].isnull()])

# Drop rows with NaN in 'Price'
df_buses_wb.dropna(subset=['Price'], inplace=True)

Empty DataFrame
Columns: [Bus_name, Bus_type, Start_time, End_time, Total_duration, Price, Seats_Available, Ratings, Route_link, Route_name]
Index: []

In [222]:
import numpy as np
import re

# Function to clean the Ratings column
def clean_rating(value):
    # If the value is one of the invalid ones, return NaN
    if str(value).lower() in ['nan', 'new', ' ', 'none']:
        return np.nan
    # Attempt to extract a numeric value from the string
    match = re.match(r'(\d+\.\d+)', str(value))
    if match:
        return float(match.group(1))
    # If no match is found, return NaN
    return np.nan

# Clean the Ratings column
df_buses_wb['Ratings'] =df_buses_wb['Ratings'].apply(clean_rating)

# Show the cleaned data
print(df_buses_wb[['Ratings']].head())

   Ratings
0      3.8
1      3.3
2      3.0
3      3.9
4      1.8

In [223]:
df_buses_wb['Ratings'] = df_buses_wb['Ratings'].fillna(0)

In [224]:
df_buses_wb = df_buses_wb.dropna(subset=['Ratings'])

In [225]:
df_buses_wb['Ratings'].unique()

array([3.8, 3.3, 3. , 3.9, 1.8, 2.5, 1.6, 3.7, 2.1, 1.7, 2.3, 4.5, 4.3,
       4.2, 3.1, 2.9, 4.7, 4.4])

In [226]:
df_buses_wb['Seats_Available'].unique()

array(['10 Seats available', '8 Seats available', '13 Seats available',
       '1 Seat available', '20 Seats available', '29 Seats available',
       '45 Seats available', '21 Seats available', '41 Seats available',
       '31 Seats available', '40 Seats available', '14 Seats available',
       '11 Seats available', '30 Seats available'], dtype=object)

In [227]:
df_buses_wb['Seats_Available']=df_buses_wb['Seats_Available'].fillna("not available")

In [228]:
import re
df_buses_wb['Seats_Available'] = df_buses_wb['Seats_Available'].apply(
    lambda x: int(re.findall(r'\d+', x)[0]) if re.findall(r'\d+', x) else 0
)

# Print the DataFrame to check the updated 'Seats_Available' values
print(df_buses_wb)

                        Bus_name                     Bus_type Start_time  \
0    Snemita Paribahan(Shinjini)             A/C Seater (2+3)   22:45:00
1        City Express (Shinjini)              AC Seater (2+3)   22:45:00
2                Satya Paribahan             A/C Seater (2+3)   23:00:00
3                   The Joy Ride   A/C Seater / Sleeper (2+2)   21:15:00
4                Satya Paribahan             A/C Seater (2+3)   23:30:00
5   Snemita Paribahan (Shinjini)              AC Seater (2+3)   23:35:00
6             Parameswar Travels   A/C Seater Push Back (2+3)   21:00:00
7               Ankita Paribahan   A/C Seater Push Back (2+3)   23:30:00
8              Snemita Paribahan             A/C Seater (2+3)   23:30:00
9              Arunita Paribahan             A/C Seater (2+3)   23:35:00
10                         RAYAN   A/C Seater / Sleeper (2+1)   20:00:00
11    Shyamoli Paribahan Pvt Ltd          VE A/C Seater (2+2)   23:30:00
12                  Express Line  Volvo 9600 A/C Seater (2+2)   23:45:00
13            Maa Chandi Travels   A/C Seater / Sleeper (2+2)   22:00:00
16               Satya Paribahan             A/C Seater (2+3)   23:40:00
17       City Express (Shinjini)              AC Seater (2+3)   23:15:00
18   Snemita Paribahan(Shinjini)             A/C Seater (2+3)   23:15:00
19  Snemita Paribahan (Shinjini)              AC Seater (2+3)   23:59:00
21    Shyamoli Paribahan Pvt Ltd          VE A/C Seater (2+2)   23:30:00
22                  Express Line  Volvo 9600 A/C Seater (2+2)   23:45:00
23                  Basu Travels   A/C Seater / Sleeper (2+2)   23:59:00
24            Maa Chandi Travels   A/C Seater / Sleeper (2+2)   22:00:00

    End_time Total_duration  Price  Seats_Available  Ratings  \
0   04:10:00       05:25:00  333.0               10      3.8
1   04:10:00       05:25:00  333.0                8      3.3
2   03:45:00       04:45:00  350.0               13      3.0
3   02:30:00       05:15:00  520.0                1      3.9
4   03:40:00       04:10:00  350.0               20      1.8
5   04:15:00       04:40:00  333.0               20      2.5
6   03:00:00       06:00:00  340.0               13      1.6
7   05:10:00       05:40:00  315.0               29      3.7
8   04:00:00       04:30:00  378.0               45      2.1
9   04:30:00       04:55:00  333.0               21      1.7
10  01:20:00       05:20:00  500.0               41      2.3
11  04:30:00       05:00:00  300.0               29      4.5
12  04:45:00       05:00:00  349.0               31      4.3
13  05:30:00       07:30:00  400.0               40      4.2
16  03:45:00       04:05:00  350.0               14      3.1
17  04:10:00       04:55:00  333.0               13      2.9
18  04:10:00       04:55:00  333.0               11      2.5
19  04:15:00       04:16:00  333.0               20      2.5
21  03:45:00       04:15:00  300.0               29      4.7
22  04:05:00       04:20:00  349.0               31      4.4
23  04:00:00       04:01:00  319.0               30      4.5
24  05:10:00       07:10:00  400.0               40      3.7

                                           Route_link             Route_name
0   https://www.redbus.in/bus-tickets/digha-to-kol...       Digha to Kolkata
1   https://www.redbus.in/bus-tickets/digha-to-kol...       Digha to Kolkata
2   https://www.redbus.in/bus-tickets/digha-to-kol...       Digha to Kolkata
3   https://www.redbus.in/bus-tickets/digha-to-kol...       Digha to Kolkata
4   https://www.redbus.in/bus-tickets/digha-to-kol...       Digha to Kolkata
5   https://www.redbus.in/bus-tickets/digha-to-kol...       Digha to Kolkata
6   https://www.redbus.in/bus-tickets/digha-to-kol...       Digha to Kolkata
7   https://www.redbus.in/bus-tickets/digha-to-kol...       Digha to Kolkata
8   https://www.redbus.in/bus-tickets/digha-to-kol...       Digha to Kolkata
9   https://www.redbus.in/bus-tickets/digha-to-kol...       Digha to Kolkata
10  https://www.redbus.in/bus-tickets/digha-to-kol...       Digha to Kolkata
11  https://www.redbus.in/bus-tickets/kolkata-to-d...       Kolkata to Digha
12  https://www.redbus.in/bus-tickets/kolkata-to-d...       Kolkata to Digha
13  https://www.redbus.in/bus-tickets/kolkata-to-d...       Kolkata to Digha
16  https://www.redbus.in/bus-tickets/mandarmani-t...  Mandarmani to Kolkata
17  https://www.redbus.in/bus-tickets/mandarmani-t...  Mandarmani to Kolkata
18  https://www.redbus.in/bus-tickets/mandarmani-t...  Mandarmani to Kolkata
19  https://www.redbus.in/bus-tickets/mandarmani-t...  Mandarmani to Kolkata
21  https://www.redbus.in/bus-tickets/kolkata-to-m...  Kolkata to Mandarmani
22  https://www.redbus.in/bus-tickets/kolkata-to-m...  Kolkata to Mandarmani
23  https://www.redbus.in/bus-tickets/kolkata-to-m...  Kolkata to Mandarmani
24  https://www.redbus.in/bus-tickets/kolkata-to-m...  Kolkata to Mandarmani

In [229]:
df_buses_wb['Seats_Available'].unique()

array([10,  8, 13,  1, 20, 29, 45, 21, 41, 31, 40, 14, 11, 30])

In [178]:
missing_values=df_buses_wb.isnull().sum()
missing_values

Bus_name           0
Bus_type           0
Start_time         0
End_time           0
Total_duration     0
Price              0
Seats_Available    0
Ratings            0
Route_link         0
Route_name         0
State              0
dtype: int64

In [11]:
df_buses_wb.to_csv('df_cleaned_wb.csv', index=False)

In [20]:
df_buses_wb

,Bus_name,Bus_type,Start_time,End_time,Total_duration,Price,Seats_Available,Ratings,Route_link,Route_name,State
0,Snemita Paribahan(Shinjini),A/C Seater (2+3),22:45:00,04:10:00,05:25:00,333,10,3.8,https://www.redbus.in/bus-tickets/digha-to-kol...,Digha to Kolkata,West bengal
1,City Express (Shinjini),AC Seater (2+3),22:45:00,04:10:00,05:25:00,333,8,3.3,https://www.redbus.in/bus-tickets/digha-to-kol...,Digha to Kolkata,West bengal
2,Satya Paribahan,A/C Seater (2+3),23:00:00,03:45:00,04:45:00,350,13,3.0,https://www.redbus.in/bus-tickets/digha-to-kol...,Digha to Kolkata,West bengal
3,The Joy Ride,A/C Seater / Sleeper (2+2),21:15:00,02:30:00,05:15:00,520,1,3.9,https://www.redbus.in/bus-tickets/digha-to-kol...,Digha to Kolkata,West bengal
4,Satya Paribahan,A/C Seater (2+3),23:30:00,03:40:00,04:10:00,350,20,1.8,https://www.redbus.in/bus-tickets/digha-to-kol...,Digha to Kolkata,West bengal
5,Snemita Paribahan (Shinjini),AC Seater (2+3),23:35:00,04:15:00,04:40:00,333,20,2.5,https://www.redbus.in/bus-tickets/digha-to-kol...,Digha to Kolkata,West bengal
6,Parameswar Travels,A/C Seater Push Back (2+3),21:00:00,03:00:00,06:00:00,340,13,1.6,https://www.redbus.in/bus-tickets/digha-to-kol...,Digha to Kolkata,West bengal
7,Ankita Paribahan,A/C Seater Push Back (2+3),23:30:00,05:10:00,05:40:00,315,29,3.7,https://www.redbus.in/bus-tickets/digha-to-kol...,Digha to Kolkata,West bengal
8,Snemita Paribahan,A/C Seater (2+3),23:30:00,04:00:00,04:30:00,378,45,2.1,https://www.redbus.in/bus-tickets/digha-to-kol...,Digha to Kolkata,West bengal
9,Arunita Paribahan,A/C Seater (2+3),23:35:00,04:30:00,04:55:00,333,21,1.7,https://www.redbus.in/bus-tickets/digha-to-kol...,Digha to Kolkata,West bengal
10,RAYAN,A/C Seater / Sleeper (2+1),20:00:00,01:20:00,05:20:00,500,41,2.3,https://www.redbus.in/bus-tickets/digha-to-kol...,Digha to Kolkata,West bengal
11,Shyamoli Paribahan Pvt Ltd,VE A/C Seater (2+2),23:30:00,04:30:00,05:00:00,300,29,4.5,https://www.redbus.in/bus-tickets/kolkata-to-d...,Kolkata to Digha,West bengal
12,Express Line,Volvo 9600 A/C Seater (2+2),23:45:00,04:45:00,05:00:00,349,31,4.3,https://www.redbus.in/bus-tickets/kolkata-to-d...,Kolkata to Digha,West bengal
13,Maa Chandi Travels,A/C Seater / Sleeper (2+2),22:00:00,05:30:00,07:30:00,400,40,4.2,https://www.redbus.in/bus-tickets/kolkata-to-d...,Kolkata to Digha,West bengal
14,Satya Paribahan,A/C Seater (2+3),23:40:00,03:45:00,04:05:00,350,14,3.1,https://www.redbus.in/bus-tickets/mandarmani-t...,Mandarmani to Kolkata,West bengal
15,City Express (Shinjini),AC Seater (2+3),23:15:00,04:10:00,04:55:00,333,13,2.9,https://www.redbus.in/bus-tickets/mandarmani-t...,Mandarmani to Kolkata,West bengal
16,Snemita Paribahan(Shinjini),A/C Seater (2+3),23:15:00,04:10:00,04:55:00,333,11,2.5,https://www.redbus.in/bus-tickets/mandarmani-t...,Mandarmani to Kolkata,West bengal
17,Snemita Paribahan (Shinjini),AC Seater (2+3),23:59:00,04:15:00,04:16:00,333,20,2.5,https://www.redbus.in/bus-tickets/mandarmani-t...,Mandarmani to Kolkata,West bengal
18,Shyamoli Paribahan Pvt Ltd,VE A/C Seater (2+2),23:30:00,03:45:00,04:15:00,300,29,4.7,https://www.redbus.in/bus-tickets/kolkata-to-m...,Kolkata to Mandarmani,West bengal
19,Express Line,Volvo 9600 A/C Seater (2+2),23:45:00,04:05:00,04:20:00,349,31,4.4,https://www.redbus.in/bus-tickets/kolkata-to-m...,Kolkata to Mandarmani,West bengal
20,Basu Travels,A/C Seater / Sleeper (2+2),23:59:00,04:00:00,04:01:00,319,30,4.5,https://www.redbus.in/bus-tickets/kolkata-to-m...,Kolkata to Mandarmani,West bengal
21,Maa Chandi Travels,A/C Seater / Sleeper (2+2),22:00:00,05:10:00,07:10:00,400,40,3.7,https://www.redbus.in/bus-tickets/kolkata-to-m...,Kolkata to Mandarmani,West bengal

**HIMACHAL**

In [36]:
df_buses_himachal

,Bus_name,Bus_type,Start_time,End_time,Total_duration,Price,Seats_Available,Ratings,Route_link,Route_name,State
0,Himachal Pradesh Tourism Development Corporati...,AC Seater (2+2),21:00:00,06:00:00,09:00:00,1000.0,31,4.6,https://www.redbus.in/bus-tickets/delhi-to-shimla,Delhi to Shimla,Himachal
1,Laxmi holidays,Volvo A/C Semi Sleeper (2+2),23:25:00,07:45:00,08:20:00,759.0,41,4.5,https://www.redbus.in/bus-tickets/delhi-to-shimla,Delhi to Shimla,Himachal
2,Ram Dalal Holidays,Mercedes Multi-Axle Semi Sleeper (2+2),23:30:00,07:40:00,08:10:00,760.0,19,4.5,https://www.redbus.in/bus-tickets/delhi-to-shimla,Delhi to Shimla,Himachal
3,Laxmi holidays,Volvo A/C Semi Sleeper (2+2),20:20:00,01:15:00,04:55:00,1899.0,6,3.3,https://www.redbus.in/bus-tickets/hamirpur-him...,Hamirpur (Himachal Pradesh) to Chandigarh,Himachal
4,Ram Dalal Holidays,Volvo A/C Semi Sleeper (2+2),21:15:00,01:20:00,04:05:00,1900.0,4,4.2,https://www.redbus.in/bus-tickets/hamirpur-him...,Hamirpur (Himachal Pradesh) to Chandigarh,Himachal
...,...,...,...,...,...,...,...,...,...,...,...
121,HRTC - 726,Ordinary 3+2 Non AC Seater,19:20:00,04:30:00,09:10:00,583.0,27,3.7,https://www.redbus.in/bus-tickets/manali-to-sh...,Manali to Shimla,Himachal
122,HRTC - 155,Himsuta AC Seater Volvo/Scania 2+2,21:00:00,06:10:00,09:10:00,963.0,15,3.8,https://www.redbus.in/bus-tickets/manali-to-sh...,Manali to Shimla,Himachal
123,HRTC - 718,Ordinary 3+2 Non AC Seater,21:30:00,06:35:00,09:05:00,583.0,31,3.3,https://www.redbus.in/bus-tickets/manali-to-sh...,Manali to Shimla,Himachal
124,HRTC - 6709,Ordinary 3+2 Non AC Seater,19:30:00,02:40:00,07:10:00,325.0,35,3.5,https://www.redbus.in/bus-tickets/baddi-himach...,Baddi (Himachal Pradesh) to Delhi,Himachal
125,HRTC - 6639,Himsuta AC Seater Volvo/Scania 2+2,20:45:00,03:30:00,06:45:00,612.0,29,3.8,https://www.redbus.in/bus-tickets/baddi-himach...,Baddi (Himachal Pradesh) to Delhi,Himachal

In [234]:
df_buses_himachal =df_buses_himachal.dropna(subset=['Bus_name'])

In [235]:
df_buses_himachal = df_buses_himachal.dropna(subset=['Bus_type'])

In [236]:
# Clean the 'Start_time' column by removing extra spaces
df_buses_himachal['Start_time'] = df_buses_himachal['Start_time'].str.strip()

# Check if the cleaning helped
print(df_buses_himachal['Start_time'].head())

0    21:00
1    23:25
2    23:30
5    20:20
6    21:15
Name: Start_time, dtype: object

In [237]:

df_buses_himachal['Start_time'] = pd.to_datetime(df_buses_himachal['Start_time'], format='%H:%M', errors='coerce')

df_buses_himachal['Start_time'] = df_buses_himachal['Start_time'].dt.strftime('%H:%M:%S')

print(df_buses_himachal[['Start_time']])

    Start_time
0     21:00:00
1     23:25:00
2     23:30:00
5     20:20:00
6     21:15:00
..         ...
158   19:20:00
159   21:00:00
160   21:30:00
161   19:30:00
162   20:45:00

[126 rows x 1 columns]

In [238]:
# Clean the 'End_time' column by removing extra spaces
df_buses_himachal['End_time'] =df_buses_himachal['End_time'].str.strip()

# Check if the cleaning helped
print(df_buses_himachal['End_time'].head())

0    06:00
1    07:45
2    07:40
5    01:15
6    01:20
Name: End_time, dtype: object

In [239]:
df_buses_himachal['End_time'] = pd.to_datetime(df_buses_himachal['End_time'], format='%H:%M', errors='coerce')
df_buses_himachal['End_time'] =df_buses_himachal['End_time'].dt.strftime('%H:%M:%S')
print(df_buses_himachal[['End_time']])

     End_time
0    06:00:00
1    07:45:00
2    07:40:00
5    01:15:00
6    01:20:00
..        ...
158  04:30:00
159  06:10:00
160  06:35:00
161  02:40:00
162  03:30:00

[126 rows x 1 columns]

In [240]:
# Function to convert 'hh h mm m' format to 'hh:mm:ss' format
def convert_to_hms(duration):
    try:
        hours = 0
        minutes = 0
        seconds = 0
        
        # Check for hours and minutes in the string, extract the numeric values
        if 'h' in duration:
            hours = int(duration.split('h')[0].strip())  # Extract hours
            duration = duration.split('h')[1].strip()  # Remove hours part
        
        if 'm' in duration:
            minutes = int(duration.split('m')[0].strip())  # Extract minutes
            duration = duration.split('m')[1].strip()  # Remove minutes part
        
        # If there are remaining characters, assume it's seconds (in case there are seconds)
        if duration:
            seconds = int(duration.strip())  # Remaining part is seconds
        
        # Format to hh:mm:ss
        time_str = f'{hours:02}:{minutes:02}:{seconds:02}'
        return time_str
    except Exception as e:
        return "Invalid Format"

# Apply the conversion function to the 'Total_duration' column in place
df_buses_himachal['Total_duration'] = df_buses_himachal['Total_duration'].apply(convert_to_hms)

# Remove rows with 'Invalid Format' in the 'Total_duration' column without affecting other columns
df_buses_himachal = df_buses_himachal[df_buses_himachal['Total_duration'] != 'Invalid Format']

# Check the DataFrame to ensure it's correct
print(df_buses_himachal)

                                              Bus_name  \
0    Himachal Pradesh Tourism Development Corporati...
1                                       Laxmi holidays
2                                   Ram Dalal Holidays
5                                       Laxmi holidays
6                                   Ram Dalal Holidays
..                                                 ...
158                                         HRTC - 726
159                                         HRTC - 155
160                                         HRTC - 718
161                                        HRTC - 6709
162                                        HRTC - 6639

                                   Bus_type Start_time  End_time  \
0                           AC Seater (2+2)   21:00:00  06:00:00
1              Volvo A/C Semi Sleeper (2+2)   23:25:00  07:45:00
2    Mercedes Multi-Axle Semi Sleeper (2+2)   23:30:00  07:40:00
5              Volvo A/C Semi Sleeper (2+2)   20:20:00  01:15:00
6              Volvo A/C Semi Sleeper (2+2)   21:15:00  01:20:00
..                                      ...        ...       ...
158              Ordinary 3+2 Non AC Seater   19:20:00  04:30:00
159      Himsuta AC Seater Volvo/Scania 2+2   21:00:00  06:10:00
160              Ordinary 3+2 Non AC Seater   21:30:00  06:35:00
161              Ordinary 3+2 Non AC Seater   19:30:00  02:40:00
162      Himsuta AC Seater Volvo/Scania 2+2   20:45:00  03:30:00

    Total_duration     Price     Seats_Available   Ratings  \
0         09:00:00  INR 1000  31 Seats available       4.6
1         08:20:00       759  41 Seats available  4.5\n648
2         08:10:00       760  19 Seats available  4.5\n584
5         04:55:00      1899   6 Seats available   3.3\n11
6         04:05:00      1900   4 Seats available   4.2\n15
..             ...       ...                 ...       ...
158       09:10:00   INR 583  27 Seats available    3.7\n4
159       09:10:00   INR 963  15 Seats available  3.8\n116
160       09:05:00   INR 583  31 Seats available    3.3\n9
161       07:10:00   INR 325  35 Seats available   3.5\n26
162       06:45:00   INR 612  29 Seats available  3.8\n148

                                            Route_link  \
0    https://www.redbus.in/bus-tickets/delhi-to-shimla
1    https://www.redbus.in/bus-tickets/delhi-to-shimla
2    https://www.redbus.in/bus-tickets/delhi-to-shimla
5    https://www.redbus.in/bus-tickets/hamirpur-him...
6    https://www.redbus.in/bus-tickets/hamirpur-him...
..                                                 ...
158  https://www.redbus.in/bus-tickets/manali-to-sh...
159  https://www.redbus.in/bus-tickets/manali-to-sh...
160  https://www.redbus.in/bus-tickets/manali-to-sh...
161  https://www.redbus.in/bus-tickets/baddi-himach...
162  https://www.redbus.in/bus-tickets/baddi-himach...

                                    Route_name
0                              Delhi to Shimla
1                              Delhi to Shimla
2                              Delhi to Shimla
5    Hamirpur (Himachal Pradesh) to Chandigarh
6    Hamirpur (Himachal Pradesh) to Chandigarh
..                                         ...
158                           Manali to Shimla
159                           Manali to Shimla
160                           Manali to Shimla
161          Baddi (Himachal Pradesh) to Delhi
162          Baddi (Himachal Pradesh) to Delhi

[126 rows x 10 columns]

In [241]:
df_buses_himachal['Total_duration'].unique()

array(['09:00:00', '08:20:00', '08:10:00', '04:55:00', '04:05:00',
       '03:45:00', '05:09:00', '03:50:00', '05:50:00', '04:50:00',
       '05:20:00', '09:30:00', '07:00:00', '08:40:00', '08:00:00',
       '09:10:00', '08:25:00', '08:35:00', '06:05:00', '04:20:00',
       '05:00:00', '11:50:00', '12:15:00', '11:55:00', '10:45:00',
       '10:40:00', '05:30:00', '06:00:00', '05:05:00', '06:40:00',
       '06:15:00', '05:45:00', '06:45:00', '05:40:00', '06:04:00',
       '07:16:00', '16:10:00', '15:15:00', '20:25:00', '07:30:00',
       '07:15:00', '04:45:00', '03:15:00', '02:40:00', '05:15:00',
       '06:01:00', '02:01:00', '02:50:00', '17:30:00', '16:15:00',
       '06:29:00', '07:35:00', '05:25:00', '06:31:00', '07:45:00',
       '10:30:00', '06:10:00', '08:45:00', '07:40:00', '08:05:00',
       '09:05:00', '07:33:00', '08:13:00', '06:30:00', '07:20:00',
       '02:30:00', '02:15:00', '09:45:00', '09:20:00', '11:00:00',
       '11:15:00', '08:56:00', '11:20:00', '10:55:00', '10:05:00',
       '07:10:00', '10:10:00'], dtype=object)

In [242]:
# Convert 'Price' column to string type before using .str methods
df_buses_himachal["Price"] =df_buses_himachal["Price"].astype(str)

In [243]:
#convert prices to numeric
df_buses_himachal["Price"]=df_buses_himachal["Price"].str.replace("INR","")
df_buses_himachal["Price"]=df_buses_himachal["Price"].astype(float)
df_buses_himachal["Price"].fillna(0)

0      1000.0
1       759.0
2       760.0
5      1899.0
6      1900.0
        ...
158     583.0
159     963.0
160     583.0
161     325.0
162     612.0
Name: Price, Length: 126, dtype: float64

In [244]:
# Convert price column to numeric, setting errors='coerce' to replace invalid values with NaN
df_buses_himachal['Price'] = pd.to_numeric(df_buses_himachal['Price'], errors='coerce')

# Replace NaN (missing values) in the price column with a default value or None (for NULL in MySQL)
df_buses_himachal['Price'] =df_buses_himachal['Price'].fillna(0)  # Replace NaN with 0, or use None for NULL

In [245]:
df_buses_himachal['Price'].unique()

array([1000.  ,  759.  ,  760.  , 1899.  , 1900.  , 1530.  ,  364.  ,
        340.  ,  302.  ,  334.  ,  399.  , 1117.  , 1620.  , 1572.  ,
       1994.  , 1479.  ,  618.  ,  569.  , 1203.57, 1804.  , 1757.  ,
       1908.  ,  661.  ,  637.  ,  692.  ,  320.  ,  549.  ,  434.  ,
       2000.  , 1304.  ,  854.  ,  664.  ,  876.  , 1062.  , 1704.  ,
        907.  ,  499.  ,  347.  ,  657.  ,  432.  ,  227.  , 1880.  ,
       1800.  ,  570.48,  438.  ,  475.  , 1537.  , 1424.  ,  450.  ,
        580.  ,  685.  ,  583.  ,  641.  ,  963.  ,  452.  ,  545.  ,
        495.  ,  818.  ,  488.  ,  403.  ,  409.  ,  925.  , 1410.  ,
       1769.  , 1709.  ,  690.  , 1128.  ,  990.  , 1080.  ,  341.  ,
        354.  ,  335.  ,  328.  ,  357.  , 1490.  , 2223.  , 1599.  ,
       2184.  , 1758.  ,  570.  ,  600.  ,  736.  , 1148.  , 2014.  ,
        325.  ,  612.  ])

In [246]:
# Print rows where 'Price' is NaN
print(df_buses_himachal[df_buses_himachal['Price'].isnull()])

# Drop rows with NaN in 'Price'
df_buses_himachal.dropna(subset=['Price'], inplace=True)

Empty DataFrame
Columns: [Bus_name, Bus_type, Start_time, End_time, Total_duration, Price, Seats_Available, Ratings, Route_link, Route_name]
Index: []

In [247]:
import numpy as np
import re

# Function to clean the Ratings column
def clean_rating(value):
    # If the value is one of the invalid ones, return NaN
    if str(value).lower() in ['nan', 'new', ' ', 'none']:
        return np.nan
    # Attempt to extract a numeric value from the string
    match = re.match(r'(\d+\.\d+)', str(value))
    if match:
        return float(match.group(1))
    # If no match is found, return NaN
    return np.nan

# Clean the Ratings column
df_buses_himachal['Ratings'] = df_buses_himachal['Ratings'].apply(clean_rating)

# Show the cleaned data
print(df_buses_himachal[['Ratings']].head())

   Ratings
0      4.6
1      4.5
2      4.5
5      3.3
6      4.2

In [248]:
df_buses_himachal['Ratings'] = df_buses_himachal['Ratings'].fillna(0)

In [249]:
df_buses_himachal = df_buses_himachal.dropna(subset=['Ratings'])

In [250]:
df_buses_himachal['Ratings'].unique()

array([4.6, 4.5, 3.3, 4.2, 3. , 4.1, 3.9, 2.5, 4.7, 2.6, 4. , 4.8, 4.4,
       3.5, 3.2, 2.7, 3.6, 3.8, 3.7, 1.9, 2.2, 3.1, 4.9, 2.9, 2.3, 2. ,
       4.3])

In [251]:
df_buses_himachal['Seats_Available'].unique()

array(['31 Seats available', '41 Seats available', '19 Seats available',
       '6 Seats available', '4 Seats available', '37 Seats available',
       '27 Seats available', '44 Seats available', '11 Seats available',
       '18 Seats available', '5 Seats available', '2 Seats available',
       '34 Seats available', '24 Seats available', '1 Seat available',
       '23 Seats available', '42 Seats available', '17 Seats available',
       '7 Seats available', '10 Seats available', '20 Seats available',
       '22 Seats available', '21 Seats available', '29 Seats available',
       '28 Seats available', '30 Seats available', '13 Seats available',
       '32 Seats available', '33 Seats available', '15 Seats available',
       '9 Seats available', '16 Seats available', '12 Seats available',
       '35 Seats available', '14 Seats available', '36 Seats available',
       '39 Seats available', '26 Seats available'], dtype=object)

In [252]:
df_buses_himachal['Seats_Available']=df_buses_himachal['Seats_Available'].fillna("not available")

In [253]:
import re
# Apply a transformation to the 'Seats_Available' column to extract the first numeric value from the string.
# If a numeric value is found, it converts it to an integer. If no numeric value is found, it assigns 0.

df_buses_himachal['Seats_Available'] = df_buses_himachal['Seats_Available'].apply(
    lambda x: int(re.findall(r'\d+', x)[0]) if re.findall(r'\d+', x) else 0
)

# Print the DataFrame to check the updated 'Seats_Available' values
print(df_buses_himachal)

                                              Bus_name  \
0    Himachal Pradesh Tourism Development Corporati...
1                                       Laxmi holidays
2                                   Ram Dalal Holidays
5                                       Laxmi holidays
6                                   Ram Dalal Holidays
..                                                 ...
158                                         HRTC - 726
159                                         HRTC - 155
160                                         HRTC - 718
161                                        HRTC - 6709
162                                        HRTC - 6639

                                   Bus_type Start_time  End_time  \
0                           AC Seater (2+2)   21:00:00  06:00:00
1              Volvo A/C Semi Sleeper (2+2)   23:25:00  07:45:00
2    Mercedes Multi-Axle Semi Sleeper (2+2)   23:30:00  07:40:00
5              Volvo A/C Semi Sleeper (2+2)   20:20:00  01:15:00
6              Volvo A/C Semi Sleeper (2+2)   21:15:00  01:20:00
..                                      ...        ...       ...
158              Ordinary 3+2 Non AC Seater   19:20:00  04:30:00
159      Himsuta AC Seater Volvo/Scania 2+2   21:00:00  06:10:00
160              Ordinary 3+2 Non AC Seater   21:30:00  06:35:00
161              Ordinary 3+2 Non AC Seater   19:30:00  02:40:00
162      Himsuta AC Seater Volvo/Scania 2+2   20:45:00  03:30:00

    Total_duration   Price  Seats_Available  Ratings  \
0         09:00:00  1000.0               31      4.6
1         08:20:00   759.0               41      4.5
2         08:10:00   760.0               19      4.5
5         04:55:00  1899.0                6      3.3
6         04:05:00  1900.0                4      4.2
..             ...     ...              ...      ...
158       09:10:00   583.0               27      3.7
159       09:10:00   963.0               15      3.8
160       09:05:00   583.0               31      3.3
161       07:10:00   325.0               35      3.5
162       06:45:00   612.0               29      3.8

                                            Route_link  \
0    https://www.redbus.in/bus-tickets/delhi-to-shimla
1    https://www.redbus.in/bus-tickets/delhi-to-shimla
2    https://www.redbus.in/bus-tickets/delhi-to-shimla
5    https://www.redbus.in/bus-tickets/hamirpur-him...
6    https://www.redbus.in/bus-tickets/hamirpur-him...
..                                                 ...
158  https://www.redbus.in/bus-tickets/manali-to-sh...
159  https://www.redbus.in/bus-tickets/manali-to-sh...
160  https://www.redbus.in/bus-tickets/manali-to-sh...
161  https://www.redbus.in/bus-tickets/baddi-himach...
162  https://www.redbus.in/bus-tickets/baddi-himach...

                                    Route_name
0                              Delhi to Shimla
1                              Delhi to Shimla
2                              Delhi to Shimla
5    Hamirpur (Himachal Pradesh) to Chandigarh
6    Hamirpur (Himachal Pradesh) to Chandigarh
..                                         ...
158                           Manali to Shimla
159                           Manali to Shimla
160                           Manali to Shimla
161          Baddi (Himachal Pradesh) to Delhi
162          Baddi (Himachal Pradesh) to Delhi

[126 rows x 10 columns]

In [254]:
df_buses_himachal['Seats_Available'].unique()

array([31, 41, 19,  6,  4, 37, 27, 44, 11, 18,  5,  2, 34, 24,  1, 23, 42,
       17,  7, 10, 20, 22, 21, 29, 28, 30, 13, 32, 33, 15,  9, 16, 12, 35,
       14, 36, 39, 26])

In [182]:
missing_values=df_buses_himachal.isnull().sum()
missing_values

Bus_name           0
Bus_type           0
Start_time         0
End_time           0
Total_duration     0
Price              0
Seats_Available    0
Ratings            0
Route_link         0
Route_name         0
State              0
dtype: int64

In [12]:
df_buses_himachal.to_csv('df_cleaned_himachal.csv', index=False)

In [22]:
df_buses_himachal

,Bus_name,Bus_type,Start_time,End_time,Total_duration,Price,Seats_Available,Ratings,Route_link,Route_name,State
0,Himachal Pradesh Tourism Development Corporati...,AC Seater (2+2),21:00:00,06:00:00,09:00:00,1000.0,31,4.6,https://www.redbus.in/bus-tickets/delhi-to-shimla,Delhi to Shimla,Himachal
1,Laxmi holidays,Volvo A/C Semi Sleeper (2+2),23:25:00,07:45:00,08:20:00,759.0,41,4.5,https://www.redbus.in/bus-tickets/delhi-to-shimla,Delhi to Shimla,Himachal
2,Ram Dalal Holidays,Mercedes Multi-Axle Semi Sleeper (2+2),23:30:00,07:40:00,08:10:00,760.0,19,4.5,https://www.redbus.in/bus-tickets/delhi-to-shimla,Delhi to Shimla,Himachal
3,Laxmi holidays,Volvo A/C Semi Sleeper (2+2),20:20:00,01:15:00,04:55:00,1899.0,6,3.3,https://www.redbus.in/bus-tickets/hamirpur-him...,Hamirpur (Himachal Pradesh) to Chandigarh,Himachal
4,Ram Dalal Holidays,Volvo A/C Semi Sleeper (2+2),21:15:00,01:20:00,04:05:00,1900.0,4,4.2,https://www.redbus.in/bus-tickets/hamirpur-him...,Hamirpur (Himachal Pradesh) to Chandigarh,Himachal
...,...,...,...,...,...,...,...,...,...,...,...
121,HRTC - 726,Ordinary 3+2 Non AC Seater,19:20:00,04:30:00,09:10:00,583.0,27,3.7,https://www.redbus.in/bus-tickets/manali-to-sh...,Manali to Shimla,Himachal
122,HRTC - 155,Himsuta AC Seater Volvo/Scania 2+2,21:00:00,06:10:00,09:10:00,963.0,15,3.8,https://www.redbus.in/bus-tickets/manali-to-sh...,Manali to Shimla,Himachal
123,HRTC - 718,Ordinary 3+2 Non AC Seater,21:30:00,06:35:00,09:05:00,583.0,31,3.3,https://www.redbus.in/bus-tickets/manali-to-sh...,Manali to Shimla,Himachal
124,HRTC - 6709,Ordinary 3+2 Non AC Seater,19:30:00,02:40:00,07:10:00,325.0,35,3.5,https://www.redbus.in/bus-tickets/baddi-himach...,Baddi (Himachal Pradesh) to Delhi,Himachal
125,HRTC - 6639,Himsuta AC Seater Volvo/Scania 2+2,20:45:00,03:30:00,06:45:00,612.0,29,3.8,https://www.redbus.in/bus-tickets/baddi-himach...,Baddi (Himachal Pradesh) to Delhi,Himachal

**DATA CLEANING**

In [13]:
import pandas as pd

# List of cleaned CSV file paths
cleaned_files = [
    "db_cleaned_goa.csv",
    "df_cleaned_rajasthan.csv",
    "df_cleaned_telangana.csv",
    "df_cleaned_kerala.csv",
    "df_cleaned_AS.csv",
    "df_cleaned_bengal.csv",
    "df_cleaned_andhra.csv",
    "df_cleaned_up.csv",
    "df_cleaned_wb.csv",
    "df_cleaned_himachal.csv"
]

# Read and concatenate all cleaned DataFrames
df_combined = pd.concat([pd.read_csv(file) for file in cleaned_files], ignore_index=True)

# Combine the last two columns into a single column called 'States'
df_combined['States'] = df_combined.iloc[:, -2].astype(str) + " " + df_combined.iloc[:, -1].astype(str)



# Display the first few rows of the combined DataFrame
print(df_combined.head())

                                            Bus_name  \
0                                      Atmaram Gobus
1                                      Atmaram Gobus
2                                  IntrCity SmartBus
3                                    Ashray Amrutyog
4  Kadamba Transport Corporation Limited (KTCL) -...

                                Bus_type Start_time  End_time Total_duration  \
0                   VE A/C Sleeper (2+1)   21:00:00  07:30:00       04:30:00
1                   VE A/C Sleeper (2+1)   22:30:00  08:45:00       07:15:00
2  Bharat Benz A/C Seater /Sleeper (2+1)   21:15:00  08:05:00       05:20:00
3                      A/C Sleeper (2+1)   22:05:00  09:30:00       07:35:00
4                      Non AC Seater 2+2   18:00:00  08:00:00       02:00:00

    Price  Seats_Available  Ratings  \
0  1450.0                6      4.7
1  1499.0                3      4.6
2  1419.0               19      4.5
3  1599.0               17      4.4
4   600.0               26      4.0

                                      Route_link   Route_name State State   \
0  https://www.redbus.in/bus-tickets/pune-to-goa  Pune to Goa   Goa    NaN
1  https://www.redbus.in/bus-tickets/pune-to-goa  Pune to Goa   Goa    NaN
2  https://www.redbus.in/bus-tickets/pune-to-goa  Pune to Goa   Goa    NaN
3  https://www.redbus.in/bus-tickets/pune-to-goa  Pune to Goa   Goa    NaN
4  https://www.redbus.in/bus-tickets/goa-to-pune  Goa to Pune   Goa    NaN

    States
0  Goa nan
1  Goa nan
2  Goa nan
3  Goa nan
4  Goa nan

In [14]:
df_combined

,Bus_name,Bus_type,Start_time,End_time,Total_duration,Price,Seats_Available,Ratings,Route_link,Route_name,State,State,States
0,Atmaram Gobus,VE A/C Sleeper (2+1),21:00:00,07:30:00,04:30:00,1450.0,6,4.7,https://www.redbus.in/bus-tickets/pune-to-goa,Pune to Goa,Goa,NaN,Goa nan
1,Atmaram Gobus,VE A/C Sleeper (2+1),22:30:00,08:45:00,07:15:00,1499.0,3,4.6,https://www.redbus.in/bus-tickets/pune-to-goa,Pune to Goa,Goa,NaN,Goa nan
2,IntrCity SmartBus,Bharat Benz A/C Seater /Sleeper (2+1),21:15:00,08:05:00,05:20:00,1419.0,19,4.5,https://www.redbus.in/bus-tickets/pune-to-goa,Pune to Goa,Goa,NaN,Goa nan
3,Ashray Amrutyog,A/C Sleeper (2+1),22:05:00,09:30:00,07:35:00,1599.0,17,4.4,https://www.redbus.in/bus-tickets/pune-to-goa,Pune to Goa,Goa,NaN,Goa nan
4,Kadamba Transport Corporation Limited (KTCL) -...,Non AC Seater 2+2,18:00:00,08:00:00,02:00:00,600.0,26,4.0,https://www.redbus.in/bus-tickets/goa-to-pune,Goa to Pune,Goa,NaN,Goa nan
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1119,HRTC - 726,Ordinary 3+2 Non AC Seater,19:20:00,04:30:00,09:10:00,583.0,27,3.7,https://www.redbus.in/bus-tickets/manali-to-sh...,Manali to Shimla,Himachal,NaN,Himachal nan
1120,HRTC - 155,Himsuta AC Seater Volvo/Scania 2+2,21:00:00,06:10:00,09:10:00,963.0,15,3.8,https://www.redbus.in/bus-tickets/manali-to-sh...,Manali to Shimla,Himachal,NaN,Himachal nan
1121,HRTC - 718,Ordinary 3+2 Non AC Seater,21:30:00,06:35:00,09:05:00,583.0,31,3.3,https://www.redbus.in/bus-tickets/manali-to-sh...,Manali to Shimla,Himachal,NaN,Himachal nan
1122,HRTC - 6709,Ordinary 3+2 Non AC Seater,19:30:00,02:40:00,07:10:00,325.0,35,3.5,https://www.redbus.in/bus-tickets/baddi-himach...,Baddi (Himachal Pradesh) to Delhi,Himachal,NaN,Himachal nan
1123,HRTC - 6639,Himsuta AC Seater Volvo/Scania 2+2,20:45:00,03:30:00,06:45:00,612.0,29,3.8,https://www.redbus.in/bus-tickets/baddi-himach...,Baddi (Himachal Pradesh) to Delhi,Himachal,NaN,Himachal nan

In [15]:
# Drop the second-to-last and third-to-last columns
df_combined = df_combined.drop(df_combined.columns[-3:-1], axis=1)

# Display the resulting DataFrame
df_combined

,Bus_name,Bus_type,Start_time,End_time,Total_duration,Price,Seats_Available,Ratings,Route_link,Route_name,States
0,Atmaram Gobus,VE A/C Sleeper (2+1),21:00:00,07:30:00,04:30:00,1450.0,6,4.7,https://www.redbus.in/bus-tickets/pune-to-goa,Pune to Goa,Goa nan
1,Atmaram Gobus,VE A/C Sleeper (2+1),22:30:00,08:45:00,07:15:00,1499.0,3,4.6,https://www.redbus.in/bus-tickets/pune-to-goa,Pune to Goa,Goa nan
2,IntrCity SmartBus,Bharat Benz A/C Seater /Sleeper (2+1),21:15:00,08:05:00,05:20:00,1419.0,19,4.5,https://www.redbus.in/bus-tickets/pune-to-goa,Pune to Goa,Goa nan
3,Ashray Amrutyog,A/C Sleeper (2+1),22:05:00,09:30:00,07:35:00,1599.0,17,4.4,https://www.redbus.in/bus-tickets/pune-to-goa,Pune to Goa,Goa nan
4,Kadamba Transport Corporation Limited (KTCL) -...,Non AC Seater 2+2,18:00:00,08:00:00,02:00:00,600.0,26,4.0,https://www.redbus.in/bus-tickets/goa-to-pune,Goa to Pune,Goa nan
...,...,...,...,...,...,...,...,...,...,...,...
1119,HRTC - 726,Ordinary 3+2 Non AC Seater,19:20:00,04:30:00,09:10:00,583.0,27,3.7,https://www.redbus.in/bus-tickets/manali-to-sh...,Manali to Shimla,Himachal nan
1120,HRTC - 155,Himsuta AC Seater Volvo/Scania 2+2,21:00:00,06:10:00,09:10:00,963.0,15,3.8,https://www.redbus.in/bus-tickets/manali-to-sh...,Manali to Shimla,Himachal nan
1121,HRTC - 718,Ordinary 3+2 Non AC Seater,21:30:00,06:35:00,09:05:00,583.0,31,3.3,https://www.redbus.in/bus-tickets/manali-to-sh...,Manali to Shimla,Himachal nan
1122,HRTC - 6709,Ordinary 3+2 Non AC Seater,19:30:00,02:40:00,07:10:00,325.0,35,3.5,https://www.redbus.in/bus-tickets/baddi-himach...,Baddi (Himachal Pradesh) to Delhi,Himachal nan
1123,HRTC - 6639,Himsuta AC Seater Volvo/Scania 2+2,20:45:00,03:30:00,06:45:00,612.0,29,3.8,https://www.redbus.in/bus-tickets/baddi-himach...,Baddi (Himachal Pradesh) to Delhi,Himachal nan

In [16]:
df_combined['States'].unique()

array(['Goa nan', 'Rajasthan nan', 'Telangana nan', 'nan Kerala',
       'nan Assam', 'South bengal nan', 'Andhra nan', 'Uttar pradesh nan',
       'West bengal nan', 'Himachal nan'], dtype=object)

In [17]:
# Replace 'nan' with an empty string in the 'States' column
df_combined['States'] = df_combined['States'].str.replace('nan', '', regex=False)

# Display the unique values after cleaning
print(df_combined['States'].unique())

['Goa ' 'Rajasthan ' 'Telangana ' ' Kerala' ' Assam' 'South bengal '
 'Andhra ' 'Uttar pradesh ' 'West bengal ' 'Himachal ']

In [18]:
df_combined["Price"].unique()

array([ 1450.  ,  1499.  ,  1419.  ,  1599.  ,   600.  ,  1099.  ,
         900.  ,  1119.  ,  2193.  ,  1782.  ,  1945.  ,  1400.  ,
        1722.  ,  1200.  ,  1000.  ,  1188.  ,   170.  ,  7200.  ,
        1799.  ,  1496.  ,  1899.  ,  2699.  ,  2799.  ,  2370.  ,
         800.  ,   999.  ,   879.  ,   809.  ,   950.  ,  1100.  ,
         650.  ,   449.  ,   350.  ,   450.  ,   499.  ,   850.  ,
        1850.  ,   700.  ,   735.  ,   949.  ,  1550.  ,  1044.  ,
         899.  ,   978.  ,   200.  ,   675.  ,  3000.  ,  1139.  ,
         140.  ,   150.  ,   490.  ,   505.  ,   699.  ,   400.  ,
        1699.  ,  2080.  ,  1600.  ,   550.  ,   990.  ,  1399.  ,
       11000.  ,   100.  ,   330.  ,   500.  ,   495.  ,   300.  ,
         485.  ,   510.  ,   270.  ,   315.  ,   349.  ,   308.  ,
         333.  ,   280.  ,   299.  ,   397.  ,   446.  ,   619.  ,
         523.  ,   408.  ,   459.  ,   206.  ,   549.  ,   739.  ,
         289.  ,   720.  ,   267.  ,   571.  ,   612.  ,   489.  ,
         639.  ,   590.  ,   777.  ,   610.  ,   670.  ,   555.  ,
         524.  ,   442.  ,  1129.  ,  2000.  ,   629.  ,  1080.  ,
         780.  ,  1036.  ,   799.  ,  1289.  ,  1409.  ,   989.  ,
        1990.  ,   711.  ,   749.  ,   738.  ,   810.  ,   750.  ,
        2100.  ,   392.  ,   464.  ,   689.  ,   580.  ,   891.  ,
        1624.  ,   789.  ,  1479.  ,   893.  ,  1090.  ,   660.  ,
         751.  ,   332.  ,  2429.  ,   647.  ,   878.  ,   730.  ,
         599.  ,   667.  ,   680.  ,   832.  ,  1169.  ,  1300.  ,
        1500.  ,  1149.  ,  1387.  ,   649.  ,  1299.  ,  1590.  ,
        1999.  ,  1055.  ,  1494.  ,  1548.  ,  1349.  ,   880.  ,
        1270.  ,  1199.  ,  1143.  ,  1350.  ,  1250.  ,  1155.  ,
        1202.  ,  1549.  ,   795.  ,   488.78,   425.  ,   375.  ,
         570.  ,   585.  ,   540.  ,   630.  ,   620.  ,   535.  ,
         439.  ,   415.  ,   595.  ,   465.  ,   451.  ,   475.  ,
         135.  ,   486.  ,   429.  ,   110.  ,   167.  ,   185.  ,
         121.  ,    95.  ,   145.  ,   250.  ,   285.  ,   430.  ,
         130.  ,   190.  ,   142.  ,   160.  ,   134.  ,   238.  ,
         246.  ,    80.  ,    78.  ,   233.  ,   319.  ,   288.  ,
          65.  ,    64.  ,    68.  ,   155.  ,   147.  ,    96.  ,
         108.  ,   163.  ,   520.  ,   115.  ,   271.  ,   303.  ,
         312.  ,    88.  ,   335.  ,   139.  ,    75.  ,   896.  ,
        1210.  ,  2530.  ,  2350.  ,   929.  ,  1069.  ,   830.  ,
        5000.  ,   454.  ,   399.  ,   394.  ,   370.  ,   521.  ,
         807.  ,  1013.  ,  1160.  ,  1050.  ,   824.  ,   431.  ,
        1320.  ,  1049.  ,   666.  ,   790.  ,  3999.  ,   560.  ,
         994.  ,   844.  ,   792.  ,   422.  ,   398.  ,  1329.  ,
         979.  ,   980.  ,  1401.79,   784.  ,  1079.  ,   478.  ,
         709.  ,   690.  ,  4000.  ,   356.25,   802.  ,   569.  ,
        1919.  ,  1425.  ,  1673.  ,   970.  ,   362.  ,   506.  ,
        1220.  ,   373.  ,   930.  ,  2099.  ,   427.68,   740.  ,
         463.  ,   224.  ,   708.  ,   435.  ,   503.  ,  1039.  ,
        1109.  ,   959.  ,   719.  ,   361.  ,   664.  ,   705.  ,
         998.  ,   359.  ,   504.  ,   529.  ,   849.  ,   924.  ,
         284.  ,   409.  ,   452.  ,  1019.  ,   939.  ,   414.  ,
         534.  ,  1490.  ,   379.  ,   368.  ,   375.1 ,   360.  ,
         321.  ,   212.5 ,  1860.  ,  1020.  ,   864.  ,   355.  ,
         665.  ,   391.  ,   283.  ,   340.  ,   378.  ,   759.  ,
         760.  ,  1900.  ,  1530.  ,   364.  ,   302.  ,   334.  ,
        1117.  ,  1620.  ,  1572.  ,  1994.  ,   618.  ,  1203.57,
        1804.  ,  1757.  ,  1908.  ,   661.  ,   637.  ,   692.  ,
         320.  ,   434.  ,  1304.  ,   854.  ,   876.  ,  1062.  ,
        1704.  ,   907.  ,   347.  ,   657.  ,   432.  ,   227.  ,
        1880.  ,  1800.  ,   570.48,   438.  ,  1537.  ,  1424.  ,
         685.  ,   583.  ,   641.  ,   963.  ,   545.  ,   818.  ,
         488.  ,   403.  ,   925.  ,  1410.  ,  1769.  ,  1709.  ,
        1128.  ,   341.  ,   354.  ,   328.  ,   357.  ,  2223.  ,
        2184.  ,  1758.  ,   736.  ,  1148.  ,  2014.  ,   325.  ])

In [19]:
df_combined['Price'].unique()

array([ 1450.  ,  1499.  ,  1419.  ,  1599.  ,   600.  ,  1099.  ,
         900.  ,  1119.  ,  2193.  ,  1782.  ,  1945.  ,  1400.  ,
        1722.  ,  1200.  ,  1000.  ,  1188.  ,   170.  ,  7200.  ,
        1799.  ,  1496.  ,  1899.  ,  2699.  ,  2799.  ,  2370.  ,
         800.  ,   999.  ,   879.  ,   809.  ,   950.  ,  1100.  ,
         650.  ,   449.  ,   350.  ,   450.  ,   499.  ,   850.  ,
        1850.  ,   700.  ,   735.  ,   949.  ,  1550.  ,  1044.  ,
         899.  ,   978.  ,   200.  ,   675.  ,  3000.  ,  1139.  ,
         140.  ,   150.  ,   490.  ,   505.  ,   699.  ,   400.  ,
        1699.  ,  2080.  ,  1600.  ,   550.  ,   990.  ,  1399.  ,
       11000.  ,   100.  ,   330.  ,   500.  ,   495.  ,   300.  ,
         485.  ,   510.  ,   270.  ,   315.  ,   349.  ,   308.  ,
         333.  ,   280.  ,   299.  ,   397.  ,   446.  ,   619.  ,
         523.  ,   408.  ,   459.  ,   206.  ,   549.  ,   739.  ,
         289.  ,   720.  ,   267.  ,   571.  ,   612.  ,   489.  ,
         639.  ,   590.  ,   777.  ,   610.  ,   670.  ,   555.  ,
         524.  ,   442.  ,  1129.  ,  2000.  ,   629.  ,  1080.  ,
         780.  ,  1036.  ,   799.  ,  1289.  ,  1409.  ,   989.  ,
        1990.  ,   711.  ,   749.  ,   738.  ,   810.  ,   750.  ,
        2100.  ,   392.  ,   464.  ,   689.  ,   580.  ,   891.  ,
        1624.  ,   789.  ,  1479.  ,   893.  ,  1090.  ,   660.  ,
         751.  ,   332.  ,  2429.  ,   647.  ,   878.  ,   730.  ,
         599.  ,   667.  ,   680.  ,   832.  ,  1169.  ,  1300.  ,
        1500.  ,  1149.  ,  1387.  ,   649.  ,  1299.  ,  1590.  ,
        1999.  ,  1055.  ,  1494.  ,  1548.  ,  1349.  ,   880.  ,
        1270.  ,  1199.  ,  1143.  ,  1350.  ,  1250.  ,  1155.  ,
        1202.  ,  1549.  ,   795.  ,   488.78,   425.  ,   375.  ,
         570.  ,   585.  ,   540.  ,   630.  ,   620.  ,   535.  ,
         439.  ,   415.  ,   595.  ,   465.  ,   451.  ,   475.  ,
         135.  ,   486.  ,   429.  ,   110.  ,   167.  ,   185.  ,
         121.  ,    95.  ,   145.  ,   250.  ,   285.  ,   430.  ,
         130.  ,   190.  ,   142.  ,   160.  ,   134.  ,   238.  ,
         246.  ,    80.  ,    78.  ,   233.  ,   319.  ,   288.  ,
          65.  ,    64.  ,    68.  ,   155.  ,   147.  ,    96.  ,
         108.  ,   163.  ,   520.  ,   115.  ,   271.  ,   303.  ,
         312.  ,    88.  ,   335.  ,   139.  ,    75.  ,   896.  ,
        1210.  ,  2530.  ,  2350.  ,   929.  ,  1069.  ,   830.  ,
        5000.  ,   454.  ,   399.  ,   394.  ,   370.  ,   521.  ,
         807.  ,  1013.  ,  1160.  ,  1050.  ,   824.  ,   431.  ,
        1320.  ,  1049.  ,   666.  ,   790.  ,  3999.  ,   560.  ,
         994.  ,   844.  ,   792.  ,   422.  ,   398.  ,  1329.  ,
         979.  ,   980.  ,  1401.79,   784.  ,  1079.  ,   478.  ,
         709.  ,   690.  ,  4000.  ,   356.25,   802.  ,   569.  ,
        1919.  ,  1425.  ,  1673.  ,   970.  ,   362.  ,   506.  ,
        1220.  ,   373.  ,   930.  ,  2099.  ,   427.68,   740.  ,
         463.  ,   224.  ,   708.  ,   435.  ,   503.  ,  1039.  ,
        1109.  ,   959.  ,   719.  ,   361.  ,   664.  ,   705.  ,
         998.  ,   359.  ,   504.  ,   529.  ,   849.  ,   924.  ,
         284.  ,   409.  ,   452.  ,  1019.  ,   939.  ,   414.  ,
         534.  ,  1490.  ,   379.  ,   368.  ,   375.1 ,   360.  ,
         321.  ,   212.5 ,  1860.  ,  1020.  ,   864.  ,   355.  ,
         665.  ,   391.  ,   283.  ,   340.  ,   378.  ,   759.  ,
         760.  ,  1900.  ,  1530.  ,   364.  ,   302.  ,   334.  ,
        1117.  ,  1620.  ,  1572.  ,  1994.  ,   618.  ,  1203.57,
        1804.  ,  1757.  ,  1908.  ,   661.  ,   637.  ,   692.  ,
         320.  ,   434.  ,  1304.  ,   854.  ,   876.  ,  1062.  ,
        1704.  ,   907.  ,   347.  ,   657.  ,   432.  ,   227.  ,
        1880.  ,  1800.  ,   570.48,   438.  ,  1537.  ,  1424.  ,
         685.  ,   583.  ,   641.  ,   963.  ,   545.  ,   818.  ,
         488.  ,   403.  ,   925.  ,  1410.  ,  1769.  ,  1709.  ,
        1128.  ,   341.  ,   354.  ,   328.  ,   357.  ,  2223.  ,
        2184.  ,  1758.  ,   736.  ,  1148.  ,  2014.  ,   325.  ])

In [20]:
df_combined['Price'] = df_combined['Price'].fillna("").astype(str) # Fill missing values (NaN) in the 'Price' column with an empty string

In [21]:
df_combined['Price'].unique() #provides all unique values in the coloumn

array(['1450.0', '1499.0', '1419.0', '1599.0', '600.0', '1099.0', '900.0',
       '1119.0', '2193.0', '1782.0', '1945.0', '1400.0', '1722.0',
       '1200.0', '1000.0', '1188.0', '170.0', '7200.0', '1799.0',
       '1496.0', '1899.0', '2699.0', '2799.0', '2370.0', '800.0', '999.0',
       '879.0', '809.0', '950.0', '1100.0', '650.0', '449.0', '350.0',
       '450.0', '499.0', '850.0', '1850.0', '700.0', '735.0', '949.0',
       '1550.0', '1044.0', '899.0', '978.0', '200.0', '675.0', '3000.0',
       '1139.0', '140.0', '150.0', '490.0', '505.0', '699.0', '400.0',
       '1699.0', '2080.0', '1600.0', '550.0', '990.0', '1399.0',
       '11000.0', '100.0', '330.0', '500.0', '495.0', '300.0', '485.0',
       '510.0', '270.0', '315.0', '349.0', '308.0', '333.0', '280.0',
       '299.0', '397.0', '446.0', '619.0', '523.0', '408.0', '459.0',
       '206.0', '549.0', '739.0', '289.0', '720.0', '267.0', '571.0',
       '612.0', '489.0', '639.0', '590.0', '777.0', '610.0', '670.0',
       '555.0', '524.0', '442.0', '1129.0', '2000.0', '629.0', '1080.0',
       '780.0', '1036.0', '799.0', '1289.0', '1409.0', '989.0', '1990.0',
       '711.0', '749.0', '738.0', '810.0', '750.0', '2100.0', '392.0',
       '464.0', '689.0', '580.0', '891.0', '1624.0', '789.0', '1479.0',
       '893.0', '1090.0', '660.0', '751.0', '332.0', '2429.0', '647.0',
       '878.0', '730.0', '599.0', '667.0', '680.0', '832.0', '1169.0',
       '1300.0', '1500.0', '1149.0', '1387.0', '649.0', '1299.0',
       '1590.0', '1999.0', '1055.0', '1494.0', '1548.0', '1349.0',
       '880.0', '1270.0', '1199.0', '1143.0', '1350.0', '1250.0',
       '1155.0', '1202.0', '1549.0', '795.0', '488.78', '425.0', '375.0',
       '570.0', '585.0', '540.0', '630.0', '620.0', '535.0', '439.0',
       '415.0', '595.0', '465.0', '451.0', '475.0', '135.0', '486.0',
       '429.0', '110.0', '167.0', '185.0', '121.0', '95.0', '145.0',
       '250.0', '285.0', '430.0', '130.0', '190.0', '142.0', '160.0',
       '134.0', '238.0', '246.0', '80.0', '78.0', '233.0', '319.0',
       '288.0', '65.0', '64.0', '68.0', '155.0', '147.0', '96.0', '108.0',
       '163.0', '520.0', '115.0', '271.0', '303.0', '312.0', '88.0',
       '335.0', '139.0', '75.0', '896.0', '1210.0', '2530.0', '2350.0',
       '929.0', '1069.0', '830.0', '5000.0', '454.0', '399.0', '394.0',
       '370.0', '521.0', '807.0', '1013.0', '1160.0', '1050.0', '824.0',
       '431.0', '1320.0', '1049.0', '666.0', '790.0', '3999.0', '560.0',
       '994.0', '844.0', '792.0', '422.0', '398.0', '1329.0', '979.0',
       '980.0', '1401.79', '784.0', '1079.0', '478.0', '709.0', '690.0',
       '4000.0', '356.25', '802.0', '569.0', '1919.0', '1425.0', '1673.0',
       '970.0', '362.0', '506.0', '1220.0', '373.0', '930.0', '2099.0',
       '427.68', '740.0', '463.0', '224.0', '708.0', '435.0', '503.0',
       '1039.0', '1109.0', '959.0', '719.0', '361.0', '664.0', '705.0',
       '998.0', '359.0', '504.0', '529.0', '849.0', '924.0', '284.0',
       '409.0', '452.0', '1019.0', '939.0', '414.0', '534.0', '1490.0',
       '379.0', '368.0', '375.1', '360.0', '321.0', '212.5', '1860.0',
       '1020.0', '864.0', '355.0', '665.0', '391.0', '283.0', '340.0',
       '378.0', '759.0', '760.0', '1900.0', '1530.0', '364.0', '302.0',
       '334.0', '1117.0', '1620.0', '1572.0', '1994.0', '618.0',
       '1203.57', '1804.0', '1757.0', '1908.0', '661.0', '637.0', '692.0',
       '320.0', '434.0', '1304.0', '854.0', '876.0', '1062.0', '1704.0',
       '907.0', '347.0', '657.0', '432.0', '227.0', '1880.0', '1800.0',
       '570.48', '438.0', '1537.0', '1424.0', '685.0', '583.0', '641.0',
       '963.0', '545.0', '818.0', '488.0', '403.0', '925.0', '1410.0',
       '1769.0', '1709.0', '1128.0', '341.0', '354.0', '328.0', '357.0',
       '2223.0', '2184.0', '1758.0', '736.0', '1148.0', '2014.0', '325.0'],
      dtype=object)

In [22]:

df_combined["Ratings"].unique()

array([4.7, 4.6, 4.5, 4.4, 4. , 4.8, 4.1, 3.8, 3.2, 3.4, 4.3, 3.6, 3. ,
       3.3, 3.5, 2.8, 2.7, 1.9, 3.9, 3.7, 2.1, 4.2, 2.9, 2.6, 5. , 3.1,
       1.7, 4.9, 2.3, 1.6, 2.2, 1.8, 1. , 1.2, 2.4, 2.5, 0. , 2. , 1.4,
       1.1, 1.3, 1.5])

In [23]:
df_combined['Seats_Available'].unique()

array([ 6,  3, 19, 17, 26,  2, 11, 22, 16, 18, 15, 21, 25, 27,  4,  8,  1,
       13,  5, 20, 29, 30, 23, 32, 34, 28, 12, 24, 41, 42, 36, 46, 47, 45,
       48, 33, 31, 38, 10, 40, 52, 44,  7,  0, 14, 35, 37,  9, 39, 50, 66,
       51, 43, 49, 61])

In [24]:
df_combined['Seats_Available'].unique()

array([ 6,  3, 19, 17, 26,  2, 11, 22, 16, 18, 15, 21, 25, 27,  4,  8,  1,
       13,  5, 20, 29, 30, 23, 32, 34, 28, 12, 24, 41, 42, 36, 46, 47, 45,
       48, 33, 31, 38, 10, 40, 52, 44,  7,  0, 14, 35, 37,  9, 39, 50, 66,
       51, 43, 49, 61])

In [25]:

df_combined['Start_time'].unique()

array(['21:00:00', '22:30:00', '21:15:00', '22:05:00', '18:00:00',
       '21:32:00', '20:30:00', '18:30:00', '16:30:00', '20:00:00',
       '19:35:00', '16:46:00', '17:15:00', '20:50:00', '19:40:00',
       '19:30:00', '16:00:00', '04:00:00', '06:30:00', '07:00:00',
       '10:35:00', '19:45:00', '21:20:00', '17:00:00', '17:01:00',
       '08:30:00', '10:20:00', '10:30:00', '12:30:00', '23:15:00',
       '00:00:00', '18:45:00', '19:00:00', '16:40:00', '18:10:00',
       '15:40:00', '10:00:00', '15:30:00', '21:45:00', '23:59:00',
       '06:00:00', '11:45:00', '07:30:00', '13:45:00', '08:00:00',
       '10:15:00', '11:30:00', '12:00:00', '23:00:00', '23:45:00',
       '10:31:00', '16:01:00', '05:15:00', '15:00:00', '08:15:00',
       '14:30:00', '20:19:00', '17:30:00', '09:25:00', '13:30:00',
       '15:55:00', '19:15:00', '18:15:00', '17:20:00', '17:10:00',
       '22:15:00', '20:04:00', '20:40:00', '21:25:00', '23:44:00',
       '21:30:00', '19:10:00', '19:01:00', '19:20:00', '16:15:00',
       '17:55:00', '22:00:00', '16:20:00', '17:40:00', '22:02:00',
       '00:50:00', '01:30:00', '23:40:00', '05:50:00', '10:25:00',
       '11:20:00', '19:05:00', '04:40:00', '04:45:00', '05:00:00',
       '00:20:00', '23:30:00', '03:40:00', '22:35:00', '22:45:00',
       '02:15:00', '02:30:00', '21:40:00', '03:00:00', '23:38:00',
       '23:10:00', '05:30:00', '22:40:00', '03:06:00', '05:06:00',
       '09:30:00', '00:15:00', '00:30:00', '20:05:00', '23:55:00',
       '12:15:00', '21:16:00', '00:55:00', '01:00:00', '01:25:00',
       '20:45:00', '20:55:00', '00:35:00', '00:45:00', '01:10:00',
       '03:15:00', '17:25:00', '04:20:00', '03:30:00', '20:31:00',
       '19:50:00', '21:50:00', '01:20:00', '22:20:00', '22:10:00',
       '00:27:00', '01:15:00', '02:35:00', '22:31:00', '23:05:00',
       '09:00:00', '13:55:00', '13:57:00', '23:50:00', '23:58:00',
       '23:36:00', '18:50:00', '20:10:00', '18:20:00', '20:15:00',
       '21:35:00', '18:01:00', '19:55:00', '22:50:00', '20:25:00',
       '20:20:00', '14:25:00', '16:45:00', '17:50:00', '13:00:00',
       '14:00:00', '16:05:00', '14:55:00', '14:56:00', '15:10:00',
       '13:35:00', '14:10:00', '15:25:00', '13:10:00', '15:15:00',
       '14:05:00', '16:50:00', '14:15:00', '15:20:00', '14:29:00',
       '14:32:00', '23:20:00', '14:35:00', '16:35:00', '17:45:00',
       '15:45:00', '23:25:00', '01:40:00', '00:40:00', '03:35:00',
       '04:15:00', '11:00:00', '20:35:00', '21:10:00', '22:25:00',
       '01:50:00', '02:25:00', '08:35:00', '04:30:00', '02:00:00',
       '02:45:00', '02:55:00', '01:46:00', '02:40:00', '23:35:00',
       '02:05:00', '02:20:00', '19:25:00', '14:45:00', '23:46:00',
       '17:59:00', '18:29:00', '20:28:00', '16:31:00', '17:35:00',
       '22:23:00', '23:49:00', '20:02:00', '21:55:00', '16:25:00',
       '18:25:00', '19:26:00', '20:01:00', '18:05:00', '19:04:00',
       '15:50:00', '18:40:00', '21:01:00', '22:14:00', '18:03:00',
       '22:46:00', '13:56:00', '12:55:00', '23:14:00', '22:21:00',
       '23:09:00', '14:40:00', '16:26:00', '17:47:00', '19:14:00'],
      dtype=object)

In [26]:

df_combined['End_time'].unique()

array(['07:30:00', '08:45:00', '08:05:00', '09:30:00', '08:00:00',
       '07:45:00', '07:02:00', '06:45:00', '05:25:00', '11:55:00',
       '10:20:00', '10:31:00', '10:15:00', '09:40:00', '19:45:00',
       '10:00:00', '10:30:00', '11:00:00', '15:00:00', '08:15:00',
       '09:25:00', '08:30:00', '07:15:00', '07:50:00', '05:30:00',
       '06:40:00', '22:15:00', '21:10:00', '21:30:00', '22:30:00',
       '14:50:00', '18:50:00', '17:00:00', '19:00:00', '09:00:00',
       '07:00:00', '04:30:00', '04:00:00', '04:45:00', '03:00:00',
       '11:45:00', '17:15:00', '20:00:00', '06:05:00', '02:00:00',
       '04:15:00', '06:00:00', '11:15:00', '13:00:00', '09:10:00',
       '15:30:00', '17:30:00', '11:25:00', '12:55:00', '13:10:00',
       '18:45:00', '19:15:00', '23:45:00', '00:45:00', '01:30:00',
       '05:42:00', '02:35:00', '08:25:00', '10:45:00', '12:30:00',
       '14:30:00', '18:00:00', '08:31:00', '14:46:00', '10:39:00',
       '01:03:00', '02:30:00', '04:40:00', '11:30:00', '20:30:00',
       '13:25:00', '18:15:00', '16:01:00', '22:55:00', '23:15:00',
       '23:20:00', '23:40:00', '20:45:00', '23:00:00', '23:59:00',
       '01:15:00', '21:55:00', '05:35:00', '21:40:00', '23:31:00',
       '06:30:00', '22:40:00', '23:50:00', '01:00:00', '06:08:00',
       '07:25:00', '04:55:00', '21:00:00', '19:30:00', '20:40:00',
       '20:35:00', '22:00:00', '23:42:00', '20:50:00', '03:30:00',
       '05:15:00', '05:00:00', '01:54:00', '02:40:00', '18:40:00',
       '22:45:00', '07:05:00', '06:42:00', '12:25:00', '17:55:00',
       '00:30:00', '23:30:00', '11:40:00', '12:40:00', '12:00:00',
       '21:45:00', '04:10:00', '09:15:00', '20:20:00', '05:10:00',
       '05:45:00', '06:15:00', '23:35:00', '23:55:00', '06:50:00',
       '06:35:00', '09:05:00', '05:50:00', '05:05:00', '08:16:00',
       '10:16:00', '07:20:00', '10:40:00', '08:55:00', '09:45:00',
       '15:05:00', '15:55:00', '06:10:00', '04:29:00', '05:20:00',
       '06:13:00', '00:40:00', '02:10:00', '02:45:00', '02:15:00',
       '06:55:00', '23:05:00', '08:40:00', '18:35:00', '04:05:00',
       '03:50:00', '04:50:00', '04:20:00', '01:45:00', '01:25:00',
       '02:50:00', '23:48:00', '02:29:00', '03:40:00', '04:25:00',
       '00:15:00', '00:00:00', '01:10:00', '03:15:00', '19:20:00',
       '19:50:00', '21:35:00', '14:15:00', '15:15:00', '16:45:00',
       '16:30:00', '19:05:00', '18:55:00', '19:10:00', '18:25:00',
       '17:40:00', '18:30:00', '16:50:00', '17:05:00', '17:35:00',
       '17:25:00', '18:05:00', '19:40:00', '03:35:00', '18:26:00',
       '02:55:00', '17:10:00', '17:20:00', '20:05:00', '22:05:00',
       '08:35:00', '11:48:00', '06:41:00', '03:25:00', '06:18:00',
       '10:10:00', '13:30:00', '16:10:00', '00:20:00', '02:25:00',
       '01:40:00', '06:20:00', '14:40:00', '04:35:00', '05:49:00',
       '06:27:00', '08:10:00', '14:05:00', '20:10:00', '16:00:00',
       '06:25:00', '05:26:00', '18:03:00', '07:40:00', '03:45:00',
       '12:59:00', '15:21:00', '18:20:00', '21:15:00', '05:55:00',
       '05:33:00', '21:01:00', '21:18:00', '21:49:00', '22:27:00',
       '23:49:00', '22:35:00', '08:20:00', '21:20:00', '22:50:00',
       '21:54:00', '22:01:00', '22:25:00', '22:54:00', '23:51:00',
       '23:52:00', '00:50:00', '21:05:00', '07:55:00', '05:40:00',
       '05:58:00', '00:16:00', '23:10:00', '01:17:00', '01:20:00',
       '02:20:00', '19:35:00', '05:59:00', '02:05:00', '01:05:00',
       '07:10:00'], dtype=object)

In [27]:
df_combined['Total_duration'].unique()

array(['04:30:00', '07:15:00', '05:20:00', '07:35:00', '02:00:00',
       '06:15:00', '04:34:00', '03:15:00', '23:55:00', '01:15:00',
       '07:55:00', '05:55:00', '03:17:00', '02:30:00', '06:20:00',
       '05:10:00', '11:45:00', '14:00:00', '17:00:00', '18:00:00',
       '01:35:00', '04:00:00', '06:45:00', '07:00:00', '03:00:00',
       '01:50:00', '22:30:00', '23:40:00', '17:30:00', '14:15:00',
       '13:40:00', '14:30:00', '15:31:00', '23:20:00', '03:30:00',
       '07:30:00', '06:00:00', '09:00:00', '01:45:00', '00:15:00',
       '23:30:00', '20:40:00', '22:55:00', '18:40:00', '21:45:00',
       '08:45:00', '01:05:00', '21:00:00', '22:45:00', '07:45:00',
       '07:59:00', '13:15:00', '15:15:00', '21:15:00', '00:45:00',
       '16:40:00', '05:15:00', '09:30:00', '17:10:00', '21:40:00',
       '00:25:00', '01:10:00', '18:30:00', '10:45:00', '11:15:00',
       '22:16:00', '09:16:00', '15:00:00', '23:00:00', '05:05:00',
       '15:25:00', '17:25:00', '19:40:00', '01:42:00', '20:30:00',
       '21:05:00', '12:30:00', '19:00:00', '08:00:00', '16:25:00',
       '21:30:00', '10:00:00', '16:01:00', '04:31:00', '00:00:00',
       '06:58:00', '16:03:00', '20:00:00', '05:30:00', '06:30:00',
       '19:55:00', '22:00:00', '08:55:00', '16:45:00', '15:30:00',
       '01:55:00', '10:15:00', '20:31:00', '07:31:00', '04:05:00',
       '03:25:00', '02:39:00', '04:45:00', '07:20:00', '02:55:00',
       '03:27:00', '02:40:00', '04:40:00', '06:01:00', '06:09:00',
       '07:41:00', '07:25:00', '03:50:00', '03:29:00', '03:20:00',
       '04:20:00', '03:35:00', '05:12:00', '04:50:00', '05:45:00',
       '08:30:00', '05:40:00', '02:20:00', '04:15:00', '08:50:00',
       '08:40:00', '06:35:00', '05:25:00', '08:35:00', '06:05:00',
       '06:29:00', '06:25:00', '07:12:00', '07:40:00', '03:10:00',
       '03:45:00', '09:50:00', '11:20:00', '11:00:00', '03:55:00',
       '04:55:00', '05:35:00', '08:15:00', '08:25:00', '03:54:00',
       '04:59:00', '05:31:00', '05:00:00', '07:58:00', '09:45:00',
       '09:14:00', '03:05:00', '05:59:00', '07:10:00', '06:40:00',
       '09:25:00', '08:20:00', '06:55:00', '02:45:00', '03:53:00',
       '02:54:00', '06:50:00', '07:50:00', '07:48:00', '06:31:00',
       '07:17:00', '06:28:00', '07:16:00', '06:24:00', '06:48:00',
       '07:19:00', '08:10:00', '07:01:00', '11:10:00', '10:59:00',
       '09:15:00', '07:05:00', '04:35:00', '04:26:00', '04:41:00',
       '04:25:00', '04:21:00', '02:35:00', '03:40:00', '09:20:00',
       '10:05:00', '02:15:00', '03:19:00', '02:50:00', '10:25:00',
       '09:55:00', '02:01:00', '02:25:00', '01:30:00', '06:10:00',
       '05:26:00', '03:01:00', '02:51:00', '02:38:00', '04:06:00',
       '04:13:00', '13:00:00', '12:00:00', '05:48:00', '04:10:00',
       '05:51:00', '08:05:00', '07:03:00', '13:50:00', '07:39:00',
       '08:22:00', '28:30:00', '03:14:00', '05:01:00', '06:16:00',
       '06:56:00', '08:33:00', '04:51:00', '05:50:00', '05:56:00',
       '05:46:00', '05:47:00', '03:02:00', '02:52:00', '03:21:00',
       '09:10:00', '13:20:00', '13:30:00', '13:10:00', '10:50:00',
       '05:34:00', '05:29:00', '04:49:00', '04:47:00', '06:49:00',
       '12:50:00', '08:49:00', '07:44:00', '06:46:00', '05:27:00',
       '06:17:00', '04:16:00', '04:01:00', '05:09:00', '11:50:00',
       '12:15:00', '11:55:00', '10:40:00', '06:04:00', '16:10:00',
       '20:25:00', '16:15:00', '10:30:00', '09:05:00', '07:33:00',
       '08:13:00', '08:56:00', '10:55:00', '10:10:00'], dtype=object)

In [28]:
# Function to standardize duration format
def convert_to_hhmmss(duration):
    if 'm' in duration:  # If the format is like '30m'
        minutes = int(duration.replace('m', ''))
        return f"00:{minutes:02d}:00"
    elif ':' in duration:  # If the format is already in hh:mm:ss
        return duration
    else:
        return "00:00:00"  # Default for unrecognized formats (optional)

# Apply the function
df_combined['Total_duration'] = df_combined['Total_duration'].apply(convert_to_hhmmss)

# Display the updated column (or use it as needed)
print(df_combined['Total_duration'])

0       04:30:00
1       07:15:00
2       05:20:00
3       07:35:00
4       02:00:00
          ...
1119    09:10:00
1120    09:10:00
1121    09:05:00
1122    07:10:00
1123    06:45:00
Name: Total_duration, Length: 1124, dtype: object

In [29]:
df_combined['Total_duration'].unique()

array(['04:30:00', '07:15:00', '05:20:00', '07:35:00', '02:00:00',
       '06:15:00', '04:34:00', '03:15:00', '23:55:00', '01:15:00',
       '07:55:00', '05:55:00', '03:17:00', '02:30:00', '06:20:00',
       '05:10:00', '11:45:00', '14:00:00', '17:00:00', '18:00:00',
       '01:35:00', '04:00:00', '06:45:00', '07:00:00', '03:00:00',
       '01:50:00', '22:30:00', '23:40:00', '17:30:00', '14:15:00',
       '13:40:00', '14:30:00', '15:31:00', '23:20:00', '03:30:00',
       '07:30:00', '06:00:00', '09:00:00', '01:45:00', '00:15:00',
       '23:30:00', '20:40:00', '22:55:00', '18:40:00', '21:45:00',
       '08:45:00', '01:05:00', '21:00:00', '22:45:00', '07:45:00',
       '07:59:00', '13:15:00', '15:15:00', '21:15:00', '00:45:00',
       '16:40:00', '05:15:00', '09:30:00', '17:10:00', '21:40:00',
       '00:25:00', '01:10:00', '18:30:00', '10:45:00', '11:15:00',
       '22:16:00', '09:16:00', '15:00:00', '23:00:00', '05:05:00',
       '15:25:00', '17:25:00', '19:40:00', '01:42:00', '20:30:00',
       '21:05:00', '12:30:00', '19:00:00', '08:00:00', '16:25:00',
       '21:30:00', '10:00:00', '16:01:00', '04:31:00', '00:00:00',
       '06:58:00', '16:03:00', '20:00:00', '05:30:00', '06:30:00',
       '19:55:00', '22:00:00', '08:55:00', '16:45:00', '15:30:00',
       '01:55:00', '10:15:00', '20:31:00', '07:31:00', '04:05:00',
       '03:25:00', '02:39:00', '04:45:00', '07:20:00', '02:55:00',
       '03:27:00', '02:40:00', '04:40:00', '06:01:00', '06:09:00',
       '07:41:00', '07:25:00', '03:50:00', '03:29:00', '03:20:00',
       '04:20:00', '03:35:00', '05:12:00', '04:50:00', '05:45:00',
       '08:30:00', '05:40:00', '02:20:00', '04:15:00', '08:50:00',
       '08:40:00', '06:35:00', '05:25:00', '08:35:00', '06:05:00',
       '06:29:00', '06:25:00', '07:12:00', '07:40:00', '03:10:00',
       '03:45:00', '09:50:00', '11:20:00', '11:00:00', '03:55:00',
       '04:55:00', '05:35:00', '08:15:00', '08:25:00', '03:54:00',
       '04:59:00', '05:31:00', '05:00:00', '07:58:00', '09:45:00',
       '09:14:00', '03:05:00', '05:59:00', '07:10:00', '06:40:00',
       '09:25:00', '08:20:00', '06:55:00', '02:45:00', '03:53:00',
       '02:54:00', '06:50:00', '07:50:00', '07:48:00', '06:31:00',
       '07:17:00', '06:28:00', '07:16:00', '06:24:00', '06:48:00',
       '07:19:00', '08:10:00', '07:01:00', '11:10:00', '10:59:00',
       '09:15:00', '07:05:00', '04:35:00', '04:26:00', '04:41:00',
       '04:25:00', '04:21:00', '02:35:00', '03:40:00', '09:20:00',
       '10:05:00', '02:15:00', '03:19:00', '02:50:00', '10:25:00',
       '09:55:00', '02:01:00', '02:25:00', '01:30:00', '06:10:00',
       '05:26:00', '03:01:00', '02:51:00', '02:38:00', '04:06:00',
       '04:13:00', '13:00:00', '12:00:00', '05:48:00', '04:10:00',
       '05:51:00', '08:05:00', '07:03:00', '13:50:00', '07:39:00',
       '08:22:00', '28:30:00', '03:14:00', '05:01:00', '06:16:00',
       '06:56:00', '08:33:00', '04:51:00', '05:50:00', '05:56:00',
       '05:46:00', '05:47:00', '03:02:00', '02:52:00', '03:21:00',
       '09:10:00', '13:20:00', '13:30:00', '13:10:00', '10:50:00',
       '05:34:00', '05:29:00', '04:49:00', '04:47:00', '06:49:00',
       '12:50:00', '08:49:00', '07:44:00', '06:46:00', '05:27:00',
       '06:17:00', '04:16:00', '04:01:00', '05:09:00', '11:50:00',
       '12:15:00', '11:55:00', '10:40:00', '06:04:00', '16:10:00',
       '20:25:00', '16:15:00', '10:30:00', '09:05:00', '07:33:00',
       '08:13:00', '08:56:00', '10:55:00', '10:10:00'], dtype=object)

In [30]:
df_combined['Route_link'].unique()

array(['https://www.redbus.in/bus-tickets/pune-to-goa',
       'https://www.redbus.in/bus-tickets/goa-to-pune',
       'https://www.redbus.in/bus-tickets/mumbai-to-goa',
       'https://www.redbus.in/bus-tickets/goa-to-mumbai',
       'https://www.redbus.in/bus-tickets/belagavi-to-goa',
       'https://www.redbus.in/bus-tickets/bangalore-to-goa',
       'https://www.redbus.in/bus-tickets/goa-to-bangalore',
       'https://www.redbus.in/bus-tickets/goa-to-belagavi',
       'https://www.redbus.in/bus-tickets/goa-to-kolhapur-maharashtra',
       'https://www.redbus.in/bus-tickets/solapur-to-goa',
       'https://www.redbus.in/bus-tickets/goa-to-pandharpur',
       'https://www.redbus.in/bus-tickets/goa-to-solapur',
       'https://www.redbus.in/bus-tickets/calangute-goa-to-goa-airport',
       'https://www.redbus.in/bus-tickets/goa-to-sangola',
       'https://www.redbus.in/bus-tickets/sangola-to-goa',
       'https://www.redbus.in/bus-tickets/calangute-goa-to-mopa-airport',
       'https://www.redbus.in/bus-tickets/goa-airport-to-calangute-goa',
       'https://www.redbus.in/bus-tickets/mopa-airport-to-calangute-goa',
       'https://www.redbus.in/bus-tickets/shimoga-to-goa',
       'https://www.redbus.in/bus-tickets/marcel-to-belagavi',
       'https://www.redbus.in/bus-tickets/ponda-to-belagavi',
       'https://www.redbus.in/bus-tickets/belagavi-to-marcel',
       'https://www.redbus.in/bus-tickets/belagavi-to-ponda',
       'https://www.redbus.in/bus-tickets/panaji-to-goa-airport',
       'https://www.redbus.in/bus-tickets/goa-to-sangli',
       'https://www.redbus.in/bus-tickets/goa-to-miraj',
       'https://www.redbus.in/bus-tickets/margoa-to-mopa-airport',
       'https://www.redbus.in/bus-tickets/mopa-airport-to-goa',
       'https://www.redbus.in/bus-tickets/mopa-airport-to-margoa',
       'https://www.redbus.in/bus-tickets/goa-airport-to-panaji',
       'https://www.redbus.in/bus-tickets/shirdi-to-goa',
       'https://www.redbus.in/bus-tickets/goa-to-shimoga',
       'https://www.redbus.in/bus-tickets/goa-to-satara',
       'https://www.redbus.in/bus-tickets/panaji-to-mopa-airport',
       'https://www.redbus.in/bus-tickets/saquelim-to-belagavi',
       'https://www.redbus.in/bus-tickets/goa-to-shirdi',
       'https://www.redbus.in/bus-tickets/calangute-goa-to-goa',
       'https://www.redbus.in/bus-tickets/mopa-airport-to-panaji',
       'https://www.redbus.in/bus-tickets/belagavi-to-saquelim',
       'https://www.redbus.in/bus-tickets/calangute-goa-to-panaji',
       'https://www.redbus.in/bus-tickets/jodhpur-to-ajmer',
       'https://www.redbus.in/bus-tickets/beawer-to-jaipur',
       'https://www.redbus.in/bus-tickets/udaipur-to-jodhpur',
       'https://www.redbus.in/bus-tickets/jaipur-to-jodhpur',
       'https://www.redbus.in/bus-tickets/sikar-to-jaipur',
       'https://www.redbus.in/bus-tickets/aligarh-uttar-pradesh-to-jaipur',
       'https://www.redbus.in/bus-tickets/kota-rajasthan-to-jaipur',
       'https://www.redbus.in/bus-tickets/jaipur-to-pilani',
       'https://www.redbus.in/bus-tickets/jaipur-to-aligarh-uttar-pradesh',
       'https://www.redbus.in/bus-tickets/kishangarh-to-jaipur',
       'https://www.redbus.in/bus-tickets/sikar-to-bikaner',
       'https://www.redbus.in/bus-tickets/jodhpur-to-beawer',
       'https://www.redbus.in/bus-tickets/udaipur-to-pali-rajasthan',
       'https://www.redbus.in/bus-tickets/jaipur-to-kota-rajasthan',
       'https://www.redbus.in/bus-tickets/kota-rajasthan-to-udaipur',
       'https://www.redbus.in/bus-tickets/jaipur-to-bharatpur',
       'https://www.redbus.in/bus-tickets/jaipur-to-mathura',
       'https://www.redbus.in/bus-tickets/bikaner-to-sikar',
       'https://www.redbus.in/bus-tickets/pali-to-udaipur',
       'https://www.redbus.in/bus-tickets/udaipur-to-jaipur',
       'https://www.redbus.in/bus-tickets/khammam-to-hyderabad',
       'https://www.redbus.in/bus-tickets/hyderabad-to-vijayawada',
       'https://www.redbus.in/bus-tickets/hyderabad-to-khammam',
       'https://www.redbus.in/bus-tickets/hyderabad-to-srisailam',
       'https://www.redbus.in/bus-tickets/karimnagar-to-hyderabad',
       'https://www.redbus.in/bus-tickets/hyderabad-to-adilabad',
       'https://www.redbus.in/bus-tickets/kothagudem-to-hyderabad',
       'https://www.redbus.in/bus-tickets/hyderabad-to-mancherial',
       'https://www.redbus.in/bus-tickets/guntur-to-hyderabad',
       'https://www.redbus.in/bus-tickets/godavarikhani-to-hyderabad',
       'https://www.redbus.in/bus-tickets/kodad-to-hyderabad',
       'https://www.redbus.in/bus-tickets/hyderabad-to-ongole',
       'https://www.redbus.in/bus-tickets/jagityal-to-hyderabad',
       'https://www.redbus.in/bus-tickets/hyderabad-to-nirmal',
       'https://www.redbus.in/bus-tickets/hyderabad-to-guntur',
       'https://www.redbus.in/bus-tickets/hyderabad-to-karimnagar',
       'https://www.redbus.in/bus-tickets/hyderabad-to-kothagudem',
       'https://www.redbus.in/bus-tickets/hyderabad-to-bhadrachalam',
       'https://www.redbus.in/bus-tickets/hyderabad-to-sathupalli',
       'https://www.redbus.in/bus-tickets/hyderabad-to-warangal',
       'https://www.redbus.in/bus-tickets/hyderabad-to-tirupathi',
       'https://www.redbus.in/bus-tickets/hyderabad-to-ananthapur',
       'https://www.redbus.in/bus-tickets/hyderabad-to-armoor',
       'https://www.redbus.in/bus-tickets/hyderabad-to-godavarikhani',
       'https://www.redbus.in/bus-tickets/peddapalli-telangana-to-hyderabad',
       'https://www.redbus.in/bus-tickets/hyderabad-to-kodad',
       'https://www.redbus.in/bus-tickets/bangalore-to-kozhikode',
       'https://www.redbus.in/bus-tickets/kozhikode-to-ernakulam',
       'https://www.redbus.in/bus-tickets/kozhikode-to-bangalore',
       'https://www.redbus.in/bus-tickets/ernakulam-to-kozhikode',
       'https://www.redbus.in/bus-tickets/mysore-to-kozhikode',
       'https://www.redbus.in/bus-tickets/kozhikode-to-mysore',
       'https://www.redbus.in/bus-tickets/kozhikode-to-thrissur',
       'https://www.redbus.in/bus-tickets/kozhikode-to-thiruvananthapuram',
       'https://www.redbus.in/bus-tickets/kozhikode-to-kottayam',
       'https://www.redbus.in/bus-tickets/thrissur-to-kozhikode',
       'https://www.redbus.in/bus-tickets/bangalore-to-kalpetta',
       'https://www.redbus.in/bus-tickets/bangalore-to-kannur',
       'https://www.redbus.in/bus-tickets/kalpetta-to-bangalore',
       'https://www.redbus.in/bus-tickets/kottayam-to-kozhikode',
       'https://www.redbus.in/bus-tickets/thiruvananthapuram-to-kozhikode',
       'https://www.redbus.in/bus-tickets/kannur-to-bangalore',
       'https://www.redbus.in/bus-tickets/kozhikode-to-aluva',
       'https://www.redbus.in/bus-tickets/tezpur-to-guwahati',
       'https://www.redbus.in/bus-tickets/guwahati-to-tezpur',
       'https://www.redbus.in/bus-tickets/guwahati-to-nagaon',
       'https://www.redbus.in/bus-tickets/dhubri-to-guwahati',
       'https://www.redbus.in/bus-tickets/tezpur-to-dibrugarh',
       'https://www.redbus.in/bus-tickets/dibrugarh-to-jorhat',
       'https://www.redbus.in/bus-tickets/north-lakhimpur-to-dibrugarh',
       'https://www.redbus.in/bus-tickets/guwahati-to-biswanath-charali',
       'https://www.redbus.in/bus-tickets/biswanath-charali-to-guwahati',
       'https://www.redbus.in/bus-tickets/dibrugarh-to-tezpur',
       'https://www.redbus.in/bus-tickets/bokakhat-to-dibrugarh',
       'https://www.redbus.in/bus-tickets/moran-to-tezpur',
       'https://www.redbus.in/bus-tickets/dibrugarh-to-north-lakhimpur',
       'https://www.redbus.in/bus-tickets/north-lakhimpur-to-tezpur',
       'https://www.redbus.in/bus-tickets/dibrugarh-to-biswanath-charali',
       'https://www.redbus.in/bus-tickets/gohpur-to-dibrugarh',
       'https://www.redbus.in/bus-tickets/gohpur-to-guwahati',
       'https://www.redbus.in/bus-tickets/guwahati-to-gohpur',
       'https://www.redbus.in/bus-tickets/guwahati-to-kaliabor',
       'https://www.redbus.in/bus-tickets/north-lakhimpur-to-guwahati',
       'https://www.redbus.in/bus-tickets/tezpur-to-tinsukia',
       'https://www.redbus.in/bus-tickets/tezpur-to-north-lakhimpur',
       'https://www.redbus.in/bus-tickets/north-lakhimpur-to-nagaon',
       'https://www.redbus.in/bus-tickets/durgapur-to-kolkata',
       'https://www.redbus.in/bus-tickets/kolkata-to-burdwan',
       'https://www.redbus.in/bus-tickets/kolkata-to-durgapur',
       'https://www.redbus.in/bus-tickets/haldia-to-kolkata',
       'https://www.redbus.in/bus-tickets/kolkata-to-haldia',
       'https://www.redbus.in/bus-tickets/kolkata-to-arambagh-west-bengal',
       'https://www.redbus.in/bus-tickets/kolkata-to-digha',
       'https://www.redbus.in/bus-tickets/digha-to-kolkata',
       'https://www.redbus.in/bus-tickets/kolkata-to-bankura',
       'https://www.redbus.in/bus-tickets/kolkata-to-asansol',
       'https://www.redbus.in/bus-tickets/kolkata-to-midnapore',
       'https://www.redbus.in/bus-tickets/jhargram-to-kolkata',
       'https://www.redbus.in/bus-tickets/kolkata-to-contai-kanthi',
       'https://www.redbus.in/bus-tickets/kolkata-to-nimtouri',
       'https://www.redbus.in/bus-tickets/digha-to-durgapur',
       'https://www.redbus.in/bus-tickets/kolkata-to-nandakumar',
       'https://www.redbus.in/bus-tickets/kolkata-to-kolaghat',
       'https://www.redbus.in/bus-tickets/kolkata-to-mecheda-west-bengal',
       'https://www.redbus.in/bus-tickets/durgapur-to-barasat-west-bengal',
       'https://www.redbus.in/bus-tickets/kolkata-to-chandipur-west-bengal',
       'https://www.redbus.in/bus-tickets/berhampore-to-durgapur',
       'https://www.redbus.in/bus-tickets/durgapur-to-digha',
       'https://www.redbus.in/bus-tickets/durgapur-to-berhampore',
       'https://www.redbus.in/bus-tickets/digha-to-barasat-west-bengal',
       'https://www.redbus.in/bus-tickets/kolkata-to-heria',
       'https://www.redbus.in/bus-tickets/kolkata-to-bajkul-west-bengal',
       'https://www.redbus.in/bus-tickets/kolkata-to-debra',
       'https://www.redbus.in/bus-tickets/kolkata-to-ramnagar-west-bengal',
       'https://www.redbus.in/bus-tickets/kolkata-to-kirnahar-west-bengal',
       'https://www.redbus.in/bus-tickets/kolkata-to-jhargram',
       'https://www.redbus.in/bus-tickets/kolkata-to-panskura',
       'https://www.redbus.in/bus-tickets/durgapur-to-bankura',
       'https://www.redbus.in/bus-tickets/siliguri-to-kolkata',
       'https://www.redbus.in/bus-tickets/vijayawada-to-hyderabad',
       'https://www.redbus.in/bus-tickets/kakinada-to-visakhapatnam',
       'https://www.redbus.in/bus-tickets/chittoor-andhra-pradesh-to-bangalore',
       'https://www.redbus.in/bus-tickets/bangalore-to-tirupathi',
       'https://www.redbus.in/bus-tickets/tirupathi-to-bangalore',
       'https://www.redbus.in/bus-tickets/kadapa-to-bangalore',
       'https://www.redbus.in/bus-tickets/ananthapur-to-bangalore',
       'https://www.redbus.in/bus-tickets/bangalore-to-kadapa',
       'https://www.redbus.in/bus-tickets/ongole-to-hyderabad',
       'https://www.redbus.in/bus-tickets/bangalore-to-chittoor-andhra-pradesh',
       'https://www.redbus.in/bus-tickets/bangalore-to-ananthapur',
       'https://www.redbus.in/bus-tickets/visakhapatnam-to-kakinada',
       'https://www.redbus.in/bus-tickets/kadiri-to-bangalore',
       'https://www.redbus.in/bus-tickets/vinukonda-to-hyderabad',
       'https://www.redbus.in/bus-tickets/bangalore-to-kadiri',
       'https://www.redbus.in/bus-tickets/hyderabad-to-narsaraopet',
       'https://www.redbus.in/bus-tickets/madanapalli-to-bangalore',
       'https://www.redbus.in/bus-tickets/narsaraopet-to-hyderabad',
       'https://www.redbus.in/bus-tickets/rajahmundry-to-visakhapatnam',
       'https://www.redbus.in/bus-tickets/eluru-to-hyderabad',
       'https://www.redbus.in/bus-tickets/chennai-to-tirupathi',
       'https://www.redbus.in/bus-tickets/bangalore-to-madanapalli',
       'https://www.redbus.in/bus-tickets/rayachoti-to-bangalore',
       'https://www.redbus.in/bus-tickets/hyderabad-to-kurnool',
       'https://www.redbus.in/bus-tickets/tirupathi-to-chennai',
       'https://www.redbus.in/bus-tickets/visakhapatnam-to-vijayawada',
       'https://www.redbus.in/bus-tickets/rajahmundry-to-vijayawada',
       'https://www.redbus.in/bus-tickets/macherla-to-hyderabad',
       'https://www.redbus.in/bus-tickets/nandyala-to-hyderabad',
       'https://www.redbus.in/bus-tickets/hyderabad-to-eluru',
       'https://www.redbus.in/bus-tickets/bangalore-to-rayachoti',
       'https://www.redbus.in/bus-tickets/kurnool-to-hyderabad',
       'https://www.redbus.in/bus-tickets/hyderabad-to-vinukonda',
       'https://www.redbus.in/bus-tickets/vijayawada-to-visakhapatnam',
       'https://www.redbus.in/bus-tickets/kurnool-to-bangalore',
       'https://www.redbus.in/bus-tickets/rajahmundry-to-hyderabad',
       'https://www.redbus.in/bus-tickets/amalapuram-to-visakhapatnam',
       'https://www.redbus.in/bus-tickets/kurnool-to-vijayawada',
       'https://www.redbus.in/bus-tickets/visakhapatnam-to-rajahmundry',
       'https://www.redbus.in/bus-tickets/hyderabad-to-macherla',
       'https://www.redbus.in/bus-tickets/nellore-to-bangalore',
       'https://www.redbus.in/bus-tickets/tadipatri-to-bangalore',
       'https://www.redbus.in/bus-tickets/kakinada-to-vijayawada',
       'https://www.redbus.in/bus-tickets/visakhapatnam-to-amalapuram',
       'https://www.redbus.in/bus-tickets/hyderabad-to-markapuram',
       'https://www.redbus.in/bus-tickets/hyderabad-to-nandyala',
       'https://www.redbus.in/bus-tickets/delhi-to-bareilly',
       'https://www.redbus.in/bus-tickets/delhi-to-lucknow',
       'https://www.redbus.in/bus-tickets/bareilly-to-delhi',
       'https://www.redbus.in/bus-tickets/lucknow-to-gorakhpur',
       'https://www.redbus.in/bus-tickets/aligarh-uttar-pradesh-to-delhi',
       'https://www.redbus.in/bus-tickets/lucknow-to-allahabad',
       'https://www.redbus.in/bus-tickets/delhi-to-aligarh-uttar-pradesh',
       'https://www.redbus.in/bus-tickets/lucknow-to-delhi',
       'https://www.redbus.in/bus-tickets/allahabad-to-lucknow',
       'https://www.redbus.in/bus-tickets/delhi-to-farrukhabad-up',
       'https://www.redbus.in/bus-tickets/delhi-to-sitapur',
       'https://www.redbus.in/bus-tickets/agra-to-lucknow',
       'https://www.redbus.in/bus-tickets/delhi-to-gorakhpur',
       'https://www.redbus.in/bus-tickets/farrukhabad-up-to-delhi',
       'https://www.redbus.in/bus-tickets/lucknow-to-varanasi',
       'https://www.redbus.in/bus-tickets/delhi-to-moradabad',
       'https://www.redbus.in/bus-tickets/lucknow-to-ballia',
       'https://www.redbus.in/bus-tickets/aligarh-to-lucknow',
       'https://www.redbus.in/bus-tickets/moradabad-to-delhi',
       'https://www.redbus.in/bus-tickets/sitapur-to-delhi',
       'https://www.redbus.in/bus-tickets/delhi-to-shahjahanpur',
       'https://www.redbus.in/bus-tickets/greater-noida-to-lucknow',
       'https://www.redbus.in/bus-tickets/kanpur-to-varanasi',
       'https://www.redbus.in/bus-tickets/gorakhpur-to-lucknow',
       'https://www.redbus.in/bus-tickets/delhi-to-agra',
       'https://www.redbus.in/bus-tickets/delhi-to-badaun',
       'https://www.redbus.in/bus-tickets/delhi-to-kanpur',
       'https://www.redbus.in/bus-tickets/delhi-to-pilibhit',
       'https://www.redbus.in/bus-tickets/lucknow-to-mathura',
       'https://www.redbus.in/bus-tickets/kanpur-to-bareilly',
       'https://www.redbus.in/bus-tickets/bareilly-to-lucknow',
       'https://www.redbus.in/bus-tickets/dehradun-to-bareilly',
       'https://www.redbus.in/bus-tickets/badaun-to-delhi',
       'https://www.redbus.in/bus-tickets/agra-to-bareilly',
       'https://www.redbus.in/bus-tickets/ballia-to-lucknow',
       'https://www.redbus.in/bus-tickets/delhi-to-kotdwar-uttarakhand',
       'https://www.redbus.in/bus-tickets/lucknow-to-agra',
       'https://www.redbus.in/bus-tickets/agra-to-delhi',
       'https://www.redbus.in/bus-tickets/gorakhpur-to-delhi',
       'https://www.redbus.in/bus-tickets/bareilly-to-dehradun',
       'https://www.redbus.in/bus-tickets/jhansi-to-kanpur',
       'https://www.redbus.in/bus-tickets/mathura-to-lucknow',
       'https://www.redbus.in/bus-tickets/varanasi-to-lucknow',
       'https://www.redbus.in/bus-tickets/lucknow-to-bareilly',
       'https://www.redbus.in/bus-tickets/bareilly-to-agra',
       'https://www.redbus.in/bus-tickets/delhi-to-haldwani',
       'https://www.redbus.in/bus-tickets/allahabad-to-azamgarh',
       'https://www.redbus.in/bus-tickets/shahjahanpur-to-delhi',
       'https://www.redbus.in/bus-tickets/mandarmani-to-kolkata',
       'https://www.redbus.in/bus-tickets/kolkata-to-mandarmani',
       'https://www.redbus.in/bus-tickets/delhi-to-shimla',
       'https://www.redbus.in/bus-tickets/hamirpur-himachal-pradesh-to-chandigarh',
       'https://www.redbus.in/bus-tickets/chandigarh-to-hamirpur-himachal-pradesh',
       'https://www.redbus.in/bus-tickets/shimla-to-delhi',
       'https://www.redbus.in/bus-tickets/hamirpur-himachal-pradesh-to-delhi',
       'https://www.redbus.in/bus-tickets/delhi-to-hamirpur-himachal-pradesh',
       'https://www.redbus.in/bus-tickets/kangra-to-chandigarh',
       'https://www.redbus.in/bus-tickets/chamba-himachal-pradesh-to-chandigarh',
       'https://www.redbus.in/bus-tickets/delhi-to-chandigarh',
       'https://www.redbus.in/bus-tickets/palampur-to-chandigarh',
       'https://www.redbus.in/bus-tickets/dharamshala-to-chandigarh',
       'https://www.redbus.in/bus-tickets/chandigarh-to-dharamshala',
       'https://www.redbus.in/bus-tickets/delhi-to-chamba-himachal-pradesh',
       'https://www.redbus.in/bus-tickets/chandigarh-to-palampur',
       'https://www.redbus.in/bus-tickets/delhi-to-nalagarh',
       'https://www.redbus.in/bus-tickets/shimla-to-chandigarh',
       'https://www.redbus.in/bus-tickets/chandigarh-to-kangra',
       'https://www.redbus.in/bus-tickets/ghumarwin-to-chandigarh',
       'https://www.redbus.in/bus-tickets/chamba-himachal-pradesh-to-delhi',
       'https://www.redbus.in/bus-tickets/chandigarh-to-kullu',
       'https://www.redbus.in/bus-tickets/manali-to-chandigarh',
       'https://www.redbus.in/bus-tickets/delhi-to-solan',
       'https://www.redbus.in/bus-tickets/shimla-to-manali',
       'https://www.redbus.in/bus-tickets/chandigarh-to-manali',
       'https://www.redbus.in/bus-tickets/kullu-to-shimla',
       'https://www.redbus.in/bus-tickets/jassur-to-chandigarh',
       'https://www.redbus.in/bus-tickets/solan-to-delhi',
       'https://www.redbus.in/bus-tickets/sundernagar-himachal-pradesh-to-chandigarh',
       'https://www.redbus.in/bus-tickets/chandigarh-to-sarkaghat',
       'https://www.redbus.in/bus-tickets/delhi-to-bilaspur-himachal-pradesh',
       'https://www.redbus.in/bus-tickets/kangra-to-delhi',
       'https://www.redbus.in/bus-tickets/palampur-to-delhi',
       'https://www.redbus.in/bus-tickets/delhi-to-palampur',
       'https://www.redbus.in/bus-tickets/delhi-to-sarkaghat',
       'https://www.redbus.in/bus-tickets/ghumarwin-to-delhi',
       'https://www.redbus.in/bus-tickets/manali-to-shimla',
       'https://www.redbus.in/bus-tickets/baddi-himachal-pradesh-to-delhi'],
      dtype=object)

In [31]:
df_combined['Route_name'].unique()

array(['Pune to Goa', 'Goa to Pune', 'Mumbai to Goa', 'Goa to Mumbai',
       'Belagavi to Goa', 'Bangalore to Goa', 'Goa to Bangalore',
       'Goa to Belagavi', 'Goa to Kolhapur(Maharashtra)',
       'Solapur to Goa', 'Goa to Pandharpur', 'Goa to Solapur',
       'Calangute (goa) to Goa Airport', 'Goa to Sangola (Solapur)',
       'Sangola (Solapur) to Goa', 'Calangute (goa) to Mopa Airport',
       'Goa Airport to Calangute (goa)',
       'Mopa Airport to Calangute (goa)', 'Shivamogga to Goa',
       'Marcel to Belagavi', 'Ponda to Belagavi', 'Belagavi to Marcel',
       'Belagavi to Ponda', 'Panaji to Goa Airport', 'Goa to Sangli',
       'Goa to Miraj', 'Margao to Mopa Airport', 'Mopa Airport to Goa',
       'Mopa Airport to Margao', 'Goa Airport to Panaji', 'Shirdi to Goa',
       'Goa to Shivamogga', 'Goa to Satara', 'Panaji to Mopa Airport',
       'Saquelim to Belagavi', 'Goa to Shirdi', 'Calangute (goa) to Goa',
       'Mopa Airport to Panaji', 'Belagavi to Saquelim',
       'Calangute (goa) to Panaji', 'Jodhpur to Ajmer',
       'Beawar (Rajasthan) to Jaipur (Rajasthan)', 'Udaipur to Jodhpur',
       'Jaipur (Rajasthan) to Jodhpur', 'Sikar to Jaipur (Rajasthan)',
       'Aligarh (uttar pradesh) to Jaipur (Rajasthan)',
       'Kota(Rajasthan) to Jaipur (Rajasthan)',
       'Jaipur (Rajasthan) to Pilani',
       'Jaipur (Rajasthan) to Aligarh (uttar pradesh)',
       'Kishangarh to Jaipur (Rajasthan)', 'Sikar to Bikaner',
       'Jodhpur to Beawar (Rajasthan)', 'Udaipur to Pali (Rajasthan)',
       'Jaipur (Rajasthan) to Kota(Rajasthan)',
       'Kota(Rajasthan) to Udaipur', 'Jaipur (Rajasthan) to Bharatpur',
       'Jaipur (Rajasthan) to Mathura', 'Bikaner to Sikar',
       'Pali (Rajasthan) to Udaipur', 'Udaipur to Jaipur (Rajasthan)',
       'Khammam to Hyderabad', 'Hyderabad to Vijayawada',
       'Hyderabad to Khammam', 'Hyderabad to Srisailam',
       'Karimnagar to Hyderabad', 'Hyderabad to Adilabad',
       'Kothagudem to Hyderabad', 'Hyderabad to Mancherial',
       'Guntur (Andhra Pradesh) to Hyderabad',
       'Godavarikhani to Hyderabad', 'Kodad to Hyderabad',
       'Hyderabad to Ongole', 'Jagityal to Hyderabad',
       'Hyderabad to Nirmal', 'Hyderabad to Guntur (Andhra Pradesh)',
       'Hyderabad to Karimnagar', 'Hyderabad to Kothagudem',
       'Hyderabad to Bhadrachalam', 'Hyderabad to Sathupally',
       'Hyderabad to Warangal', 'Hyderabad to Tirupati',
       'Hyderabad to Anantapur (andhra pradesh)', 'Hyderabad to Armoor',
       'Hyderabad to Godavarikhani',
       'Peddapalli (Telangana) to Hyderabad', 'Hyderabad to Kodad',
       'Bangalore to Kozhikode', 'Kozhikode to Ernakulam',
       'Kozhikode to Bangalore', 'Ernakulam to Kozhikode',
       'Mysore to Kozhikode', 'Kozhikode to Mysore',
       'Kozhikode to Thrissur', 'Kozhikode to Thiruvananthapuram',
       'Kozhikode to Kottayam', 'Thrissur to Kozhikode',
       'Bangalore to Kalpetta (kerala)', 'Bangalore to Kannur (Kerala)',
       'Kalpetta (kerala) to Bangalore', 'Kottayam to Kozhikode',
       'Thiruvananthapuram to Kozhikode', 'Kannur (Kerala) to Bangalore',
       'Kozhikode to Aluva', 'Tezpur to Guwahati', 'Guwahati to Tezpur',
       'Guwahati to Nagaon (Assam)', 'Dhubri to Guwahati',
       'Tezpur to Dibrugarh', 'Dibrugarh to Jorhat',
       'North Lakhimpur to Dibrugarh', 'Guwahati to Biswanath Charali',
       'Biswanath Charali to Guwahati', 'Dibrugarh to Tezpur',
       'Bokakhat to Dibrugarh', 'Moran to Tezpur',
       'Dibrugarh to North Lakhimpur', 'North Lakhimpur to Tezpur',
       'Dibrugarh to Biswanath Charali', 'Gohpur to Dibrugarh',
       'Gohpur to Guwahati', 'Guwahati to Gohpur', 'Guwahati to Kaliabor',
       'North Lakhimpur to Guwahati', 'Tezpur to Tinsukia',
       'Tezpur to North Lakhimpur', 'North Lakhimpur to Nagaon (Assam)',
       'Durgapur (West Bengal) to Kolkata', 'Kolkata to Burdwan',
       'Kolkata to Durgapur (West Bengal)', 'Haldia to Kolkata',
       'Kolkata to Haldia', 'Kolkata to Arambagh (West Bengal)',
       'Kolkata to Digha', 'Digha to Kolkata', 'Kolkata to Bankura',
       'Kolkata to Asansol (West Bengal)', 'Kolkata to Midnapore',
       'Jhargram to Kolkata', 'Kolkata to Contai (Kanthi)',
       'Kolkata to Nimtouri', 'Digha to Durgapur (West Bengal)',
       'Kolkata to Nandakumar (west bengal)', 'Kolkata to Kolaghat',
       'Kolkata to Mecheda (West Bengal)',
       'Durgapur (West Bengal) to Barasat (West Bengal)',
       'Kolkata to Chandipur (West Bengal)',
       'Berhampore (West Bengal) to Durgapur (West Bengal)',
       'Durgapur (West Bengal) to Digha',
       'Durgapur (West Bengal) to Berhampore (West Bengal)',
       'Digha to Barasat (West Bengal)', 'Kolkata to Heria',
       'Kolkata to Bajkul (West Bengal)', 'Kolkata to Debra',
       'Kolkata to Ramnagar (West Bengal)',
       'Kolkata to Kirnahar (West Bengal)', 'Kolkata to Jhargram',
       'Kolkata to Panskura', 'Durgapur (West Bengal) to Bankura',
       'Siliguri to Kolkata', 'Vijayawada to Hyderabad',
       'Kakinada to Visakhapatnam',
       'Chittoor (Andhra Pradesh) to Bangalore', 'Bangalore to Tirupati',
       'Tirupati to Bangalore', 'Kadapa to Bangalore',
       'Anantapur (andhra pradesh) to Bangalore', 'Bangalore to Kadapa',
       'Ongole to Hyderabad', 'Bangalore to Chittoor (Andhra Pradesh)',
       'Bangalore to Anantapur (andhra pradesh)',
       'Visakhapatnam to Kakinada', 'Kadiri to Bangalore',
       'Vinukonda to Hyderabad', 'Bangalore to Kadiri',
       'Hyderabad to Narasaraopet', 'Madanapalli to Bangalore',
       'Narasaraopet to Hyderabad', 'Rajahmundry to Visakhapatnam',
       'Eluru to Hyderabad', 'Chennai to Tirupati',
       'Bangalore to Madanapalli', 'Rayachoti to Bangalore',
       'Hyderabad to Kurnool', 'Tirupati to Chennai',
       'Visakhapatnam to Vijayawada', 'Rajahmundry to Vijayawada',
       'Macherla (andhra pradesh) to Hyderabad', 'Nandyal to Hyderabad',
       'Hyderabad to Eluru', 'Bangalore to Rayachoti',
       'Kurnool to Hyderabad', 'Hyderabad to Vinukonda',
       'Vijayawada to Visakhapatnam', 'Kurnool to Bangalore',
       'Rajahmundry to Hyderabad', 'Amalapuram to Visakhapatnam',
       'Kurnool to Vijayawada', 'Visakhapatnam to Rajahmundry',
       'Hyderabad to Macherla (andhra pradesh)', 'Nellore to Bangalore',
       'Tadipatri to Bangalore', 'Kakinada to Vijayawada',
       'Visakhapatnam to Amalapuram', 'Hyderabad to Markapuram',
       'Hyderabad to Nandyal', 'Delhi to Bareilly (Uttar Pradesh)',
       'Delhi to Lucknow', 'Bareilly (Uttar Pradesh) to Delhi',
       'Lucknow to Gorakhpur (uttar pradesh)',
       'Aligarh (uttar pradesh) to Delhi',
       'Lucknow to Prayagraj(Uttar Pradesh)',
       'Delhi to Aligarh (uttar pradesh)', 'Lucknow to Delhi',
       'Prayagraj(Uttar Pradesh) to Lucknow',
       'Delhi to Farrukhabad (Uttar Pradesh)',
       'Delhi to Sitapur (Uttar Pradesh)', 'Agra to Lucknow',
       'Delhi to Gorakhpur (uttar pradesh)',
       'Farrukhabad (Uttar Pradesh) to Delhi', 'Lucknow to Varanasi',
       'Delhi to Moradabad', 'Lucknow to Ballia (Uttar Pradesh)',
       'Aligarh (uttar pradesh) to Lucknow', 'Moradabad to Delhi',
       'Sitapur (Uttar Pradesh) to Delhi',
       'Delhi to Shahjahanpur (Uttar Pradesh)',
       'Greater noida (uttar pradesh) to Lucknow',
       'Kanpur (Uttar Pradesh) to Varanasi',
       'Gorakhpur (uttar pradesh) to Lucknow', 'Delhi to Agra',
       'Delhi to Badaun', 'Delhi to Kanpur (Uttar Pradesh)',
       'Delhi to Pilibhit', 'Lucknow to Mathura',
       'Kanpur (Uttar Pradesh) to Bareilly (Uttar Pradesh)',
       'Bareilly (Uttar Pradesh) to Lucknow',
       'Dehradun to Bareilly (Uttar Pradesh)', 'Badaun to Delhi',
       'Agra to Bareilly (Uttar Pradesh)',
       'Ballia (Uttar Pradesh) to Lucknow',
       'Delhi to Kotdwar (Uttarakhand)', 'Lucknow to Agra',
       'Agra to Delhi', 'Gorakhpur (uttar pradesh) to Delhi',
       'Bareilly (Uttar Pradesh) to Dehradun',
       'Jhansi(Uttar Pradesh) to Kanpur (Uttar Pradesh)',
       'Mathura to Lucknow', 'Varanasi to Lucknow',
       'Lucknow to Bareilly (Uttar Pradesh)',
       'Bareilly (Uttar Pradesh) to Agra', 'Delhi to Haldwani',
       'Prayagraj(Uttar Pradesh) to Azamgarh',
       'Shahjahanpur (Uttar Pradesh) to Delhi', 'Mandarmani to Kolkata',
       'Kolkata to Mandarmani', 'Delhi to Shimla',
       'Hamirpur (Himachal Pradesh) to Chandigarh',
       'Chandigarh to Hamirpur (Himachal Pradesh)', 'Shimla to Delhi',
       'Hamirpur (Himachal Pradesh) to Delhi',
       'Delhi to Hamirpur (Himachal Pradesh)', 'Kangra to Chandigarh',
       'Chamba (Himachal Pradesh) to Chandigarh', 'Delhi to Chandigarh',
       'Palampur to Chandigarh',
       'Dharamshala (Himachal Pradesh) to Chandigarh',
       'Chandigarh to Dharamshala (Himachal Pradesh)',
       'Delhi to Chamba (Himachal Pradesh)', 'Chandigarh to Palampur',
       'Delhi to Nalagarh', 'Shimla to Chandigarh',
       'Chandigarh to Kangra', 'Ghumarwin to Chandigarh',
       'Chamba (Himachal Pradesh) to Delhi', 'Chandigarh to Kullu',
       'Manali to Chandigarh', 'Delhi to Solan', 'Shimla to Manali',
       'Chandigarh to Manali', 'Kullu to Shimla', 'Jassur to Chandigarh',
       'Solan to Delhi', 'Sunder Nagar (Himachal Pradesh) to Chandigarh',
       'Chandigarh to Sarkaghat', 'Delhi to Bilaspur (Himachal Pradesh)',
       'Kangra to Delhi', 'Palampur to Delhi', 'Delhi to Palampur',
       'Delhi to Sarkaghat', 'Ghumarwin to Delhi', 'Manali to Shimla',
       'Baddi (Himachal Pradesh) to Delhi'], dtype=object)

In [32]:
df_combined['States'].unique()

array(['Goa ', 'Rajasthan ', 'Telangana ', ' Kerala', ' Assam',
       'South bengal ', 'Andhra ', 'Uttar pradesh ', 'West bengal ',
       'Himachal '], dtype=object)

In [33]:
# Remove leading and trailing white spaces from the 'States' column
df_combined['States'] = df_combined['States'].str.strip()

# Display the unique values after cleaning
print(df_combined['States'].unique())

['Goa' 'Rajasthan' 'Telangana' 'Kerala' 'Assam' 'South bengal' 'Andhra'
 'Uttar pradesh' 'West bengal' 'Himachal']

In [34]:
missing_values = df_combined.isnull().sum()
print("Missing values per column:\n", missing_values)

Missing values per column:
 Bus_name           0
Bus_type           0
Start_time         0
End_time           0
Total_duration     0
Price              0
Seats_Available    0
Ratings            0
Route_link         0
Route_name         0
States             0
dtype: int64

In [35]:
# Remove rows with missing values in any column
df_combined = df_combined.dropna()

In [36]:
print("Data after removing rows with missing values:\n", df_combined)

Data after removing rows with missing values:
                                                Bus_name  \
0                                         Atmaram Gobus
1                                         Atmaram Gobus
2                                     IntrCity SmartBus
3                                       Ashray Amrutyog
4     Kadamba Transport Corporation Limited (KTCL) -...
...                                                 ...
1119                                         HRTC - 726
1120                                         HRTC - 155
1121                                         HRTC - 718
1122                                        HRTC - 6709
1123                                        HRTC - 6639

                                   Bus_type Start_time  End_time  \
0                      VE A/C Sleeper (2+1)   21:00:00  07:30:00
1                      VE A/C Sleeper (2+1)   22:30:00  08:45:00
2     Bharat Benz A/C Seater /Sleeper (2+1)   21:15:00  08:05:00
3                         A/C Sleeper (2+1)   22:05:00  09:30:00
4                         Non AC Seater 2+2   18:00:00  08:00:00
...                                     ...        ...       ...
1119             Ordinary 3+2 Non AC Seater   19:20:00  04:30:00
1120     Himsuta AC Seater Volvo/Scania 2+2   21:00:00  06:10:00
1121             Ordinary 3+2 Non AC Seater   21:30:00  06:35:00
1122             Ordinary 3+2 Non AC Seater   19:30:00  02:40:00
1123     Himsuta AC Seater Volvo/Scania 2+2   20:45:00  03:30:00

     Total_duration   Price  Seats_Available  Ratings  \
0          04:30:00  1450.0                6      4.7
1          07:15:00  1499.0                3      4.6
2          05:20:00  1419.0               19      4.5
3          07:35:00  1599.0               17      4.4
4          02:00:00   600.0               26      4.0
...             ...     ...              ...      ...
1119       09:10:00   583.0               27      3.7
1120       09:10:00   963.0               15      3.8
1121       09:05:00   583.0               31      3.3
1122       07:10:00   325.0               35      3.5
1123       06:45:00   612.0               29      3.8

                                             Route_link  \
0         https://www.redbus.in/bus-tickets/pune-to-goa
1         https://www.redbus.in/bus-tickets/pune-to-goa
2         https://www.redbus.in/bus-tickets/pune-to-goa
3         https://www.redbus.in/bus-tickets/pune-to-goa
4         https://www.redbus.in/bus-tickets/goa-to-pune
...                                                 ...
1119  https://www.redbus.in/bus-tickets/manali-to-sh...
1120  https://www.redbus.in/bus-tickets/manali-to-sh...
1121  https://www.redbus.in/bus-tickets/manali-to-sh...
1122  https://www.redbus.in/bus-tickets/baddi-himach...
1123  https://www.redbus.in/bus-tickets/baddi-himach...

                             Route_name    States
0                           Pune to Goa       Goa
1                           Pune to Goa       Goa
2                           Pune to Goa       Goa
3                           Pune to Goa       Goa
4                           Goa to Pune       Goa
...                                 ...       ...
1119                   Manali to Shimla  Himachal
1120                   Manali to Shimla  Himachal
1121                   Manali to Shimla  Himachal
1122  Baddi (Himachal Pradesh) to Delhi  Himachal
1123  Baddi (Himachal Pradesh) to Delhi  Himachal

[1124 rows x 11 columns]

In [37]:
df_combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1124 entries, 0 to 1123
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Bus_name         1124 non-null   object
 1   Bus_type         1124 non-null   object
 2   Start_time       1124 non-null   object
 3   End_time         1124 non-null   object
 4   Total_duration   1124 non-null   object
 5   Price            1124 non-null   object
 6   Seats_Available  1124 non-null   int64
 7   Ratings          1124 non-null   float64
 8   Route_link       1124 non-null   object
 9   Route_name       1124 non-null   object
 10  States           1124 non-null   object
dtypes: float64(1), int64(1), object(9)
memory usage: 96.7+ KB

In [38]:
df_combined.to_csv('df_combined.csv', index=False)

In [39]:
df_combined

,Bus_name,Bus_type,Start_time,End_time,Total_duration,Price,Seats_Available,Ratings,Route_link,Route_name,States
0,Atmaram Gobus,VE A/C Sleeper (2+1),21:00:00,07:30:00,04:30:00,1450.0,6,4.7,https://www.redbus.in/bus-tickets/pune-to-goa,Pune to Goa,Goa
1,Atmaram Gobus,VE A/C Sleeper (2+1),22:30:00,08:45:00,07:15:00,1499.0,3,4.6,https://www.redbus.in/bus-tickets/pune-to-goa,Pune to Goa,Goa
2,IntrCity SmartBus,Bharat Benz A/C Seater /Sleeper (2+1),21:15:00,08:05:00,05:20:00,1419.0,19,4.5,https://www.redbus.in/bus-tickets/pune-to-goa,Pune to Goa,Goa
3,Ashray Amrutyog,A/C Sleeper (2+1),22:05:00,09:30:00,07:35:00,1599.0,17,4.4,https://www.redbus.in/bus-tickets/pune-to-goa,Pune to Goa,Goa
4,Kadamba Transport Corporation Limited (KTCL) -...,Non AC Seater 2+2,18:00:00,08:00:00,02:00:00,600.0,26,4.0,https://www.redbus.in/bus-tickets/goa-to-pune,Goa to Pune,Goa
...,...,...,...,...,...,...,...,...,...,...,...
1119,HRTC - 726,Ordinary 3+2 Non AC Seater,19:20:00,04:30:00,09:10:00,583.0,27,3.7,https://www.redbus.in/bus-tickets/manali-to-sh...,Manali to Shimla,Himachal
1120,HRTC - 155,Himsuta AC Seater Volvo/Scania 2+2,21:00:00,06:10:00,09:10:00,963.0,15,3.8,https://www.redbus.in/bus-tickets/manali-to-sh...,Manali to Shimla,Himachal
1121,HRTC - 718,Ordinary 3+2 Non AC Seater,21:30:00,06:35:00,09:05:00,583.0,31,3.3,https://www.redbus.in/bus-tickets/manali-to-sh...,Manali to Shimla,Himachal
1122,HRTC - 6709,Ordinary 3+2 Non AC Seater,19:30:00,02:40:00,07:10:00,325.0,35,3.5,https://www.redbus.in/bus-tickets/baddi-himach...,Baddi (Himachal Pradesh) to Delhi,Himachal
1123,HRTC - 6639,Himsuta AC Seater Volvo/Scania 2+2,20:45:00,03:30:00,06:45:00,612.0,29,3.8,https://www.redbus.in/bus-tickets/baddi-himach...,Baddi (Himachal Pradesh) to Delhi,Himachal

**Create a mysql database**

In [51]:
import mysql.connector
import pandas as pd

connection = mysql.connector.connect(
    host='localhost',
    user='root',
    password='123456789',
    database='redbusquery'
)

cursor = connection.cursor()

query = 'CREATE DATABASE IF NOT EXISTS redbusquery'
cursor.execute(query)
if connection.is_connected():
    print("Connected to MySQL database")

Connected to MySQL database

In [52]:
# Drop the table if it exists
cursor.execute("DROP TABLE IF EXISTS Bus_data;")
connection.commit()

# Recreate the table
query = """
CREATE TABLE IF NOT EXISTS Bus_data (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Bus_name TEXT,
    Bus_type TEXT,
    Start_time TIME,
    End_time TIME,
    Total_duration TEXT,
    Price DECIMAL(10, 2),
    Seats_Available INT,
    Ratings FLOAT,
    Route_link TEXT,
    Route_name TEXT,
    States TEXT
);
"""
cursor.execute(query)
connection.commit()
print("Table created successfully with States column.")

Table created successfully with States column.

In [53]:
# Prepare insert query with exact column names
insert_query = """
INSERT INTO Bus_data (
    Bus_name, 
    Bus_type, 
    Start_time, 
    End_time, 
    Total_duration, 
    Price, 
    Seats_Available, 
    Ratings, 
    Route_link, 
    Route_name, 
    States
) 
VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);
"""

In [54]:
print(df_combined.columns)

Index(['Bus_name', 'Bus_type', 'Start_time', 'End_time', 'Total_duration',
       'Price', 'Seats_Available', 'Ratings', 'Route_link', 'Route_name',
       'States'],
      dtype='object')

In [55]:

df_combined.columns = df_combined.columns.str.strip()

In [56]:
cursor.fetchall()  # This will clear any previous result set if there was one

# Execute the DESCRIBE query to get the table structure
cursor.execute("DESCRIBE Bus_data;")

# Fetch the result of the query
table_structure = cursor.fetchall()

# Display the table structure
for column in table_structure:
    print(column)

('id', 'int', 'NO', 'PRI', None, 'auto_increment')
('Bus_name', 'text', 'YES', '', None, '')
('Bus_type', 'text', 'YES', '', None, '')
('Start_time', 'time', 'YES', '', None, '')
('End_time', 'time', 'YES', '', None, '')
('Total_duration', 'text', 'YES', '', None, '')
('Price', 'decimal(10,2)', 'YES', '', None, '')
('Seats_Available', 'int', 'YES', '', None, '')
('Ratings', 'float', 'YES', '', None, '')
('Route_link', 'text', 'YES', '', None, '')
('Route_name', 'text', 'YES', '', None, '')
('States', 'text', 'YES', '', None, '')

In [57]:
# Convert DataFrame to list of tuples with proper column names
data = df_combined[['Bus_name', 'Bus_type', 'Start_time', 'End_time', 'Total_duration', 
                    'Price', 'Seats_Available', 'Ratings', 'Route_link', 'Route_name','States']].values.tolist()

# Insert data into the table
try:
    cursor.executemany(insert_query, data)
    connection.commit()
    print("Data inserted successfully.")
except mysql.connector.Error as err:
    print(f"Error: {err}")
    connection.rollback()

Data inserted successfully.

In [58]:
# Create a cursor object
cursor = connection.cursor()

# Your SELECT query
query = "SELECT * FROM Bus_data"

# Execute the query
cursor.execute(query)

# Fetch all rows from the result of the query
data = cursor.fetchall()

# Print the data fetched from the table
for row in data:
    print(row)

# Close the cursor and connection
#cursor.close()
#connection.close()

(1, 'Atmaram Gobus', 'VE A/C Sleeper (2+1)', datetime.timedelta(seconds=75600), datetime.timedelta(seconds=27000), '04:30:00', Decimal('1450.00'), 6, 4.7, 'https://www.redbus.in/bus-tickets/pune-to-goa', 'Pune to Goa', 'Goa')
(2, 'Atmaram Gobus', 'VE A/C Sleeper (2+1)', datetime.timedelta(seconds=81000), datetime.timedelta(seconds=31500), '07:15:00', Decimal('1499.00'), 3, 4.6, 'https://www.redbus.in/bus-tickets/pune-to-goa', 'Pune to Goa', 'Goa')
(3, 'IntrCity SmartBus', 'Bharat Benz A/C Seater /Sleeper (2+1)', datetime.timedelta(seconds=76500), datetime.timedelta(seconds=29100), '05:20:00', Decimal('1419.00'), 19, 4.5, 'https://www.redbus.in/bus-tickets/pune-to-goa', 'Pune to Goa', 'Goa')
(4, 'Ashray Amrutyog', 'A/C Sleeper (2+1)', datetime.timedelta(seconds=79500), datetime.timedelta(seconds=34200), '07:35:00', Decimal('1599.00'), 17, 4.4, 'https://www.redbus.in/bus-tickets/pune-to-goa', 'Pune to Goa', 'Goa')
(5, 'Kadamba Transport Corporation Limited (KTCL) - 6032', 'Non AC Seater 2+2', datetime.timedelta(seconds=64800), datetime.timedelta(seconds=28800), '02:00:00', Decimal('600.00'), 26, 4.0, 'https://www.redbus.in/bus-tickets/goa-to-pune', 'Goa to Pune', 'Goa')
(6, 'Atmaram Gobus', 'VE A/C Sleeper (2+1)', datetime.timedelta(seconds=81000), datetime.timedelta(seconds=27900), '06:15:00', Decimal('1099.00'), 2, 4.8, 'https://www.redbus.in/bus-tickets/goa-to-pune', 'Goa to Pune', 'Goa')
(7, 'Atmaram Gobus', 'VE A/C Sleeper (2+1)', datetime.timedelta(seconds=77520), datetime.timedelta(seconds=25320), '04:34:00', Decimal('900.00'), 11, 4.7, 'https://www.redbus.in/bus-tickets/goa-to-pune', 'Goa to Pune', 'Goa')
(8, 'IntrCity SmartBus', 'Bharat Benz A/C Seater /Sleeper (2+1)', datetime.timedelta(seconds=73800), datetime.timedelta(seconds=24300), '03:15:00', Decimal('600.00'), 22, 4.6, 'https://www.redbus.in/bus-tickets/goa-to-pune', 'Goa to Pune', 'Goa')
(9, 'IntrCity SmartBus', 'AC Sleeper (2+1)', datetime.timedelta(seconds=66600), datetime.timedelta(seconds=19500), '23:55:00', Decimal('1119.00'), 16, 4.6, 'https://www.redbus.in/bus-tickets/goa-to-pune', 'Goa to Pune', 'Goa')
(10, 'IntrCity SmartBus', 'AC Sleeper (2+1)', datetime.timedelta(seconds=59400), datetime.timedelta(seconds=31500), '01:15:00', Decimal('2193.00'), 18, 4.5, 'https://www.redbus.in/bus-tickets/mumbai-to-goa', 'Mumbai to Goa', 'Goa')
(11, 'Zingbus Plus', 'VE A/C Sleeper (2+1)', datetime.timedelta(seconds=72000), datetime.timedelta(seconds=42900), '07:55:00', Decimal('1782.00'), 17, 4.4, 'https://www.redbus.in/bus-tickets/mumbai-to-goa', 'Mumbai to Goa', 'Goa')
(12, 'Zingbus Plus', 'Bharat Benz A/C Sleeper (2+1)', datetime.timedelta(seconds=70500), datetime.timedelta(seconds=37200), '05:55:00', Decimal('1945.00'), 15, 4.4, 'https://www.redbus.in/bus-tickets/mumbai-to-goa', 'Mumbai to Goa', 'Goa')
(13, 'AdShubhra Sharma Tourist Services', 'A/C Sleeper (2+1)', datetime.timedelta(seconds=60360), datetime.timedelta(seconds=37860), '03:17:00', Decimal('1400.00'), 21, 4.0, 'https://www.redbus.in/bus-tickets/mumbai-to-goa', 'Mumbai to Goa', 'Goa')
(14, 'IntrCity SmartBus', 'AC Sleeper (2+1)', datetime.timedelta(seconds=62100), datetime.timedelta(seconds=31500), '02:00:00', Decimal('1722.00'), 22, 4.4, 'https://www.redbus.in/bus-tickets/mumbai-to-goa', 'Mumbai to Goa', 'Goa')
(15, 'Kadamba Transport Corporation Limited (KTCL) - 116186', 'Volvo AC Seater 2+2', datetime.timedelta(seconds=66600), datetime.timedelta(seconds=28800), '02:30:00', Decimal('1200.00'), 21, 4.0, 'https://www.redbus.in/bus-tickets/goa-to-mumbai', 'Goa to Mumbai', 'Goa')
(16, 'Zingbus Plus', 'VE A/C Sleeper (2+1)', datetime.timedelta(seconds=75000), datetime.timedelta(seconds=34200), '06:20:00', Decimal('1000.00'), 17, 4.5, 'https://www.redbus.in/bus-tickets/goa-to-mumbai', 'Goa to Mumbai', 'Goa')
(17, 'Zingbus Plus', 'Bharat Benz A/C Sleeper (2+1)', datetime.timedelta(seconds=70800), datetime.timedelta(seconds=36900), '05:55:00', Decimal('1000.00'), 25, 4.4, 'https://www.redbus.in/bus-tickets/goa-to-mumbai', 'Goa to Mumbai', 'Goa')
(18, 'IntrCity SmartBus', 'AC Sleeper (2+1)', datetime.timedelta(seconds=70200), datetime.timedelta(seconds=34800), '05:10:00', Decimal('1188.00'), 16, 4.4, 'https://www.redbus.in/bus-tickets/goa-to-mumbai', 'Goa to Mumbai', 'Goa')
(19, 'Kadamba Transport Corporation Limited (KTCL) - 6020', 'Non AC Seater 2+2', datetime.timedelta(seconds=57600), datetime.timedelta(seconds=71100), '11:45:00', Decimal('170.00'), 25, 4.1, 'https://www.redbus.in/bus-tickets/belagavi-to-goa', 'Belagavi to Goa', 'Goa')
(20, 'Gajal Tours And Travels', 'A/C Sleeper (2+1)', datetime.timedelta(seconds=14400), datetime.timedelta(seconds=36000), '14:00:00', Decimal('7200.00'), 27, 3.8, 'https://www.redbus.in/bus-tickets/belagavi-to-goa', 'Belagavi to Goa', 'Goa')
(21, 'Rajat Travels', 'A/C Seater / Sleeper (2+1)', datetime.timedelta(seconds=23400), datetime.timedelta(seconds=37800), '17:00:00', Decimal('1799.00'), 3, 3.2, 'https://www.redbus.in/bus-tickets/belagavi-to-goa', 'Belagavi to Goa', 'Goa')
(22, 'PVS Tours and Travels', 'A/C Sleeper (2+1)', datetime.timedelta(seconds=25200), datetime.timedelta(seconds=39600), '18:00:00', Decimal('1496.00'), 4, 3.4, 'https://www.redbus.in/bus-tickets/belagavi-to-goa', 'Belagavi to Goa', 'Goa')
(23, 'PVS Tours and Travels', 'A/C Sleeper (2+1)', datetime.timedelta(seconds=38100), datetime.timedelta(seconds=54000), '01:35:00', Decimal('1899.00'), 8, 3.4, 'https://www.redbus.in/bus-tickets/belagavi-to-goa', 'Belagavi to Goa', 'Goa')
(24, 'Kadamba Transport Corporation Limited (KTCL) - 141293', 'Volvo AC Seater 2+2', datetime.timedelta(seconds=71100), datetime.timedelta(seconds=29700), '04:00:00', Decimal('1200.00'), 1, 3.8, 'https://www.redbus.in/bus-tickets/bangalore-to-goa', 'Bangalore to Goa', 'Goa')
(25, 'Intercity travels', 'Bharat Benz A/C Sleeper (2+1)', datetime.timedelta(seconds=75600), datetime.timedelta(seconds=36900), '07:15:00', Decimal('2699.00'), 13, 4.5, 'https://www.redbus.in/bus-tickets/bangalore-to-goa', 'Bangalore to Goa', 'Goa')
(26, 'Sunrise Tours and Travels', 'A/C Sleeper (2+1)', datetime.timedelta(seconds=76800), datetime.timedelta(seconds=33900), '06:45:00', Decimal('2799.00'), 5, 4.5, 'https://www.redbus.in/bus-tickets/bangalore-to-goa', 'Bangalore to Goa', 'Goa')
(27, 'Streamline tours and travels', 'A/C Sleeper (2+1)', datetime.timedelta(seconds=75600), datetime.timedelta(seconds=36000), '07:00:00', Decimal('2370.00'), 18, 4.3, 'https://www.redbus.in/bus-tickets/bangalore-to-goa', 'Bangalore to Goa', 'Goa')
(28, 'Kadamba Transport Corporation Limited (KTCL) - 5633', 'Volvo AC Seater 2+2', datetime.timedelta(seconds=66600), datetime.timedelta(seconds=30600), '03:00:00', Decimal('800.00'), 27, 3.6, 'https://www.redbus.in/bus-tickets/goa-to-bangalore', 'Goa to Bangalore', 'Goa')
(29, 'Intercity travels', 'Bharat Benz A/C Sleeper (2+1)', datetime.timedelta(seconds=64800), datetime.timedelta(seconds=26100), '01:15:00', Decimal('999.00'), 20, 4.5, 'https://www.redbus.in/bus-tickets/goa-to-bangalore', 'Goa to Bangalore', 'Goa')
(30, 'IntrCity SmartBus', 'AC Sleeper (2+1)', datetime.timedelta(seconds=64800), datetime.timedelta(seconds=28200), '01:50:00', Decimal('879.00'), 29, 4.4, 'https://www.redbus.in/bus-tickets/goa-to-bangalore', 'Goa to Bangalore', 'Goa')
(31, 'AdStreamline tours and travels', 'A/C Sleeper (2+1)', datetime.timedelta(seconds=61200), datetime.timedelta(seconds=19800), '22:30:00', Decimal('999.00'), 30, 3.2, 'https://www.redbus.in/bus-tickets/goa-to-bangalore', 'Goa to Bangalore', 'Goa')
(32, 'IntrCity SmartBus', 'AC Sleeper (2+1)', datetime.timedelta(seconds=61200), datetime.timedelta(seconds=24000), '23:40:00', Decimal('809.00'), 23, 4.4, 'https://www.redbus.in/bus-tickets/goa-to-bangalore', 'Goa to Bangalore', 'Goa')
(33, 'Kadamba Transport Corporation Limited (KTCL) - 6028', 'Non AC Seater 2+2', datetime.timedelta(seconds=25200), datetime.timedelta(seconds=37800), '17:30:00', Decimal('170.00'), 19, 3.0, 'https://www.redbus.in/bus-tickets/goa-to-belagavi', 'Goa to Belagavi', 'Goa')
(34, 'National travels', 'Bharat Benz A/C Sleeper (2+1)', datetime.timedelta(seconds=57600), datetime.timedelta(seconds=80100), '14:15:00', Decimal('950.00'), 32, 3.3, 'https://www.redbus.in/bus-tickets/goa-to-belagavi', 'Goa to Belagavi', 'Goa')
(35, 'VRL Travels', 'A/C Sleeper (2+1)', datetime.timedelta(seconds=59400), datetime.timedelta(seconds=76200), '13:40:00', Decimal('1100.00'), 34, 3.4, 'https://www.redbus.in/bus-tickets/goa-to-belagavi', 'Goa to Belagavi', 'Goa')
(36, 'Shirdi Xpress', 'A/C Sleeper (2+1)', datetime.timedelta(seconds=61200), datetime.timedelta(seconds=77400), '14:30:00', Decimal('650.00'), 28, 3.3, 'https://www.redbus.in/bus-tickets/goa-to-belagavi', 'Goa to Belagavi', 'Goa')
(37, 'PSR Travels Goa', 'A/C Sleeper (2+1)', datetime.timedelta(seconds=61260), datetime.timedelta(seconds=81000), '15:31:00', Decimal('950.00'), 28, 3.5, 'https://www.redbus.in/bus-tickets/goa-to-belagavi', 'Goa to Belagavi', 'Goa')
(38, 'Ashoka Travels', 'A/C Sleeper (2+1)', datetime.timedelta(seconds=30600), datetime.timedelta(seconds=53400), '23:20:00', Decimal('449.00'), 23, 3.4, 'https://www.redbus.in/bus-tickets/goa-to-kolhapur-maharashtra', 'Goa to Kolhapur(Maharashtra)', 'Goa')
(39, 'Vaibhav Travels', 'A/C Sleeper (2+1)', datetime.timedelta(seconds=37200), datetime.timedelta(seconds=67800), '05:10:00', Decimal('350.00'), 34, 3.4, 'https://www.redbus.in/bus-tickets/goa-to-kolhapur-maharashtra', 'Goa to Kolhapur(Maharashtra)', 'Goa')
(40, 'URL Travels Neeta', 'A/C Sleeper (2+1)', datetime.timedelta(seconds=37800), datetime.timedelta(seconds=61200), '03:30:00', Decimal('450.00'), 21, 3.3, 'https://www.redbus.in/bus-tickets/goa-to-kolhapur-maharashtra', 'Goa to Kolhapur(Maharashtra)', 'Goa')
(41, 'KTC Travels (Neeta)', 'A/C Sleeper (2+1)', datetime.timedelta(seconds=45000), datetime.timedelta(seconds=68400), '07:30:00', Decimal('499.00'), 23, 4.0, 'https://www.redbus.in/bus-tickets/goa-to-kolhapur-maharashtra', 'Goa to Kolhapur(Maharashtra)', 'Goa')
(42, 'Kadamba Transport Corporation Limited (KTCL) - 61005', 'Non AC Seater 2+2', datetime.timedelta(seconds=72000), datetime.timedelta(seconds=36000), '06:00:00', Decimal('850.00'), 34, 3.6, 'https://www.redbus.in/bus-tickets/solapur-to-goa', 'Solapur to Goa', 'Goa')
(43, 'Humsafar Travels', 'Bharat Benz A/C Sleeper (2+1)', datetime.timedelta(seconds=83700), datetime.timedelta(seconds=28800), '07:15:00', Decimal('1850.00'), 28, 3.0, 'https://www.redbus.in/bus-tickets/solapur-to-goa', 'Solapur to Goa', 'Goa')
(44, 'Zingbus Plus', 'AC Sleeper (2+1)', datetime.timedelta(0), datetime.timedelta(seconds=32400), '09:00:00', Decimal('1499.00'), 12, 4.4, 'https://www.redbus.in/bus-tickets/solapur-to-goa', 'Solapur to Goa', 'Goa')
(45, 'S R Travels', 'A/C Seater/Sleeper (2+1)', datetime.timedelta(seconds=67500), datetime.timedelta(seconds=25200), '01:45:00', Decimal('700.00'), 16, 2.8, 'https://www.redbus.in/bus-tickets/solapur-to-goa', 'Solapur to Goa', 'Goa')
(46, 'Kadamba Transport Corporation Limited (KTCL) - 60996', 'Non AC Seater 2+2', datetime.timedelta(seconds=68400), datetime.timedelta(seconds=25200), '02:00:00', Decimal('735.00'), 24, 2.7, 'https://www.redbus.in/bus-tickets/goa-to-pandharpur', 'Goa to Pandharpur', 'Goa')
(47, 'New Shivbaba Tours And Travels', 'AC Sleeper (2+1)', datetime.timedelta(seconds=71100), datetime.timedelta(seconds=16200), '00:15:00', Decimal('949.00'), 26, 1.9, 'https://www.redbus.in/bus-tickets/goa-to-pandharpur', 'Goa to Pandharpur', 'Goa')
(48, 'Kadamba Transport Corporation Limited (KTCL) - 60996', 'Non AC Seater 2+2', datetime.timedelta(seconds=68400), datetime.timedelta(seconds=30600), '03:30:00', Decimal('850.00'), 24, 2.8, 'https://www.redbus.in/bus-tickets/goa-to-solapur', 'Goa to Solapur', 'Goa')
(49, 'Humsafar Travels', 'Bharat Benz A/C Sleeper (2+1)', datetime.timedelta(seconds=68400), datetime.timedelta(seconds=16200), '23:30:00', Decimal('1550.00'), 12, 3.9, 'https://www.redbus.in/bus-tickets/goa-to-solapur', 'Goa to Solapur', 'Goa')
(50, 'IntrCity SmartBus', 'AC Sleeper (2+1)', datetime.timedelta(seconds=60000), datetime.timedelta(seconds=14400), '20:40:00', Decimal('1044.00'), 23, 4.8, 'https://www.redbus.in/bus-tickets/goa-to-solapur', 'Goa to Solapur', 'Goa')
(51, 'IntrCity SmartBus', 'AC Sleeper (2+1)', datetime.timedelta(seconds=65400), datetime.timedelta(seconds=17100), '22:55:00', Decimal('899.00'), 26, 3.7, 'https://www.redbus.in/bus-tickets/goa-to-solapur', 'Goa to Solapur', 'Goa')
(52, 'IntrCity SmartBus', 'AC Sleeper (2+1)', datetime.timedelta(seconds=56400), datetime.timedelta(seconds=10800), '18:40:00', Decimal('978.00'), 17, 4.4, 'https://www.redbus.in/bus-tickets/goa-to-solapur', 'Goa to Solapur', 'Goa')
(53, 'Kadamba Transport Corporation Limited (KTCL) - 99716', 'AC Seater (2+2)', datetime.timedelta(seconds=36000), datetime.timedelta(seconds=42300), '21:45:00', Decimal('200.00'), 41, 4.3, 'https://www.redbus.in/bus-tickets/calangute-goa-to-goa-airport', 'Calangute (goa) to Goa Airport', 'Goa')
(54, 'Kadamba Transport Corporation Limited (KTCL) - 99718', 'AC Seater (2+2)', datetime.timedelta(seconds=55800), datetime.timedelta(seconds=62100), '08:45:00', Decimal('200.00'), 41, 3.7, 'https://www.redbus.in/bus-tickets/calangute-goa-to-goa-airport', 'Calangute (goa) to Goa Airport', 'Goa')
(55, 'Kadamba Transport Corporation Limited (KTCL) - 99719', 'AC Seater (2+2)', datetime.timedelta(seconds=66600), datetime.timedelta(seconds=72000), '14:30:00', Decimal('200.00'), 42, 4.6, 'https://www.redbus.in/bus-tickets/calangute-goa-to-goa-airport', 'Calangute (goa) to Goa Airport', 'Goa')
(56, 'Kadamba Transport Corporation Limited (KTCL) - 60996', 'Non AC Seater 2+2', datetime.timedelta(seconds=68400), datetime.timedelta(seconds=21900), '01:05:00', Decimal('675.00'), 25, 3.0, 'https://www.redbus.in/bus-tickets/goa-to-sangola', 'Goa to Sangola (Solapur)', 'Goa')
(57, 'Humsafar Travels', 'Bharat Benz A/C Sleeper (2+1)', datetime.timedelta(seconds=68400), datetime.timedelta(seconds=7200), '21:00:00', Decimal('1550.00'), 15, 3.6, 'https://www.redbus.in/bus-tickets/goa-to-sangola', 'Goa to Sangola (Solapur)', 'Goa')
(58, 'PSR Travels Goa', 'A/C Sleeper (2+1)', datetime.timedelta(seconds=66600), datetime.timedelta(seconds=15300), '22:45:00', Decimal('900.00'), 25, 3.5, 'https://www.redbus.in/bus-tickets/goa-to-sangola', 'Goa to Sangola (Solapur)', 'Goa')
(59, 'PSR Travels Goa', 'A/C Sleeper (2+1)', datetime.timedelta(seconds=66600), datetime.timedelta(seconds=15300), '22:45:00', Decimal('3000.00'), 36, 3.5, 'https://www.redbus.in/bus-tickets/goa-to-sangola', 'Goa to Sangola (Solapur)', 'Goa')
(60, 'Kadamba Transport Corporation Limited (KTCL) - 61005', 'Non AC Seater 2+2', datetime.timedelta(seconds=78300), datetime.timedelta(seconds=36000), '07:45:00', Decimal('675.00'), 36, 2.8, 'https://www.redbus.in/bus-tickets/sangola-to-goa', 'Sangola (Solapur) to Goa', 'Goa')
(61, 'Humsafar Travels', 'Bharat Benz A/C Sleeper (2+1)', datetime.timedelta(seconds=86340), datetime.timedelta(seconds=28800), '07:59:00', Decimal('1850.00'), 32, 3.8, 'https://www.redbus.in/bus-tickets/sangola-to-goa', 'Sangola (Solapur) to Goa', 'Goa')
(62, 'New Shivbaba Tours And Travels', 'AC Sleeper (2+1)', datetime.timedelta(seconds=73800), datetime.timedelta(seconds=21600), '02:30:00', Decimal('1139.00'), 24, 2.1, 'https://www.redbus.in/bus-tickets/sangola-to-goa', 'Sangola (Solapur) to Goa', 'Goa')
(63, 'Kadamba Transport Corporation Limited (KTCL) - 159017', 'A/C Seater (2+3)', datetime.timedelta(seconds=21600), datetime.timedelta(seconds=26100), '13:15:00', Decimal('200.00'), 46, 4.2, 'https://www.redbus.in/bus-tickets/calangute-goa-to-mopa-airport', 'Calangute (goa) to Mopa Airport', 'Goa')
(64, 'Kadamba Transport Corporation Limited (KTCL) - 159018', 'A/C Seater (2+3)', datetime.timedelta(seconds=25200), datetime.timedelta(seconds=29700), '15:15:00', Decimal('200.00'), 47, 2.9, 'https://www.redbus.in/bus-tickets/calangute-goa-to-mopa-airport', 'Calangute (goa) to Mopa Airport', 'Goa')
(65, 'Kadamba Transport Corporation Limited (KTCL) - 159019', 'A/C Seater (2+3)', datetime.timedelta(seconds=36000), datetime.timedelta(seconds=40500), '21:15:00', Decimal('200.00'), 45, 3.7, 'https://www.redbus.in/bus-tickets/calangute-goa-to-mopa-airport', 'Calangute (goa) to Mopa Airport', 'Goa')
(66, 'Kadamba Transport Corporation Limited (KTCL) - 159065', 'A/C Seater (2+3)', datetime.timedelta(seconds=42300), datetime.timedelta(seconds=46800), '00:45:00', Decimal('200.00'), 47, 2.9, 'https://www.redbus.in/bus-tickets/calangute-goa-to-mopa-airport', 'Calangute (goa) to Mopa Airport', 'Goa')
(67, 'Kadamba Transport Corporation Limited (KTCL) - 99708', 'AC Seater (2+2)', datetime.timedelta(seconds=27000), datetime.timedelta(seconds=33000), '16:40:00', Decimal('200.00'), 41, 3.7, 'https://www.redbus.in/bus-tickets/goa-airport-to-calangute-goa', 'Goa Airport to Calangute (goa)', 'Goa')
(68, 'Kadamba Transport Corporation Limited (KTCL) - 99707', 'AC Seater (2+2)', datetime.timedelta(seconds=49500), datetime.timedelta(seconds=55800), '05:15:00', Decimal('200.00'), 41, 4.2, 'https://www.redbus.in/bus-tickets/goa-airport-to-calangute-goa', 'Goa Airport to Calangute (goa)', 'Goa')
(69, 'Kadamba Transport Corporation Limited (KTCL) - 99710', 'AC Seater (2+2)', datetime.timedelta(seconds=57600), datetime.timedelta(seconds=63000), '09:30:00', Decimal('200.00'), 42, 4.0, 'https://www.redbus.in/bus-tickets/goa-airport-to-calangute-goa', 'Goa Airport to Calangute (goa)', 'Goa')
(70, 'Kadamba Transport Corporation Limited (KTCL) - 159022', 'A/C Seater (2+3)', datetime.timedelta(seconds=28800), datetime.timedelta(seconds=33000), '17:10:00', Decimal('200.00'), 42, 2.6, 'https://www.redbus.in/bus-tickets/mopa-airport-to-calangute-goa', 'Mopa Airport to Calangute (goa)', 'Goa')
(71, 'Kadamba Transport Corporation Limited (KTCL) - 159023', 'A/C Seater (2+3)', datetime.timedelta(seconds=36900), datetime.timedelta(seconds=41100), '21:40:00', Decimal('200.00'), 42, 5.0, 'https://www.redbus.in/bus-tickets/mopa-airport-to-calangute-goa', 'Mopa Airport to Calangute (goa)', 'Goa')
(72, 'Kadamba Transport Corporation Limited (KTCL) - 158988', 'A/C Seater (2+3)', datetime.timedelta(seconds=41400), datetime.timedelta(seconds=46500), '00:25:00', Decimal('200.00'), 47, 3.1, 'https://www.redbus.in/bus-tickets/mopa-airport-to-calangute-goa', 'Mopa Airport to Calangute (goa)', 'Goa')
(73, 'Kadamba Transport Corporation Limited (KTCL) - 159021', 'A/C Seater (2+3)', datetime.timedelta(seconds=43200), datetime.timedelta(seconds=47400), '01:10:00', Decimal('200.00'), 48, 4.8, 'https://www.redbus.in/bus-tickets/mopa-airport-to-calangute-goa', 'Mopa Airport to Calangute (goa)', 'Goa')
(74, 'Kadamba Transport Corporation Limited (KTCL) - 132897', 'Non AC Seater (2+2)', datetime.timedelta(seconds=82800), datetime.timedelta(seconds=28800), '07:00:00', Decimal('450.00'), 33, 1.7, 'https://www.redbus.in/bus-tickets/shimoga-to-goa', 'Shivamogga to Goa', 'Goa')
(75, 'Sea Bird Tourist', 'NON A/C Sleeper (2+1)', datetime.timedelta(seconds=85500), datetime.timedelta(seconds=28800), '07:45:00', Decimal('1400.00'), 19, 2.7, 'https://www.redbus.in/bus-tickets/shimoga-to-goa', 'Shivamogga to Goa', 'Goa')
(76, 'Kadamba Transport Corporation Limited (KTCL) - 6028', 'Non AC Seater 2+2', datetime.timedelta(seconds=28800), datetime.timedelta(seconds=37800), '18:30:00', Decimal('140.00'), 22, 3.6, 'https://www.redbus.in/bus-tickets/marcel-to-belagavi', 'Marcel to Belagavi', 'Goa')
(77, 'Kadamba Transport Corporation Limited (KTCL) - 6028', 'Non AC Seater 2+2', datetime.timedelta(seconds=27000), datetime.timedelta(seconds=37800), '18:00:00', Decimal('150.00'), 17, 3.6, 'https://www.redbus.in/bus-tickets/ponda-to-belagavi', 'Ponda to Belagavi', 'Goa')

In [62]:
print["Start_time"].dtype
print["Start_time"].head()

TypeError: 'builtin_function_or_method' object is not subscriptable